### ISSUE TITLE
Cannot disable tabufline in NvChad plugins override

### ISSUE THREAD

**Issue by JerryLiao26** [NvChad/ui#1]
I tried to disable tabufline in NvChad config with
```lua
-- custom/chadrc.lua
local M = {}

M.plugins = {
   override = {
      ["NvChad/ui"] = {
         tabufline = {
            enabled = false,
         },
      },
   },
}

return M
```
Is there something missing in the [init.lua file of tabufline](https://github.com/NvChad/ui/blob/main/lua/nvchad_ui/tabufline/init.lua)?

**Comment by siduck** [comment]
i'll test this here, a sec

**Comment by WernerWessely** [comment]
I am trying something similar with statusline, does not work either:
```lua
["NvChad/ui"] = {
    statusline = {
        separator_style = "round", -- default/round/block/arrow
    },
},
```
Thanks for taking a look!

**Comment by WernerWessely** [comment]
> ok both work for me, i think its an issue with your custom config

You're right, it was structured wrong. Thanks!

**Comment by JerryLiao26** [comment]
@siduck  But it's really getting weird here...
Here's my ```custom/chadrc.lua```
<img width="682" alt="image" src="https://user-images.githubusercontent.com/8209341/179539513-52f724e4-e27e-4f63-bc0f-d7eeefb808e3.png">
And here's my ```custom/override.lua```
<img width="682" alt="image" src="https://user-images.githubusercontent.com/8209341/179539705-13162179-5267-4bcd-9da8-4778a2332249.png">
As you can see, with these configurations, the statusline is working just fine but not the tabufline
<img width="928" alt="image" src="https://user-images.githubusercontent.com/8209341/179540265-2a2578a5-1ac0-4402-8bee-1d7e5e44cc9f.png">

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/179567381-9a1e996b-ddb0-407b-8d78-bc9c5be7c1d4.png)

thats cuz you disabled the tabufline here itself D:

**Comment by JerryLiao26** [comment]
Yes but what I'm trying to do is to disable tabufline and use bufferline(for the unique name feature) but tabufline is still showing up 😭

**Comment by siduck** [comment]
@JerryLiao26 the unique name feature for same file will be added to tabufline soon so wait up

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/179682450-4c73d512-9ec8-47ea-8c95-d4eb0a701ac2.mp4

disabling tabufline works here too btw

**Comment by JerryLiao26** [comment]
@siduck Thank you for your time! I think I'll wait up then. BTW your desktop setting looks great 🤩

**Comment by siduck** [comment]
> @siduck Thank you for your time! I think I'll wait up then. BTW your desktop setting looks great star_struck

https://github.com/siduck/chadwm
