### ISSUE TITLE
Hide [Close Button]

### ISSUE THREAD

**Issue by rayshabh** [NvChad/ui#103]
Hey **Siduck**, just wanted to know whether we can hide the Red **CLOSE BUTTON** that is in the Top-Right Most corner of the window? I want to keep the **THEME SWITCHER** and only want to hide/disable the **CLOSE BUTTON**.

Waiting for your response.
![2023-05-10-18:38:55-screenshot](https://github.com/NvChad/NvChad/assets/43938393/26c69a55-0131-4191-84cd-de20f1e1eb5a)

**Comment by siduck** [comment]
will help in an hour, brb

**Comment by siduck** [comment]
```lua
tabufline = {
    overriden_modules = function()
      return {
        buttons = function()
          local toggle_themeBtn = "%@TbToggle_theme@%#TbLineThemeToggleBtn#" .. vim.g.toggle_theme_icon .. "%X"
          return toggle_themeBtn
        end,
      }
    end,
  }
 ```
 
 Add this table in your M.ui field in chadrc 
 
 Docs https://nvchad.com/docs/config/nvchad_ui :)

**Comment by rayshabh** [comment]
> 

Hey bro, thanks for replying back and for the solution, but I've achieved my needs by using the same piece of config after reading your documentation properly yesterday. 

Thank you so much anyway ^_^
