### ISSUE TITLE
Cheatsheet strange behavior

### ISSUE THREAD

**Issue by BrunoKrugel** [NvChad/ui#105]
If I have more than one item in tabuffline and open cheatsheet, after closing it, all the items will be moved to the right of the screen:

https://www.loom.com/share/fc7a4855b9214fbaac52d5f66dc6cc1e

I would expect to come back to the same buffer I had open before opening cheatsheet.

**Comment by siduck** [comment]
i think its related to https://github.com/NvChad/ui/issues/94

**Comment by BrunoKrugel** [comment]
https://github.com/NvChad/ui/assets/30608179/c47c7b27-9f05-46bf-b00f-4683d4e947b7
