### ISSUE TITLE
Statusline Shows incorrectly 

### ISSUE THREAD

**Issue by lucifer-heaven** [NvChad/ui#108]
Hi, 
I'm new here. I really love the project, it makes the configuration very easy. 
During the setup. I found there's icons or glyph shows improperly.  
https://github.com/NvChad/ui/blob/1eb880208af1a14829553b3808bfde9fd48b3de4/lua/nvchad_ui/statusline/default.lua#L99
Maybe this line, might cause the problem? 

![Screen Shot 2023-05-13 at 5 27 23 PM](https://github.com/NvChad/ui/assets/10078186/44722d35-8d9c-4178-9597-874d4bfbb284)

I don't know where the status or head comes from. I tried searching the keywords in both UI and Nvchad repo. Nothing comes out. 

Other than the icon before the branch name, When I changed to a theme other than base 46, the separator shows very differently.  

Also, where does the $st_file_info# tag come from? can I overwrite the return value? https://github.com/NvChad/ui/blob/1eb880208af1a14829553b3808bfde9fd48b3de4/lua/nvchad_ui/statusline/default.lua#L101

If you can share some tips with me about the problems, there's be great appreciation. 

Thanks

**Comment by siduck** [comment]
St_file_info is just the highlight group, check it in our base46 repo's integration folder's statusline file. 

Also the icon issue is from your terminal most probably! update your fonts

**Comment by lucifer-heaven** [comment]
Oh. I got a quick reply! 
I'm using Kitty + Nerdfont. You can see the other icon in the bar shows correctly. only very a few icons goes wrong. I only find the icon problem in this particular scenario. Do you want my setup? or I can check something else to fix/ignore this icon? 

Thank you!

**Comment by siduck** [comment]
> Oh. I got a quick reply! I'm using Kitty + Nerdfont. You can see the other icon in the bar shows correctly. only very a few icons goes wrong. I only find the icon problem in this particular scenario. Do you want my setup? or I can check something else to fix/ignore this icon?
> 
> Thank you!

check nerdfix
