### ISSUE TITLE
Error when running Nvdash command with "folke/noice.nvim" plugin

### ISSUE THREAD

**Issue by ywwa** [NvChad/ui#114]
**Description:**
When "folke/noice.nvim" plugin is enabled command `NvDash` returns Error
Preview:

https://github.com/NvChad/ui/assets/56758452/6c913b78-c00a-4976-9071-fa710006432f

**Comment by mikededo** [comment]
Hm, can you provide the output of the `:messages` command? I'm not really aware on how does `noice` work, but it seems that it is changing or updating windows. Nvdash tries to be loaded in the current window, which for some reason cannot be found.

**Comment by ywwa** [comment]
there you go
```
Error executing Lua callback: .../.local/share/nvim/lazy/ui/lua/nvchad_ui/nvdash/init.lua:42: Invalid window id: 1113
stack traceback:
	[C]: in function 'nvim_win_get_buf'
	.../.local/share/nvim/lazy/ui/lua/nvchad_ui/nvdash/init.lua:42: in function 'open'
	...uukiwwa/.local/share/nvim/lazy/ui/lua/nvchad_ui/init.lua:15: in function <...uukiwwa/.local/share/nvim/lazy/ui/lua/nvchad_ui/init.lua:11>
```

**Comment by mikededo** [comment]
I can't recreate the issue. I have installed `noice` in my configuration but `Nvdash` is showing/hiding the dashboard as expected...  
Is it only when `noice` is installed? What if you load lazily?

**Comment by ywwa** [comment]
you can try with my configs what are located here https://github.com/yuukilla/nvchad-config
cause in my case error shows up only when i enable noice plugin
