### ISSUE TITLE
[PROPOSAL] Different styles for tabufline

### ISSUE THREAD

**Issue by mikededo** [NvChad/ui#116]
Hi, opening an issue as discussions are not enabled.

Lately I have been wondering if it was possible to update the look of the tabs of `tabufline`. Yesterday, using the `modules_overrides` and creating a really messy approach, I was able to find a way to style in order to have rounded borders. This is the final result:

<img width="693" alt="image" src="https://github.com/NvChad/ui/assets/48334745/6e958bcc-e6a3-4702-94d3-3c7297013fb3">

What do you think about adding this new options? I would be more that interested to work on it, though I'm quite short on time. Having already implemented it in my custom configuration would be quite easy, only that I would like to provide a good interface for users to customise the look of it.

**Comment by siduck** [comment]
hi @mikededo , looks awesome, looking forward to add it in v3.0 nvchad :)

**Comment by mikededo** [comment]
Great! Are there any guidelines on how to contribute in the ui repo?

**Comment by siduck** [comment]
> Great! Are there any guidelines on how to contribute in the ui repo?

no guidelines, but before new features I want to fix all the issues in all nvchad related repos :)

**Comment by siduck** [comment]
will close this as its not an issue, I'll notify you when I add different tabufline styles

**Comment by mikededo** [comment]
Yes, no problem. I currently don't have much time because of uni, but once I finish I would like to contribute to the repo, so if you need help in something just let me know. I'm not aware if you are tracking the bugs/issues in the NvChad in any place.

**Comment by siduck** [comment]
> Yes, no problem. I currently don't have much time because of uni, but once I finish I would like to contribute to the repo, so if you need help in something just let me know. I'm not aware if you are tracking the bugs/issues in the NvChad in any place.

im tracking it, i try to fix it before going to work or at the end of the day.  Currently need help with https://github.com/NvChad/nvterm , i didnt code it @zbirenbaum  did . Will take some time to understand the plugin
