### ISSUE TITLE
[feature request] most recently used (MRU) buffer switching

### ISSUE THREAD

**Issue by sidequestboy** [NvChad/ui#117]
It would be nice to be able to map `<C-tab>` and `<C-S-tab>` to switch buffers based on most recently used, because many other modern applications do this. 

e.g. This is the default behaviour of VSCode's Ctrl-Tab.

**Comment by siduck** [comment]
hi @sidequestboy , you're free to disable default mappings i.e tab and s-tab in normal mode and add your mappings!!
