### ISSUE TITLE
transparent status line

### ISSUE THREAD

**Issue by gfsd3v** [NvChad/ui#12]
Howdy folks :)

First I would like to thank u guys for the amazing effort and even more amazing result, been using NvChad for the last couple of months and things are being relatively easily to setup and to get up and running.

I would like to ask how could I go about changing the status line to support transparency and how can I change from showing the current buffer file name to the file path?

PS: I've checked the docs and source code but I should've missed something.

Again, thx for the awesome work :)

**Comment by siduck** [comment]
override modules https://nvchad.github.io/config/nvchad_ui

**Comment by gfsd3v** [comment]
@siduck I think for the file should be [this one,](https://github.com/NvChad/ui/blob/a7445f5c1e999894b6ba478de370f2a591ddef4b/lua/nvchad_ui/statusline/modules.lua#L47), right?

But I wasn't able to figure it out the colors, I even tried to check how the colors are changing when I change themes but without success.

**Comment by siduck** [comment]
> @siduck I think for the file name should be [this one,](https://github.com/NvChad/ui/blob/a7445f5c1e999894b6ba478de370f2a591ddef4b/lua/nvchad_ui/statusline/modules.lua#L47) right?
> 
> But I wasn't able to figure it out the colors, I even tried to check how the colors are changing when I change themes but without success.

add highlight group before the text like

```lua
"%#St_file_info#"  .. getFileName()
```

**Comment by siduck** [comment]
read the fileInfo function

**Comment by gfsd3v** [comment]
ohhhhh, got it, thanks :)

**Comment by siduck** [comment]
> ohhhhh, got it, thanks :)

yeah you can override values of a highlight group ( fg , bg, italic, underline and so on, check nvim_hl api for more info ) and add new highlight groups, change specific colors in a theme too.

https://nvchad.github.io/config/theming
