### ISSUE TITLE
Current line and column in status line 2

### ISSUE THREAD

**Issue by minocrafft** [NvChad/ui#121]
**Is your feature request related to a problem? Please describe.**
The current location cannot be put in the desired position.

**Describe the solution you'd like**
Add current line and column between icon and text in statusline.

**Additional context**
I modified my chadrc.lua file as follows, referring to NvChad/NvChad#1562 and docs.
```lua
statusline = {
    overriden_modules = function()
      local st_modules = require "nvchad_ui.statusline.default"

      return {
        cursor_position = function()
          local line = vim.fn.line "."
          local col = vim.fn.virtcol "."

          -- lets store current logs
          local cp = st_modules.cursor_position()

          return cp .. string.format("%3d:%-2d", line, col)
        end,
      }
    end,
  },
```

**Screenshot**
and got this
![statusline](https://github.com/NvChad/NvChad/assets/84756721/686d3d6b-d162-4937-96cb-29e4334c1cd1)

or this
![statusline2](https://github.com/NvChad/NvChad/assets/84756721/85e953df-392b-4e2f-b2ef-5ff176b18521)

but expected "icon" .. line : column .. "text".
like this
![statusline3](https://github.com/NvChad/NvChad/assets/84756721/899f4ad1-abfe-4b3e-b64a-236a3da79d82)

Is there a way to add a column between the existing icon and text?

Importing and fixing all statusline files in NvChad/ui is too cumbersome.

**Comment by siduck** [comment]
which icon are you even talking about? :angry:

**Comment by siduck** [comment]
you are just copying the default  cursor_position module. Either write  your own cursorposition function or just add a line icon 

![image](https://github.com/NvChad/ui/assets/59060246/e6a4a2cd-6ced-42db-a60c-b08407eb7e55)

`return cp .. "│" .. string.format("%3d:%-2d", line, col) .. " "`

> Importing and fixing all statusline files in NvChad/ui is too cumbersome.

Its not, importing is only meant to be done when you want the default module + your module, please read our docs well

**Comment by minocrafft** [comment]
Thank you for your reply, but this is not an issue about line icons.

I mean the location of text in status line.

This is what I expected.
![statusline4](https://github.com/NvChad/ui/assets/84756721/41c0e17c-b5ea-45fc-a64f-f6bdd6f63533)

How can I add it?

Is it possible to put new text between already specified text?

**Comment by siduck** [comment]
@minhub7  you have to write your own cursor position function for that

**Comment by siduck** [comment]
![image](https://github.com/NvChad/ui/assets/59060246/fec8b1a0-ec7a-4371-bc35-2462a687d6b2)

**Comment by siduck** [comment]
```lua
statusline = {
    overriden_modules = function()
      local fn = vim.fn
      local sep_l = ""

      return {

        cursor_position = function()
          local line = fn.line "."
          local col = fn.virtcol "."

          local chad = string.format(" %d:%d", line, col) .. " │ "

          -- default cursor_position module
          local left_sep = "%#St_pos_sep#" .. sep_l .. "%#St_pos_icon#" .. " "

          local current_line = fn.line "."
          local total_line = fn.line "$"
          local text = math.modf((current_line / total_line) * 100) .. tostring "%%"
          text = string.format("%4s", text)

          text = (current_line == 1 and "Top") or text
          text = (current_line == total_line and "Bot") or text

          return left_sep .. "%#St_pos_text#" .. chad .. text .. " "
        end,
      }
    end,
  }
  ```

**Comment by minocrafft** [comment]
That's cool, thank you very much.
