### ISSUE TITLE
Cheatsheet produces error when trying to open it up in nvimtree

### ISSUE THREAD

**Issue by Nukiloco** [NvChad/ui#123]
**Describe the bug**
Cheatsheet produces error when trying to open it up in nvimtree.

**To Reproduce**
1. Open nvimtree ``<leader> + e``.
2. Open cheatsheet while focused on nvimtree ``<leader> + ch``.
3. Error produces on the bottom.

**Expected behavior**
The cheat sheet should appear on the buffer screen and switch focus to it. When removing focus, it should go back to nvimtree or the buffer?

**Screenshots**
None

**Desktop (please complete the following information):**
 - Linux Mint
 - Alacritty
 - NVIM v0.9.0-dev-1093+gfb1db80f5

**Additional context**
None

**Comment by siduck** [comment]
@Nukiloco i believe this was fixed already, please update nvchad

**Comment by Nukiloco** [comment]
I have updated to the newest version though it still errors out.

**Comment by siduck** [comment]
> I have updated to the newest version though it still errors out.

please show the error!!!!

**Comment by Nukiloco** [comment]
```
Error executing Lua callback: vim/shared.lua:0: Expected table, got nil
stack traceback:
        [C]: in function 'assert'
        vim/shared.lua: in function 'tbl_values'
        ...cal/share/nvim/lazy/ui/lua/nvchad_ui/cheatsheet/grid.lua:185: in function <...cal/share/nvim/lazy/ui/lua/nvchad_ui/cheatsheet/grid.lua:27>
        ...ukiloco/.local/share/nvim/lazy/ui/lua/nvchad_ui/init.lua:31: in function <...ukiloco/.local/share/nvim/lazy/ui/lua/nvchad_ui/init.lua:27>
```
![tmux new_003](https://github.com/NvChad/ui/assets/16618467/7b629e4c-81eb-40b4-a300-fce75c2153d2)
