### ISSUE TITLE
tabufline: close all buffers to the right

### ISSUE THREAD

**Issue by martin-braun** [NvChad/ui#127]
Would be handy to being able to close all buffers (tabufline tabs) to the right. :)

**Comment by siduck** [comment]
```lua
 local current_buf = vim.api.nvim_get_current_buf()
 local current_buf_index = require("nvchad_ui.tabufline").getBufIndex(current_buf)

  for i, bufnr in ipairs(vim.t.bufs) do
    if i > current_buf_index then
      require("nvchad_ui.tabufline").close_buffer(bufnr)
    end
  end
  ```

**Comment by martin-braun** [comment]
@siduck You are fast, I made a PR with my own solution. I think it's slower to call `close_buffer`, please check my PR #128 for a much faster solution. :)

Also `close_buffer` contains `vim.cmd("confirm bd" .. bufnr)`, I think that will block.
