### ISSUE TITLE
Tabuffline breaks after session restored.

### ISSUE THREAD

**Issue by BrunoKrugel** [NvChad/ui#132]
If you use a plugin that auto restore a session like: [auto-session](https://github.com/rmagatti/auto-session) or [possession](https://github.com/gennaro-tedesco/nvim-possession), after a session is restored, the nvimtree will be bugged (using 50% of the screen and blank), the following autocmd fix the nvimtree issue, however, the tabuffline breaks.

possession config:
```
  {
    "gennaro-tedesco/nvim-possession",
    lazy = false,
    dependencies = {
      "ibhagwan/fzf-lua",
    },
    config = function()
      require("nvim-possession").setup {
        autoload = true,
      }
    end,
  },
```

autocmd:
```
autocmd({ "BufEnter" }, {
  pattern = "NvimTree*",
  callback = function()
    local api = require "nvim-tree.api"
    local view = require "nvim-tree.view"

    if not view.is_visible() then
      api.tree.open()
    end
  end,
})
```

Error when trying to format anything:

```
[null-ls] error in formatting handler: ...lar/neovim/0.9.1/share/nvim/runtime/lua/vim/lsp/util.lua:404: BufAdd Autocommands for "*": Vim(append):Error executing lua callback: .../share/nvim/lazy/ui/lua/nvchad_ui/tabufline/lazyload.lua:37: Invalid buffer id: 6
stack traceback:
    [C]: in function 'nvim_buf_get_name'
    .../share/nvim/lazy/ui/lua/nvchad_ui/tabufline/lazyload.lua:37: in function <.../share/nvim/lazy/ui/lua/nvchad_ui/tabufline/lazyload.lua:19>
    [C]: in function 'resume'
    ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:45: in function <...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:44>
```

After this error is thrown, all tabuffline related functions will not work.

Let me know if you need more info.

**Comment by BrunoKrugel** [comment]
To be able to reproduce the issue, make sure you have a session saved with possession.

Also, after the last nvdash update, the dashboard is opening in the session restored (that didnt happened before).

https://github.com/NvChad/ui/assets/30608179/3153e50e-b278-455d-b7f9-81c0ccd4625f

**Comment by siduck** [comment]
https://github.com/NvChad/ui/assets/59060246/91127b06-0f55-47b2-a560-2781d5811fa7

hmm still cant reproduce, also your  nvimtree autocmd doesnt open nvimtree on startup

**Comment by BrunoKrugel** [comment]
It is **not** supposed to open nvim tree on startup.

If you use any plugin that save sessions and you save a session with nvim tree opened, when you open again, the nvim tree will use half the screen and be blank.

This is a [known](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes#workaround-when-using-rmagattiauto-session) issue and the autocmd is supposed to fix it.

Example of the nvim tree blank:

![image](https://github.com/NvChad/ui/assets/30608179/b7c0d69c-b257-470b-a571-822c12bb43f3)

The issue here is: if you open nvim with a session restored (that has a nvim tree opened) the tabuffline will break, any action (tab and etc) will not work.

In your video, you only open a nvim, the nvim-tree is not opened and you do not perform and tabuffline related action.

**Comment by BrunoKrugel** [comment]
Also, after the last commits in nvdash, when restoring a session with nvdash setup to load on start up, it will try to use the blank space from nvim tree:

![image](https://github.com/NvChad/ui/assets/30608179/0e022ba9-d47a-40c7-8188-76f2b7df177e)

**Comment by BrunoKrugel** [comment]
In a summary:

1. If you have any session, delete it (`<leader>sd` if you have any saved).
2. Without any session, open nvim and then open `nvim-tree`.
3. Save a session with nvim tree opened (`<leader>sn`).

![image](https://github.com/NvChad/ui/assets/30608179/00bdc348-7016-4673-a40e-75fa4fd6bd87)

4. Make sure to have the plugin setup to autoload session and the autocmd to fix `nvim-tree`, then quit nvim.
5. Open nvim, the `nvim-tree` will be opened (because of the session restored), try to format any file or press `<Tab>`

![image](https://github.com/NvChad/ui/assets/30608179/d7c6cbf7-c0d9-441d-8334-e85c54c6636c)

**Comment by digitallyserviced** [comment]
@BrunoKrugel did you fix this? i have the same errors but relating to some other plugin it seems

@siduck I use lspsaga and the default copypasta setup for lazy.nvim and after I use any popup finder/code action it will then start doing this.

i've been able to monkey patch some of it away by editing tabufline lua files to check for both `vim.api.nvim_buf_is_valid` AND `nvim.api.nvim_buf_is_loaded' rather then just `is_valid`

apparently listing buffers by `:buffers` shows only valid/loaded but if you make an api call with the relevant `nvim_gimme_buf` api call then it responds with **unloaded** buffers as well in the list and they are **VALID** but **NOT LOADED**

![image](https://github.com/NvChad/ui/assets/1828125/5a78b7a2-9d28-4cec-bc5c-8961e63cc7aa)

![image](https://github.com/NvChad/ui/assets/1828125/dcff0faf-fcfe-4f43-a200-1a2167dad654)

both of the buffers that it is trying to operate on there are yes valid, but NOT loaded...

**Comment by noahbald** [comment]
I'm also having issues with this - I feel like it may be due to how the bufffers will be loaded before and after saving/loading a session.
If I open NvimTree, and then with NvimTree I open mappings.lua and plugins.lua.
```txt
-- `:ls!` before `:mksession` --
:ls!
  1 #h   "~\AppData\Local\nvim\lua\custom\mappings.lua" line 1
  3u a-  "NvimTree_1"                   line 0
  4u     "~\AppData\Local\nvim\lua\custom\configs\lspconfig.lua" line 0
  5 %a   "~\AppData\Local\nvim\lua\custom\plugins.lua" line 1
  6u a-  "CodeWindow"                   line 0
  7u     "~\AppData\Local\nvim\lua\plugins\configs\lspconfig.lua" line 0
  8u     "~\AppData\Local\nvim\lua\plugins\init.lua" line 0

-- `:ls!` after `:source` --
:ls!
  2 #    "~/AppData/Local/nvim/lua/custom/mappings.lua" line 1
  3 %a   "~/AppData/Local/nvim/lua/custom/plugins.lua" line 1
  5u a-  "NvimTree_1"                   line 0
  6u a-  "CodeWindow"                   line 0
```

If I press `<Tab>` I get a similar error to @digitallyserviced 
```txt
E5108: Error executing lua: ...Local/nvim-data/lazy/ui/lua/nvchad_ui/tabufline/init.lua:12: Invalid buffer id: 4
stack traceback:
        [C]: in function '__index'
        ...Local/nvim-data/lazy/ui/lua/nvchad_ui/tabufline/init.lua:12: in function 'bufilter'
        ...Local/nvim-data/lazy/ui/lua/nvchad_ui/tabufline/init.lua:29: in function 'tabuflineNext'
        C:\Users\noahw\AppData\Local\nvim/lua/core/mappings.lua:82: in function <C:\Users\noahw\AppData\Local\nvim/lua/core/mappings.lua:81>
```
I assume because buffer 4 is now empty - tabufline fails.
Tabufline still works, because if I press `3 <Tab>-6` then `plugins.lua` loads in the active tab window.

**Comment by digitallyserviced** [comment]
@noahbald @BrunoKrugel 

so in case you want to just monkeypatch this 

I did because waiting around and no real interest with why this occurs neccessitated me getting this working proper somewhat

this could be done sooooo much better but i was lazy and wanted it working without headaches

```diff
diff --git a/lua/nvchad_ui/tabufline/init.lua b/lua/nvchad_ui/tabufline/init.lua
index fe9ea2a..8597412 100644
--- a/lua/nvchad_ui/tabufline/init.lua
+++ b/lua/nvchad_ui/tabufline/init.lua
@@ -7,6 +7,15 @@ M.bufilter = function()
   if not bufs then
     return {}
   end
+        vim.t.bufs = vim.api.nvim_list_bufs()
+        local listed_bufs = {}
+        for _, val in ipairs(vim.t.bufs) do
+          if vim.bo[val].buflisted then
+            table.insert(listed_bufs, val)
+          end
+        end
+        vim.t.bufs = listed_bufs
+        bufs=vim.t.bufs

   for i = #bufs, 1, -1 do
     if not vim.api.nvim_buf_is_valid(bufs[i]) and vim.bo[bufs[i]].buflisted then
diff --git a/lua/nvchad_ui/tabufline/lazyload.lua b/lua/nvchad_ui/tabufline/lazyload.lua
index 0aa5e5f..5269479 100644
--- a/lua/nvchad_ui/tabufline/lazyload.lua
+++ b/lua/nvchad_ui/tabufline/lazyload.lua
@@ -30,6 +30,15 @@ vim.api.nvim_create_autocmd({ "BufAdd", "BufEnter", "tabnew" }, {
         and vim.bo[args.buf].buflisted
       then
         table.insert(bufs, args.buf)
+        vim.t.bufs = vim.api.nvim_list_bufs()
+        local listed_bufs = {}
+        for _, val in ipairs(vim.t.bufs) do
+          if vim.bo[val].buflisted then
+            table.insert(listed_bufs, val)
+          end
+        end
+        vim.t.bufs = listed_bufs
+        bufs=vim.t.bufs

         -- remove unnamed buffer which isnt current buf & modified
         for index, bufnr in ipairs(bufs) do

```

you are correct in for some reason the buffer list is being cached and the cache is assumed to be gospel but if changed outside of nvchad-ui then boof

**Comment by siduck** [comment]
@digitallyserviced @BrunoKrugel please check if this works
 
 ```diff
 +++ b/lua/nvchad_ui/tabufline/init.lua
@@ -8,17 +8,18 @@ M.bufilter = function()
     return {}
   end
 
-  for i = #bufs, 1, -1 do
-    if not vim.api.nvim_buf_is_valid(bufs[i]) and vim.bo[bufs[i]].buflisted then
+  for i, nr in ipairs(bufs) do
+    if not vim.api.nvim_buf_is_valid(nr) then
       table.remove(bufs, i)
     end
   end
 
+  vim.t.bufs = bufs
   return bufs
 end
 
 M.getBufIndex = function(bufnr)
-  for i, value in ipairs(vim.t.bufs) do
+  for i, value in ipairs(M.bufilter()) do
     if value == bufnr then
       return i
     end
     ```

**Comment by siduck** [comment]
try the `bugfix` branch and let me know if this issue's fixed
