### ISSUE TITLE
In windows with smaller width, tabuline enters the space occupied by nvimtree.

### ISSUE THREAD

**Issue by Upsurge-11** [NvChad/ui#133]
When multiple tabs are present, this bug is visible.
![image](https://github.com/NvChad/ui/assets/57493726/19dafcb5-6fef-433e-a967-c2a070aeb356)

**Comment by ywwa** [comment]
noticed that its because of buttons on right side, theyre not getting excluded
![image](https://github.com/NvChad/ui/assets/56758452/5c1dbc5e-b0ae-463a-9ffd-6207858310f7)

**Comment by siduck** [comment]
@ywwa you sure?

![image](https://github.com/NvChad/ui/assets/59060246/72981b7a-4a7f-4651-8b09-bb7ca96ccae0)
