### ISSUE TITLE
Tabufline: Relocate tabs to a specific index.

### ISSUE THREAD

**Issue by AribYadi** [NvChad/ui#134]
Is there currently any way to relocate the tabs in tabufline? I tried using :tabmove but that doesn't work.

**Comment by siduck** [comment]
@AribYadi  check the vim.t.bufs table , mess with it. I'll give you a hint!

that table contains a list of all buffer numbers in current tab. So just store the current tab's buffer number in a variable and check its index in vim.t.bufs, then you can re-arrange vim.t.bufs

**Comment by AribYadi** [comment]
Thank you @siduck! Just for people in the future who also have this question, here are the functions that I wrote for moving the tabs right and left:

Moving the current tab to the right:

```lua
function()
  local current_buf = vim.api.nvim_get_current_buf();
  local bufs = vim.t.bufs;
  local i = 0;
  for j, v in ipairs(bufs) do
    if v == current_buf then
      i = j;
    end
  end
  if i < #bufs then
    bufs[i], bufs[i+1] = bufs[i+1], current_buf;
    vim.t.bufs = bufs;
    vim.cmd "redrawtabline"
  end
end
```

Moving the current tab to the left:

```lua
function()
  local current_buf = vim.api.nvim_get_current_buf();
  local bufs = vim.t.bufs;
  local i = 0;
  for j, v in ipairs(bufs) do
    if v == current_buf then
      i = j;
    end
  end
  if i > 0 then
    bufs[i], bufs[i-1] = bufs[i-1], current_buf;
    vim.t.bufs = bufs;
    vim.cmd "redrawtabline"
  end
end
```

**Comment by siduck** [comment]
@AribYadi , btw there's a predefined function the tabufline/init.lua to get the index of buffer , check it and use it to make your code shorter :D

**Comment by AribYadi** [comment]
@siduck, I feel so dumb for not finding the `move_buf` function in [`tabufline/init.lua`](https://github.com/NvChad/ui/blob/v2.0/lua/nvchad_ui/tabufline/init.lua)! Here's the updated functions! Thank you so much by the way!

Right:

```lua
function()
  require 'nvchad_ui.tabufline'.move_buf(1);
end
```

Left:

```lua
function()
  require 'nvchad_ui.tabufline'.move_buf(-1);
end
```

**Comment by Hugobsb** [comment]
> @siduck, I feel so dumb for not finding the `move_buf` function in [`tabufline/init.lua`](https://github.com/NvChad/ui/blob/v2.0/lua/nvchad_ui/tabufline/init.lua)! Here's the updated functions! Thank you so much by the way!
> 
> Right:
> 
> ```lua
> function()
>   require 'nvchad_ui.tabufline'.move_buf(1);
> end
> ```
> 
> Left:
> 
> ```lua
> function()
>   require 'nvchad_ui.tabufline'.move_buf(-1);
> end
> ```

Updating here with the new way to import it:

Right:
```lua
function()
  require 'nvchad.tabufline'.move_buf(1);
end
```

Left:
```lua
function()
  require 'nvchad.tabufline'.move_buf(-1);
end
```

This is for anyone who [updated NvChad](https://github.com/NvChad/ui/commit/b73a34114103a3ba20e086b0129b173b1138839f) and might be expecting the following issue:

```
Error executing lua [string ":lua"]:1: module 'nvchad_ui.tabufline' not found: no field package.preload['nvchad_ui.tabufline']
```

**Comment by siduck** [comment]
@Hugobsb could send a PR in the nvchad.github.io repo :)

**Comment by Hugobsb** [comment]
> @Hugobsb could send a PR in the nvchad.github.io repo :)

Hey, @siduck :) it'd be a pleasure. Do you mean a PR to add a section or sth like that in the docs talking about what was discussed on this issue?

**Comment by siduck** [comment]
@Hugobsb nvm it, i thought we had some outdated docs regarding those tabufline functions, but we dont

**Comment by Hugobsb** [comment]
> @Hugobsb nvm it, i thought we had some outdated docs regarding those tabufline functions, but we dont

@siduck yes, I've just searched the project by `_ui` to take a look at it, that's the reason why I was in doubt 😅 then if there's something I can help with, let me know :)
