### ISSUE TITLE
vim.lsp.util.get_progress_messages is deprecated

### ISSUE THREAD

**Issue by sangshuduo** [NvChad/ui#140]
hi, when I launch nvim there is a message shows as:

vim.lsp.util.get_progress_messages is deprecated, use vim.lsp.status instead. :help deprecated
This feature will be removed in Nvim version 0.11.0

My neovim version is:

NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/usr/include/luajit-2.1 -I/usr/include -I/build/neovim-mN1Oid/neovim-0.10.0~ubuntu1+git202306112018-bde59e814-9b397864c/.deps/usr/include -I/build/neovim-mN1Oid/neovim-0.10.0~ubuntu1+git202306112018-bde59e814-9b397864c/build/src/nvim/auto -I/build/neovim-mN1Oid/neovim-0.10.0~ubuntu1+git202306112018-bde59e814-9b397864c/build/include -I/build/neovim-mN1Oid/neovim-0.10.0~ubuntu1+git202306112018-bde59e814-9b397864c/build/cmake.config -I/build/neovim-mN1Oid/neovim-0.10.0~ubuntu1+git202306112018-bde59e814-9b397864c/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

Any solution or plan? Thanks.

**Comment by sangshuduo** [comment]
\--- a/lua/nvchad\_ui/statusline/default.lua  
+++ b/lua/nvchad\_ui/statusline/default.lua  
@@ -107,7 +107,7 @@ M.LSP\_progress = function()  
    return ""  
  end

\-  local Lsp = vim.lsp.util.get\_progress\_messages()\[1\]  
\+  local Lsp = vim.lsp.status()\[1\]

problem is resolved now.

**Comment by siduck** [comment]
fixed https://github.com/NvChad/ui/pull/139
