### ISSUE TITLE
Icons are not displayed in the status bar

### ISSUE THREAD

**Issue by NorthernBlow** [NvChad/ui#142]
i cannot remove this "empty icons".  
and I don't want to roll back to a previous version of the system font

the best soiution on my sight is  add to core/default_config.lua an option like icons=false

Desktop (please complete the following information):

    Operating System: Arch Linux 6.3.5-arch1-1
    Terminal: Alacritty
    NVIM v0.9.1
    Build type: Release
    LuaJIT 2.1.0-beta3

![statusline](https://github.com/NvChad/ui/assets/39205340/3712d5c8-0dea-4086-abdd-e8cc974564bd)

**Comment by siduck** [comment]
update your fonts please

**Comment by NorthernBlow** [comment]
What fonts need? I installed Nerd Font and nothing has changed.

**Comment by siduck** [comment]
> What fonts need? I installed Nerd Font and nothing has changed.

install the latest ones and delete old fonts

**Comment by hawkinchina** [comment]
@NorthernBlow Is it ok?  I met the same problem.

**Comment by siduck** [comment]
> [@NorthernBlow](https://github.com/NorthernBlow) Is it ok? I met the same problem.

installing fonts wont work ,set them in terminal too
