### ISSUE TITLE
inlayHints not working

### ISSUE THREAD

**Issue by codeprefect** [NvChad/ui#150]
# Description

InlayHints is not showing when using NvChad UI, but it shows with some other neovim ui

Note: Tested with catppuccin through LazyVim

**Comment by siduck** [comment]
i think you need to set some config for it

**Comment by codeprefect** [comment]
Can you share a working config?

**Comment by siduck** [comment]
@codeprefect i dont know about it,  check r/neovim's one of the posts related to it. ive seen some code for it to work

**Comment by codeprefect** [comment]
Yes, I got it working with LazyVim, but it does not work when I am using NvChad,
I am not a vim expert, but maybe this [link](https://github.com/catppuccin/nvim/blob/3ffd2f511f3dc6c01258923d7170ccaf1445634b/lua/catppuccin/groups/integrations/native_lsp.lua#L88) will provide some hint

**Comment by siduck** [comment]
> Yes, I got it working with LazyVim, but it does not work when I am using NvChad, I am not a vim expert, but maybe this [link](https://github.com/catppuccin/nvim/blob/3ffd2f511f3dc6c01258923d7170ccaf1445634b/lua/catppuccin/groups/integrations/native_lsp.lua#L88) will provide some hint

that just adds highlight groups for inlay hints, also probably lazyvim sets inlay hints by default :thinking:

**Comment by siduck** [comment]
ok it works for me @codeprefect 

![image](https://github.com/NvChad/ui/assets/59060246/5936b808-4fc9-4492-b725-b815663a5837)

you need to enable it in your LSP server as well

**Comment by codeprefect** [comment]
Just confimed it working with Rust, I don't know what is missing in my JS/TS lspconfig that is not making it work.

**Comment by siduck** [comment]
> Just confimed it working with Rust, I don't know what is missing in my JS/TS lspconfig that is not making it work.

there's an option for tsserver

**Comment by siduck** [comment]
i use typescript-tools plugin for tsserver, remove tsserver from your custom lspconfig and add my typescript-tools setup

```lua
{
    "neovim/nvim-lspconfig",
    dependencies = {
      {
        -- format & linting
        "jose-elias-alvarez/null-ls.nvim",
        config = function()
          require "custom.configs.null-ls"
        end,
      },

      {
        "pmizio/typescript-tools.nvim",
        config = function()
          local on_attach = require("plugins.configs.lspconfig").on_attach

          require("typescript-tools").setup {
            on_attach = on_attach,

            settings = {
                    tsserver_file_preferences = {
                        includeInlayParameterNameHints = "all",   -- THIS
                  }
             },
          }
        end,
      },
    },

    config = function()
      require "plugins.configs.lspconfig"
      require "custom.configs.lspconfig"
    end,
  }
  ```
