### ISSUE TITLE
Cheatsheet menu breaking after performing vertical split of window

### ISSUE THREAD

**Issue by pc215** [NvChad/ui#154]
Description
Cheatsheet is not being produced with the file-tree open after splitting the program using :vsp

**To Reproduce**
1. Open a file using nvim
2. Open the file-tree using Ctrl+n
3. Split the program using the :vsp command
4.  Open the cheatsheet using <Leader> + ch
5. Greeted with an assertion error.

**Expected behavior**
Should show the cheatsheet in the split window.

**Desktop (please complete the following information):**
 - Operating System : WSL2 Ubuntu 20.04.6
 - Terminal: Windows Terminal
 - Version of Neovim: NVIM v0.9.1

**Additional context**
This is the error:
Error executing Lua callback: vim/shared.lua:0: Expected table, got nil
stack traceback:
        [C]: in function 'assert'
        vim/shared.lua: in function 'tbl_values'
        ...cal/share/nvim/lazy/ui/lua/nvchad_ui/cheatsheet/grid.lua:197: in function <...cal/share/nvim/lazy/ui/lua/nvch
ad_ui/cheatsheet/grid.lua:35>
        ...e/pc215/.local/share/nvim/lazy/ui/lua/nvchad_ui/init.lua:33: in function <...e/pc215/.local/share/nvim/lazy/u
i/lua/nvchad_ui/init.lua:29>

**Comment by siduck** [comment]
why do you even run vsp in nvimtree?

nvcheatsheet runs on buffers that are modificable, running vsp on nvimtree will just duplicate nvimtree itself.

So please if you want to split the file via nvimtree, try ctrl + x / v

**Comment by pc215** [comment]
I'm not using vsp in nvimtree.. that's just opened separately. I'm using vsp in the actual buffer, and then opening the cheatsheet from there

**Comment by siduck** [comment]
@pc215 make a video so I could reproduce

i tried your steps, this is what i get

![image](https://github.com/NvChad/ui/assets/59060246/42cade49-f1c4-47fd-8cff-f08c6175d9aa)


i hope you have nvchad upto date and all nvim plugins too

**Comment by pc215** [comment]
Yes, I have everything up to date and have checked for all plugins. I have also run NvChadUpdate.
I am attaching a video to show how to reproduce it.

https://github.com/NvChad/ui/assets/113053305/5e8f0360-170a-4de3-99f4-c377ab9a3c95

**Comment by siduck** [comment]
https://github.com/NvChad/ui/assets/59060246/73a24b9c-e516-46dd-9450-a4424bd91dda


 
i'm pretty sure you forgot to add description for your custom mappings or it has some syntax errors
