### ISSUE TITLE
Wrong behaviour when nvimtree is on the Right

### ISSUE THREAD

**Issue by KorigamiK** [NvChad/ui#161]
Tabufline has space on the left even when nvimtree is on the right

I don't have any special config for tabufline. Also can you tell me how to get rid of the close and toggle theme button on the top right?

https://github.com/NvChad/ui/assets/72932688/d309b9a1-7687-41cc-9ae9-fc971c133611

**Comment by BrunoKrugel** [comment]
to get rid of close button, you have to [override](https://nvchad.com/docs/config/nvchad_ui) the tabuffline config

**Comment by BrunoKrugel** [comment]
Regarding the missing space, it is not wrong, you are missing some config
https://github.com/NvChad/ui/issues/68

**Comment by siduck** [comment]
@BrunoKrugel you need to override tabufline modules now!

**Comment by siduck** [comment]
```lua

M.ui = {
  tabufline = {
    overriden_modules = function(modules)
       table.remove(modules, 4) -- removes buttons module cuz its at index 4
      table.insert(modules, modules[1]) -- adds nvimtree module ( its at index 1 ) , to end of the table
      table.remove(modules, 1) -- removes nvimtree module at index 1
    end,
  },
}
```
 pls read nvchad  docs well!

**Comment by KorigamiK** [comment]
> 

Does this fix the nvim tree issue or the close and toggle buttons?

**Comment by KorigamiK** [comment]
> ```lua
> M.ui = {
>   tabufline = {
>     overriden_modules = function(modules)
>       table.insert(modules, modules[1])
>       table.remove(modules, 1)
>     end,
>   },
> }
> ```
> 
> pls read nvchad docs well!

Does this fix the nvim tree issue or the close and toggle buttons?

**Comment by siduck** [comment]
@KorigamiK both

**Comment by KorigamiK** [comment]
> @KorigamiK both

Just a slight change, I modified it to this and it works now

```lua
  tabufline = {
    overriden_modules = function(modules)
      table.remove(modules, 1)
      table.remove(modules, 3)
    end,
  },
```

**Comment by siduck** [comment]
> > @KorigamiK both
> 
> Just a slight change, I modified it to this and it works now
> 
> ```lua
>   tabufline = {
>     overriden_modules = function(modules)
>       table.remove(modules, 1)
>       table.remove(modules, 3)
>     end,
>   },
> ```

yep that will not add nvimtree offset on the right

**Comment by anakinsonone** [comment]
for anyone reading this in 2025, this should work:
```lua
M.ui = {
  tabufline = {
    order = { "buffers", "tabs", "btns", "treeOffset" } -- Moved 'treeOffset' to the end
  },
}
```
