### ISSUE TITLE
status line modules override

### ISSUE THREAD

**Issue by BrunoKrugel** [NvChad/ui#163]
In the new statusline version, there is a strange behavior with the modules index/order.

Using the example from the docs, I was testing index by index to find the lsp index and I found it in the index `12`.

```
      modules[12] = (function()
        return "MODE!"
      end)()
```
This is the logic for the LSP_Status module, so if I override the index 12, I expect to have the same behavior of the original statusline.

```
modules[12] = (function()
  if rawget(vim, "lsp") then
    for _, client in ipairs(vim.lsp.get_active_clients()) do
      if client.attached_buffers[vim.api.nvim_get_current_buf()] and client.name ~= "null-ls" then
        return (vim.o.columns > 100 and "%#St_LspStatus# 󰄭  " .. client.name .. "  ") or " 󰄭  LSP  "
      end
    end
  end
end)()
```
However, when there is no LSP attached, the statusline is missing some modules:

<img width="369" alt="image" src="https://github.com/NvChad/ui/assets/30608179/07273b97-cbdc-4e8a-a892-375d40523992">

I am using `vscode_colored` theme, didnt test with other themes.

**Comment by siduck** [comment]
should be fixed, just return empty string after if condition
