### ISSUE TITLE
nvdash load_on_startup = true throws error

### ISSUE THREAD

**Issue by danwetherald** [NvChad/ui#164]
**Describe the bug**
When setting nvdash load_on_startup = true we receive this error:

```
Error executing vim.schedule lua callback: .../.local/share/nvim/lazy/ui/lua/nvchad_ui/init.lua:22: attempt to get
 length of field 'bufs' (a nil value)
stack traceback:
        .../.local/share/nvim/lazy/ui/lua/nvchad_ui/init.lua:22: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

When manually opening the nvdash with the command there is no issues or errors.

**Expected behavior**
The dashboard to show without any errors

**Comment by georgejean** [comment]
Have you put something like this in `lua/custom/chadrc.lua`? It should work.
```lua
M.ui = {nvdash = { load_on_startup = true } }
```

**Comment by danwetherald** [comment]
Huh?

The error is very much caused by me seeing that to true in my config. When setting nvdash load_on_startup = true we receive this error.

**Comment by georgejean** [comment]
Which line of code do you use ? In which file ?
![image](https://github.com/NvChad/NvChad/assets/11246966/af3165d7-666f-4be4-96da-2260391ac6cb)

**Comment by danwetherald** [comment]
I think you are misunderstanding the issue completely. I have configured the load_on_startup = true.

When I add this configuration, this is what causes the error when opening vim.

```
nvdash = {
  load_on_startup = true,
}
```

**Comment by georgejean** [comment]
Sorry, I can't reproduce it. Maybe you could provide more details about the context like described [here](https://github.com/NvChad/NvChad/blob/0e27cb4b44fbba69f8646d1f88555737d2b6aedf/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by siduck** [comment]
share your chadrc

**Comment by siduck** [comment]
https://github.com/NvChad/ui/assets/59060246/18232444-063a-480c-b28d-cd1de1e9c1f4

unable to reproduce at all, please make sure you ran NvChadUpdate

**Comment by danwetherald** [comment]
Found the issue:

```
tabufline = {
    enabled = false,
},

nvdash = {
    load_on_startup = true,
}
```

It seems the issue is caused when tabufline is not enabled

**Comment by siduck** [comment]
ok i get the error now, nvdash is dependent on tabufline partially . one thing you can do is remove the nvdash option from chadrc and add this code in your custom/init.lua

```lua
vim.defer_fn(function()
  -- load nvdash on startup
  -- only if nvim was opened without a file
  if #vim.fn.argv() == 0 then
    require("nvchad_ui.nvdash").open()
  end

  local new_cmd = vim.api.nvim_create_user_command

  -- Command to toggle NvDash
  new_cmd("Nvdash", function()
    if vim.g.nvdash_displayed then
      vim.cmd "bd"
    else
      require("nvchad_ui.nvdash").open()
    end
  end, {})
end, 0)
```

**Comment by danwetherald** [comment]
Is this seen as a temporary work around? Should the Nvdash plugin not be dependent on a plugin being disabled?

**Comment by siduck** [comment]
> Is this seen as a temporary work around? Should the Nvdash plugin not be dependent on a plugin being disabled?

not a temporary workaround, nvdash is  a part of our UI plugin, tabufline is also part  of our UI plugin, it executes some code based on a variable from tabufline on certain conditions.

the code I gave you is the same code that loads nvdash in nvchad, but without the tabufline dependent code*

**Comment by danwetherald** [comment]
Gotcha, Is it not possible to conditionaly run the tabifline code if enabled?

**Comment by siduck** [comment]
> Gotcha, Is it not possible to conditionaly run the tabifline code if enabled?

done
