### ISSUE TITLE
Request: make tabufline standalone plugin

### ISSUE THREAD

**Issue by ryanmsnyder** [NvChad/ui#166]
NvChad's tabufline is the best buffer/tab manager I've used. Would love to see it as a standalone plugin that can be installed via packer/lazy.

**Comment by siduck** [comment]
@ryanmsnyder sorry to disappoint but i dont have any plans for doing it. Also you can still use it technically, just need to make a module ` require("core.utils").load_config()` that returns a table which has structure to that of nvchad's default_config.lua
