### ISSUE TITLE
Space Is appended to symbol name in renamer

### ISSUE THREAD

**Issue by strau0106** [NvChad/ui#167]
When opening the renamer, there is a space added to the symbol name. When that space isn't removed manually, it causes undefined behaviour.

The following line suggests this is intentional:
https://github.com/NvChad/ui/blob/1d4267f47fc022c66af87261f49c32b9a05273cf/lua/nvchad_ui/renamer.lua#L7
could someone explain me why this is done?

**Comment by siduck** [comment]
@strau0106 without it the cursor would be before the last letter which is ODD

![image](https://github.com/NvChad/ui/assets/59060246/11b0d0af-dc7f-4c4a-9d03-30cb8edf66d9)

**Comment by strau0106** [comment]
ok yeah. it was nvim-cmp interfering causing the weird behaviour, so this issue can close
