### ISSUE TITLE
nvchad_ui.icons not found

### ISSUE THREAD

**Issue by ikkihou** [NvChad/ui#168]
hi there, I just updated the nvchad UI plugin and got the error below, which I naturally believe is a bug.
could you plz help me with that, thx very much!!

![71691571287_ pic](https://github.com/NvChad/ui/assets/51254965/fde7856f-2cf0-4449-86ba-b9c390cee4d4)

**Comment by siduck** [comment]
please update nvchad

this should be your latest commit https://github.com/NvChad/ui/commit/7be4e1bc4f46bffc54cd1383ad2d1a957ca95bf1
