### ISSUE TITLE
Unexpected close when move between tab

### ISSUE THREAD

**Issue by bachrilq** [NvChad/ui#170]
**Describe the bug**
So I'm using plugin `https://github.com/mbbill/undotree/tree/master` to visualize undo, and when I open that plugin, and then close the plugin again, I try to move between tabs, and after that nvim suddenly close.

**To Reproduce**
1. run nvim
2. open nvimtree
3. open two files (and it will open 2 new tab)
4. open undotree
5. close undotree
6. close nvimtree
7. try to move between tab
8. nvim suddenly close

**Expected behavior**
nvim not unexpected close

**Screenrecord**
https://github.com/NvChad/NvChad/assets/40727644/c729b09d-bee2-4e8d-9794-39049694bb6f

**Desktop (please complete the following information):**
 - Operating System : macos Ventura 13.4
 - Terminal: iTerm2 Build 3.4.19
 - Version of Neovim: v0.9.1
 - nvchad : commit 46a61073a82087f9e339dab6de2b2

**Additional context**
and sometimes when the issue happens, I got an error log like this 
```
E5108: Error executing lua: vim/_editor.lua:0: nvim_exec2()..BufEnter Autocommands for "<buffer=8>": Vim(if):E121: Undefined variable: t:undotree
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        .../.local/share/nvim/lazy/ui/lua/nvchad/tabufline/init.lua:38: in function 'tabuflineNext'
        /Users/bachril.qirom/.config/nvim/lua/core/mappings.lua:82: in function </Users/bachril.qirom/.config/nvim/lua/core/mappings.lua:81>
```

**Comment by siduck** [comment]
https://github.com/NvChad/ui/assets/59060246/7c321ff6-a267-492b-b00d-f07f0563e82c

nvimtree here doesnt close but expands to max width

**Comment by bachrilq** [comment]
Can you try to close the nvimtree? and switch between tabs?, because in my side the nvim will close after closing the nvimtree and try to switch between tab. Also, I try only open 1 file, open undotree, and after pressing tab, nvim will close unexpectedly.

https://github.com/NvChad/ui/assets/40727644/d311510c-3290-4b42-98f1-ef0167e4d065

**Comment by siduck** [comment]
ugh man, we always get issues with sidebars :/

**Comment by bachrilq** [comment]
I see, is that expected?, and is there any I can do about that?

**Comment by siduck** [comment]
> I see, is that expected?, and is there any I can do about that?

no idea, i'll have check!

**Comment by siduck** [comment]
but first i have to understand the problem properly, i cant reproduce your issue from last issue too.

**Comment by siduck** [comment]
do you face this issue if you make nvimtree on right? edit nvimtree config temporarily

**Comment by bachrilq** [comment]
Are you already checked my latest record on this comment https://github.com/NvChad/ui/issues/170#issuecomment-1672484747 ?, It seems the issue does not from nvimtree, because the issue is also happening when I'm not opening the nvimtree, but I think the issue is from the tabuffline instead cmiiw.

**Comment by BrunoKrugel** [comment]
can you share your config? if I am not mistaken, nvimtree has some config to close nvim if nvimtree is the last buffer remaining

**Comment by bachrilq** [comment]
Hi @BrunoKrugel, thank you for your answer, Actually, I didn't make any changes on the configuration nvimtree, so all the configuration nvimtree are still the default. and here is my custom config for nvchad https://github.com/bachrilq/nvchad-custom. Also please take a look at this screen capture https://github.com/NvChad/ui/issues/170#issuecomment-1672484747, because I think the issue is not from nvimtree, Thank you

**Comment by BrunoKrugel** [comment]
I was only able to reproduce the issue with the undotree, I recommend to create a issue at the plugin repo

**Comment by BrunoKrugel** [comment]
Yep, their issue:

I executed my nvim with logs and these were the last ones:

```
Executing BufLeave Autocommands for "*"
autocommand call s:Remove_Matches()

Executing BufEnter Autocommands for "*"
autocommand <Lua 97: ~/.local/share/nvim/lazy/ui/lua/nvchad/tabufline/lazyload.lua:19>

Executing BufEnter Autocommands for "<buffer=4>"
autocommand call s:exitIfLast()
```

I took a look at their code and I found the autocmd

https://github.com/mbbill/undotree/blob/0e11ba7325efbbb3f3bebe06213afa3e7ec75131/autoload/undotree.vim#L347

**Comment by siduck** [comment]
ok so not a nvchad issue. try other plugins https://github.com/debugloop/telescope-undo.nvim

**Comment by bachrilq** [comment]
Thank you @BrunoKrugel for your help! and Thank you @siduck for your suggestion for another plugin! Really Appreciated. 👍
