### ISSUE TITLE
Nvdash does not load on startup

### ISSUE THREAD

**Issue by bravo1003** [NvChad/ui#171]
Hi siduck
First of all I would like to thank you for your great work on Nvchad.
It is such a joy to be editing code using your config!

Describe the bug
The setting for nvdash "load_on_startup" doesn't seem to work.

To Reproduce
1 .Set the following in chadrc.lua
```
  nvdash = {
    load_on_startup = true,
 }
```
2.  start nvim

Expected behavior
Nvdash should load on start up

Screenrecord
https://github.com/NvChad/ui/assets/5191595/dbacfd48-2fe1-4ffd-9577-ffa1a388b924

Desktop (please complete the following information):

    Operating System : macos Ventura 13.5
    Terminal: Alacritty 0.12.2
    Version of Neovim: v0.9.1
    nvchad : commit d3d9aa251a9dd94881cdbc48c5852b3eaba969b8

Additional context
The offending code seems to be here
```
if config.nvdash.load_on_startup then
  vim.defer_fn(function()
    local bufs = vim.api.nvim_list_bufs()

    if #vim.fn.argv() == 0 and (#bufs == 1 and bufs[1] == 1) then
      require("nvchad.nvdash").open()
    end
  end, 0)
end
```

Where if I remove "(#bufs == 1 and bufs[1] == 1)" in the condition, nvdash starts up just fine.

**Comment by siduck** [comment]
https://github.com/NvChad/ui/assets/59060246/14774e8e-5ba8-47d2-afd0-239a27d6189e

works fine, unable to reproduce. please make a video

**Comment by bravo1003** [comment]
I did have a video in the screen record section.
Weird, let me do a clean install and get back to you

Edit: Nvmind, It was due to some weird issue with nvim-cmp overrides opts
I fix it myself. Tks!
