### ISSUE TITLE
How to enable statusline in nvchad to move along with the selected window/active window in case of split screen ? 

### ISSUE THREAD

**Issue by Pratham16112002** [NvChad/ui#173]

**Comment by siduck** [comment]
you mean statusline per window?

**Comment by Pratham16112002** [comment]
> you mean statusline per window?

Yes

**Comment by siduck** [comment]
vim.opt.laststatus=2 , in custom init.lua.

but nvchad's statusline is designed for global statusline so check one of the closed issues regarding showing filename properly when there are multiple statuslines
