### ISSUE TITLE
Colored ASCII/ANSI Art In Nvdash

### ISSUE THREAD

**Issue by orhnk** [NvChad/ui#175]
> **Note**: I couldn't make colored text work with Nvdash.

[Here](https://0x0.st/HLJi.csv) is a minimal splash ascii example to show it fails.

With this feature It is possible to create wonderful splash screens like so:

![image](https://github.com/NvChad/ui/assets/101834410/d93ffe19-a792-4eaf-8b6f-8e8023ed3890)

<details><summary><b>Click for DOOM only visualization</b></summary>

![image](https://github.com/NvChad/ui/assets/101834410/02f37f81-222c-4d94-8833-5778b1ac4213)
</details>

-> [ASCII Source Code](https://0x0.st/HL42.txt)   <-
-> [Neovim Source Code](https://github.com/EngineersBox/dotfiles/tree/main/nvim) <-

**Comment by siduck** [comment]
no future plans for this! i personally find this feature useless
