### ISSUE TITLE
close_buffer() doesn't work as expected

### ISSUE THREAD

**Issue by MKrbm** [NvChad/ui#179]
I'm not sure if this is in the specifications but when I close a file in a tab, the file will be closed also in the other tab. 

Also, there maybe a problem related to this issue.

Let's say we have two tabs with the following buffers

- tab1 
   -  a.lua
   - b.lua
- tab2 
    - b.lua
    - c.lua
    - so on

and If I close b.lua with close_buffer() command in the second tab, then it will close all files open in second tab as well as b.lua in first tab. Therefore as a result it will be like

- tab1
   - a.lua

==========

Thank you

**Comment by MKrbm** [comment]
Is there any update with this?

**Comment by siduck** [comment]
@MKrbm will look into it this weekend insha'Allah

**Comment by MKrbm** [comment]
Thank you!

**Comment by siduck** [comment]
I was able to reproduce this, good bug!

**Comment by siduck** [comment]
seems like this occurs only when  you're trying to close a buffer which is opened in multiple tabs

**Comment by siduck** [comment]
@MKrbm i am able to reproduce this without nvchad i.e on nvim --clean :fearful:

**Comment by siduck** [comment]
@MKrbm  read https://www.reddit.com/r/neovim/comments/16wvqsb/comment/k2za6ms/?context=3

so basically your tab 1 has a.lua and tab2 has a.lua too, then tab 1 must at least have 2 or more windows

**Comment by MKrbm** [comment]
I understood, so this is a behaviour of nvim. 

Is there a way to close a file only within tabufline?  If not I might issue a feature request! 

Thank you very much.

**Comment by siduck** [comment]
> I understood, so this is a behaviour of nvim.
> 
> Is there a way to close a file only within tabufline? If not I might issue a feature request!
> 
> Thank you very much.

its not easy. If  you're closing a buffer which is an active window in other tabpages, then we'd have to make switch to another buffer before closing that one

**Comment by lucario387** [comment]
> its not easy. If you're closing a buffer which is an active window in other tabpages, then we'd have to make switch to another buffer before closing that one

You can close by setting the current buf to some other bufs + removing the index from the `vim.t.bufs` array instead of deleting it

**Comment by siduck** [comment]
@lucario387  hmm ok so check this scenario 

tab 1 :  abc.lua xyz.lua  ( abc.lua is active buf) 

tab 2 : somefile abc.lua 

now close abc.lua in tab2 , but its the active window in tab 1 and tab1 has only 1 window so it will break apart :/ 

maybe `1gt` + setting another buf as current or `enew` would work but i that will look messy cuz you'll see nvim automatically changing tabs in front of your eyes which is scary :skull:

**Comment by lucario387** [comment]
> now close abc.lua in tab2 , but its the active window in tab 1 and tab1 has only 1 window so it will break apart :/

You just don't close it, `enew` or `tabclose` if tab2 only have 1 buf, or `nvim_set_current_buf(prev/next_buf)` for tab2, then simultaneously removing abc from `vim.t.bufs` of tab2

**Comment by siduck** [comment]
> > now close abc.lua in tab2 , but its the active window in tab 1 and tab1 has only 1 window so it will break apart :/
> 
> You just don't close it, `enew` or `tabclose` if tab2 only have 1 buf, or `nvim_set_current_buf(prev/next_buf)` for tab2, then simultaneously removing abc from `vim.t.bufs` of tab2

hmm thats a hacky workaround!! many would have zombie buffers xD
