### ISSUE TITLE
Problems with <Tab> and tabuflineNext 

### ISSUE THREAD

**Issue by Franz1241** [NvChad/ui#182]
**Describe the bug**
When openning 2 tabs and pressing Tab key it throws this error:
```
E5108: Error executing lua: .../.local/share/nvim/lazy/ui/lua/nvchad/tabufline/init.lua:34: attempt to concatenate a nil value
stack traceback:
        .../.local/share/nvim/lazy/ui/lua/nvchad/tabufline/init.lua:34: in function 'tabuflineNext'
        /home/franz1241/.config/nvim/lua/core/mappings.lua:82: in function </home/franz1241/.config/nvim/lua/core/mappings.lua:81>
        
```
The only changes made in the original download where in the custom folder, specifically this one in the /home/franz1241/.config/nvim/lua/custom/plugins.lua file
```
...
-- Install a plugin
  {
    "max397574/better-escape.nvim",
    event = "InsertEnter",
    config = function()
      require("better_escape").setup()
    end,
  },
+  {
+   "github/copilot.vim"
+    , lazy = false
+    , config = function()
+                vim.cmd('imap <silent><script><expr> <F1> copilot#Accept("")')
+                vim.cmd('imap <silent><script><expr> <F2> copilot#Next()')
+                vim.cmd('imap <silent><script><expr> <F3> copilot#Previous()')
+                vim.cmd("let g:copilot_no_tab_map = v:true")
+    end,
+  },

}
```
Copilot works normally

**To Reproduce**
1. Fresh Install NVChad
2. Add Github Copilot to the custom plugins lua file 
3. Open a folder
4. leader + f + f to any file
5. leader + f + f to other file
6. <Tab> switches between tabs
7. <C w v> to split
8. <Tab> stills switches between tabs
9. <C w T> to break into a new tab
10. <Tab> to swith between "TABS"
11. See error

**Expected behavior**
Change "TABS"

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/72873924/437e6aaf-ad2b-4a6a-907b-2d5d516607a6)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye) on Windows 10 x86_64 (WSL2)
 - Terminal: Relay(7741)
 - Version of Neovim:
❯ nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

**Additional context**
I added Github Copilot and explained the change in the description

**Comment by siduck** [comment]
https://github.com/NvChad/ui/assets/59060246/57e11e33-5c5a-461a-b548-5c946f2c9a2f

unable to reproduce

**Comment by remino** [comment]
Oddly enough, I have the same issue.

1. Opened nvim.
2. `C-w s` to split default new empty buffer in two windows.
3. `C-w T` to break new window into new tab.
4. `Tab` to switch between tabs fails with the following error:

```
E5108: Error executing lua: .../.local/share/nvim/lazy/ui/lua/nvchad/tabufline/init.lua:34: attempt to concatenate a nil value
stack traceback:
        .../.local/share/nvim/lazy/ui/lua/nvchad/tabufline/init.lua:34: in function 'tabuflineNext'
        /Users/[redacted]/.config/nvim/lua/core/mappings.lua:84: in function </Users/[redacted]/.config/nvim/lua/core/mappings.lu
a:83>
```

## System Details

```
macOS Ventura 13.6
NVIM v0.9.4
NvChad 2.0 Commit ID 9d37797e6f9856ef25cfa266cff43f764e828827
ui Commit ID e61df0bf5978bebedf20c964b194de60b69c7a80
```

**Comment by siduck** [comment]
@remino tabs you see on the tabufline work differently than vim tabs

tabufline stores buffers opened per tabs i.e 

if you opened `abc, xyz` files, then these will be stored in tab 1 by default, in `vim.t.bufs`
and the vim.t* is a tab local variable, so different for all tabs

so technically `vim.t[1].bufs` = tab 1 and `vim.t[2].bufs` = tab 2, and so on

so if you want to open a file in new tab, then

1) either go to that tab and open that file via telescope/nvimtree etc 

2) Or make a new mapping that'd just do this 

-> store buffer n.o of active window in a var
-> then do tabnew 
-> then append the buffer n.o in the vim.t* variable ( table )

**Comment by lucario387** [comment]
Still an issue. Just because one move a window with a buffer to a different tab, it shouldn't mean breaking while moving between tabs
