### ISSUE TITLE
Terminal not closing completely with C-d in branch v3.0

### ISSUE THREAD

**Issue by yoplat** [NvChad/ui#187]
With the new implementation of the terminal in ui v3.0, closing the terminal with <C-d> leaves it open with [process exited 0], it would be useful to close it automatically thereafter.
I tried mapping <C-d> to also close the buffer with tabufline but it still appears in the hidden terminal pickers until I manually reopen it and press Enter or q.
Moreover the <leader>h and <leader>v keybinds for new terminal seem to be broken for me, the first time a terminal is opened with the keybind it seems to be working just fine, but the second one that you open doesn't respect the size settings set in the chadrc file and neither the size set in the mapping.lua file, pretty strange.

**Comment by siduck** [comment]
@carlobonandriniunimi  thats normal neovim behaviour. run :term command and then press C-d in it, it'll do the same. instead use Esc to close the term window

**Comment by yoplat** [comment]
> @carlobonandriniunimi thats normal neovim behaviour. run :term command and then press C-d in it, it'll do the same. instead use Esc to close the term window

Yeah but using Esc doesn't actually close the term, it just hides it. Moreover what about the issue of the term sizes with <leader>h/v?

**Comment by siduck** [comment]
what term sizes? they are initially resized according to the config, after that they are autoresized based on space available

**Comment by siduck** [comment]
just bd! the terminal if  you want to kill it, make a mapping for it

**Comment by yoplat** [comment]
> what term sizes? they are initially resized according to the config, after that they are autoresized based on space available

Maybe that's why, I was saying that after the first terminal is opened and closed, the second one is created bigger (only with the <leader>v/h, with toggle even if you close the first one, the second is still the same size)


> just bd! the terminal if you want to kill it, make a mapping for it

Thanks I got it working with this:
["<C-d>"] = { "<C-\\><C-n><cmd>bd!<CR>", "Close terminal" },

**Comment by yoplat** [comment]
Is there a way to auto-insert when focusing on the terminal? nvterm had the option but I don't know how to implement it my self. Maybe an autocommand?

**Comment by siduck** [comment]
> Is there a way to auto-insert when focusing on the terminal? nvterm had the option but I don't know how to implement it my self. Maybe an autocommand?

do lazy sync https://github.com/NvChad/ui/commit/6306e5330af6e4ccadd4c7feb42578da8cb50d23

Also use v3.0 at your own risk. None of it is documented!

**Comment by yoplat** [comment]
> > Is there a way to auto-insert when focusing on the terminal? nvterm had the option but I don't know how to implement it my self. Maybe an autocommand?
> 
> do lazy sync [6306e53](https://github.com/NvChad/ui/commit/6306e5330af6e4ccadd4c7feb42578da8cb50d23)
> 
> Also use v3.0 at your own risk. None of it is documented!

That fixed it thanks
