### ISSUE TITLE
Opening more than two tabs causes tabs hiding

### ISSUE THREAD

**Issue by nuid32** [NvChad/ui#19]
If i open third tab, the first tab is hiding, and i can't reach it via <TAB>. If i use gt to switch tab, i can reach it, but then other tabs are getting hiden.

**Comment by siduck** [comment]
@Ziaft unable to reproduce this issue :/

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/190861768-c63da460-48e7-4be1-9f29-7e8024aaa027.mp4

**Comment by Ziaft** [comment]
@siduck hm, what if i give you my files? A dubious idea, but maybe will work..?

**Comment by siduck** [comment]
@Ziaft first try to reproduce this issue with vanilla nvchad ( no custom config at all )

**Comment by Ziaft** [comment]
Only thing i changed is alpha banner and theme, i didn't make custom config yet

**Comment by siduck** [comment]
hmm i cant seem to reproduce your bug :c
