### ISSUE TITLE
feat request: Custom statusline theme request

### ISSUE THREAD

**Issue by ywwa** [NvChad/ui#194]
similarly to custom ui theme handling, allow to writing custom statusline themes

#### Details
I want to write own statusline theme from scratch without using `statusline.overriden_modules` in `chadrc.lua` but just creating my own statusline theme and use it in `statusline.theme` field to keep `chardrc.lua` file as clean as possible

#### Example
statusline theme storing can be similar to ui themes by creating folder `statusline` in `lua/custom` directory and inside it file `<statusline_theme_name>.lua` which should require minimum content of following code
```lua
local config = require("core.utils").load_config().ui.statusline

local M = {}

M.run = function()
  local modules = {}

  if config.overriden_modules then
    config.overriden_modules(modules)
  end

  return table.concat(modules)
end
```
this code could be bare minimum for successful statusline initialization
*_optionally can remove `config.overriden_modules` to keep it as simple as possible, but then `overriden_modules` field in `chadrc` wont be usable_

**Comment by siduck** [comment]
```lua
vim.opt.statusline = "%!v:lua.require('custom.statusline').run()"
```

and custom.statusline file must have the run function , the run function must return a concaneted string which is combined from many other modules in same file
