### ISSUE TITLE
Strange cursor behaviour on NvDash

### ISSUE THREAD

**Issue by yoplat** [NvChad/ui#196]
Cursor not staying in the correct column:

https://github.com/NvChad/ui/assets/98645146/6b672b64-9df9-4bd3-a3fb-74445326956c

**Comment by CleoMenezesJr** [comment]
A similar behavior happens here.
[Screencast from 2023-10-24 22-18-45.webm](https://github.com/NvChad/ui/assets/54215258/de884763-ecbb-43ca-a904-c500cffd6631)

**Comment by siduck** [comment]
this is not a nvchad issue, the icon sizes are different so the   cursor moves differently, replace 2,3 icons with 1st one, from core/default_config.lua's nvdash buttons table and the issue will be gone.

I'll look for better icons in v3.0
