### ISSUE TITLE
statusline error in root `/` directory

### ISSUE THREAD

**Issue by Andrew15-5** [NvChad/ui#197]
**Describe the bug**
I tried opening a file buffer in `/` dir, but no matter what it still throws an error.

**To Reproduce**
```sh
cd /
nvim file
# See the error:                                                       
```

```
^I...cal/share/nvim/lazy/ui/lua/nvchad/sta...y/ui/lua/nvchad/statusline/default.lua:199>            
E15: Invalid expression: v:lua.require('nvchad.statusline.default').run()                           
Press ENTER or type command to continue                                                             
```

**Expected behavior**
No error.

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/37143421/a5d65495-6997-4abb-9440-e89591f18453)

**Desktop (please complete the following information):**
 - Operating System: Pop!_OS
 - Terminal: kitty
 - Version of Neovim: v0.9.2

**Additional context**
_none_

**Comment by siduck** [comment]
make sure UI plugin is uptodate https://github.com/NvChad/ui/commits/v2.0

**Comment by Andrew15-5** [comment]
How can I update UI plugin if NvChad is tracking NvChad repository?

**Comment by siduck** [comment]
lazy sync ?

**Comment by Andrew15-5** [comment]
There are no updates for ui plugin (I installed nvchad config about 2 days ago).

**Comment by Andrew15-5** [comment]
If I open without a file, then there are no errors. As soon as I _then_ open a file via `:e file<CR>`, the same error appears.

**Comment by siduck** [comment]
run :mes command

**Comment by Andrew15-5** [comment]
```
...cal/share/nvim/lazy/ui/lua/nvchad/statusline/default.lua:97: attempt to concatenate local 'name' (a nil value)                                                                                                    
stack traceback:                                                                                                                                                                                                     
^I...cal/share/nvim/lazy/ui/lua/nvchad/statusline/default.lua:97: in function 'fileInfo'                                                                                                                             
^I...cal/share/nvim/lazy/ui/lua/nvchad/statusline/default.lua:202: in function <...cal/share/nvim/lazy/ui/lua/nvchad/statusline/default.lua:199>                                                                     
E15: Invalid expression: v:lua.require('nvchad.statusline.default').run()                                                                                                                                            
```

**Comment by siduck** [comment]
and show your chadrc

**Comment by Andrew15-5** [comment]
```lua
return {}
```

**Comment by siduck** [comment]
@Andrew15-5  please use default_config.lua at least, why is your chadrc empty?

**Comment by Andrew15-5** [comment]
What do you mean default_config.lua? It's in the core dir. You said to show chadrc.lua. By default it is empty. What's the problem? It means that the error happens with just the default settings.

**Comment by siduck** [comment]
@Andrew15-5 chadrc by default is never empty. Even if you press "no" during nvchad installation, a minimal chadrc gets copied .

Please do a clean installation of nvchad and check

**Comment by Andrew15-5** [comment]
I was referring to the configuration in the chadrc.lua being (basically) empty. Here is the default config:

```lua
---@type ChadrcConfig
local M = {}

M.ui = { theme = 'onedark' }

return M
```

It will give me the exact same result as if I just leave this:

```lua
return {}
```

I don't see any reason to argue about default/minimal/empty chadrc.lua since the result will be the exact same anyway.
