### ISSUE TITLE
Feature Request: Possibility to print the cheatsheet

### ISSUE THREAD

**Issue by marek22k** [NvChad/ui#198]
**Is your feature request related to a problem? Please describe.**
I have a hard time remembering key combinations and it sometimes takes me a while to internalize them. Since I don't want to have the cheatsheet open all the time, I wish I could print it out.

**Describe the solution you'd like**
A possibility to print the cheatsheet with white background into a PDF.

**Comment by siduck** [comment]
@marek22k loop through all the mappings table and print the key names & their tables data.

**Comment by siduck** [comment]
fyi

```lua
local mappings = require('core.utils').load_config().mappings
```

**Comment by marek22k** [comment]
@siduck And how do I create a PDF file on it, which I can print?

**Comment by siduck** [comment]
@marek22k first save all the data in a file and then yknow how to print a file
