### ISSUE TITLE
tabufline. closeAllBufs error

### ISSUE THREAD

**Issue by hankji** [NvChad/ui#20]
vim --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az164-457

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

command : `:lua require('nvchad_ui/tabufline').closeAllBufs('');`
`
E5108: Error executing lua ...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:48: Vim(bdelete):E516: No buffers were deleted: confirm bd1
stack traceback:
        [C]: in function 'cmd'
        ...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:48: in function 'close_buffer'
        ...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:61: in function 'closeAllBufs'
        [string ":lua"]:1: in main chunk
E5108: Error executing lua ...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:48: Vim(bdelete):E516: No buffers were deleted: confirm bd1
stack traceback:
        [C]: in function 'cmd'
        ...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:48: in function 'close_buffer'
        ...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:61: in function 'closeAllBufs'
        [string ":lua"]:1: in main chunk
E5108: Error executing lua ...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:48: Vim(bdelete):E516: No buffers were deleted: confirm bd1
stack traceback:
        [C]: in function 'cmd'
        ...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:48: in function 'close_buffer'
        ...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:61: in function 'closeAllBufs'
        [string ":lua"]:1: in main chunk
table: 0x7f99c7a4c810
`

**Comment by siduck** [comment]
unable to reproduce the error, please provide a video of this behaviour.

**Comment by hankji** [comment]
I see the buffers is not 1, but the error show confirm bd1.
After ` rm -r ~/.config/nvim/plugin`, the error is missed.
If it recurs, I will report it.
thank you.

**Comment by PushUpek** [comment]
I have also this error. But only when I run nvim with Alpha dashboard active.
