### ISSUE TITLE
Nvdash loaded when reading from stdin

### ISSUE THREAD

**Issue by beatmax** [NvChad/ui#201]
If you do e.g., `man ls | nvim -R`, nvdash gets loaded and you have to press `tab` to see the input.
Apparently the plugin is not detecting that there is already a buffer with data.
As a workaround I'm doing this:

    nvdash = {
      load_on_startup = not vim.bo[vim.api.nvim_win_get_buf(0)].readonly,
    },

**Comment by sgorblex** [comment]
Related: if `load_on_startup = true`, using nvim as MANPAGER (`export MANPAGER="nvim +Man!"`) breaks because nvdash still loads and nvim tries to load the page over it
