### ISSUE TITLE
Delay  opening buffers (about 500ms)

### ISSUE THREAD

**Issue by vitorboschi** [NvChad/ui#215]
Opening an existing file adds about 500ms when NVChad is installed (no extra plugins, as far as I can tell).
This seems to happen when opening buffers: `563.087  545.325: opening buffers`. See attached file at end for complete timing log.

**To Reproduce**
1. Run `nvim somefile.txt`.
2. NVim opens quickly, but there's a noticeable delay before the file appears

**Expected behavior**
Opening files should be real quick

**Desktop (please complete the following information):**
 - Ubuntu 22.10
 - Fish
 - NVChad rev: 9d37797e6f9856ef25cfa266cff43f764e828827 (v2.0 branch)
 - Version of Neovim:

 ```
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Additional context**
- I have benchmarked the startup using `--startuptime` flag: 
[timing.txt](https://github.com/NvChad/NvChad/files/13537758/timing.txt)

- File type does not seem to make any difference. I used a txt file, but opening a cpp or a ts file leads to similar results.
- File size doesn't seem to matter either. The test file was 11k in size, but the same happened when I opened a 17 bytes json
- File opens instantly without NVChad
- The test was made on a file that is not inside a Git repo
- Repeating the test leads to similar numbers as well, so it's unlikely to be related to IO waits when reading the file

**Comment by siduck** [comment]
try tinyvim or other nvim configs, do they do the same?

**Comment by vitorboschi** [comment]
Tried tinyvim and it open up quickly. See attached benchmark: [timing-tiny.txt](https://github.com/NvChad/ui/files/13537800/timing-tiny.txt)

**Comment by vitorboschi** [comment]
Additional info: the delay is gone when I comment [the gitsigns plugin from the default config](https://github.com/NvChad/NvChad/blob/v2.0/lua/plugins/init.lua#L90-L117)

**Comment by vitorboschi** [comment]
I got it! The problem is on `vim.fn.system("git -C " .. '"' .. vim.fn.expand "%:p:h" .. '"' .. " rev-parse")`: Using `system` this way will start a shell to run the command, which is the source of the delay.
I was able to fix that by using `jobstart` instead of a direct `system` call. This way, nvim is not blocked while doing this work:
```
-          vim.fn.system("git -C " .. '"' .. vim.fn.expand "%:p:h" .. '"' .. " rev-parse")
-          if vim.v.shell_error == 0 then
-            vim.api.nvim_del_augroup_by_name "GitSignsLazyLoad"
-            vim.schedule(function()
-              require("lazy").load { plugins = { "gitsigns.nvim" } }
-            end)
-          end
+          vim.fn.jobstart("git -C " .. '"' .. vim.fn.expand "%:p:h" .. '"' .. " rev-parse",
+            {
+              on_exit = function(_, return_code)
+                if return_code == 0 then
+                  vim.api.nvim_del_augroup_by_name "GitSignsLazyLoad"
+                  vim.schedule(function()
+                    require("lazy").load { plugins = { "gitsigns.nvim" } }
+                  end)
+                end
+              end
+            }
+          )
```
I can create a PR for that if you want me to. It seems to be working fine on my end, but I know ~ zero about nvim/lua scripting, so I might be missing something important.

**Comment by lucario387** [comment]
feel free to.

**Comment by siduck** [comment]
@vitorboschi yes send a PR, but before that i'd also like to reproduce the issue and test it here, does it happen on large git repos?

**Comment by vitorboschi** [comment]
It happens in any buffer, even those that are not in a git repo, as the init function always run.
I guess the easiest way to repro is to add some delay in your bashrc and try to open a file in nvim

**Comment by lucario387** [comment]
Also, idk but gitsigns might not be attached for the first few buffers you opened with this, as it's async

**Comment by vitorboschi** [comment]
> Also, idk but gitsigns might not be attached for the first few buffers you opened with this, as it's async

gitsigns is not being initialized in this case, as I'm not opening a file inside a git repo. However, Lazy always executes the init function, which will create the autocmd on BufRead.

**Comment by lucario387** [comment]
> > Also, idk but gitsigns might not be attached for the first few buffers you opened with this, as it's async
> 
> 
> 
> gitsigns is not being initialized in this case, as I'm not opening a file inside a git repo. However, Lazy always executes the init function, which will create the autocmd on BufRead.

But if you are using inside a git-tracked repo? Will it still be attached instantly when opened, or never attaeched?

**Comment by vitorboschi** [comment]
> But if you are using inside a git-tracked repo? Will it still be attached instantly when opened, or never attaeched?

Oh, I see what you mean. In that case, there might be a small delay before gitsigns attach to the buffer.

**Comment by lucario387** [comment]
What if i do nvim file1 file2 file3 ..., will they still be attached?

**Comment by vitorboschi** [comment]
> What if i do nvim file1 file2 file3 ..., will they still be attached?

Yes, works fine

**Comment by vitorboschi** [comment]
@siduck hey, were you able to reproduce the issue on your end?

**Comment by siduck** [comment]
> @siduck hey, were you able to reproduce the issue on your end?

will check tonight
