### ISSUE TITLE
tabufline not restorable via typical session managers

### ISSUE THREAD

**Issue by nDimensionalSpace** [NvChad/ui#219]
**Describe the bug**
(N.B.: This issue crosses packages, so I added it here, just to get something going . . .  That is, maybe the devs want to move it elsewhere.)

When using almost-latest stable neovim, and the latest NvChad (including tabufline and example_config), attempts to save and restore a tabufline configuration (i.e., multiple neovim tabs, each with multiple buffers) with fairly common session managers (e.g., rmagatti/auto-session and folke/persistence.nvim) fail.  The failure mode is that some of the buffers are restored incorrectly, including (1) not being restored at all, (2) restored on incorrect tabs, and in at least one case (3) restored on multiple tabs.

**To Reproduce**
1. Install latest stable neovim (0.9.1).
2. Install default NvChad, and NvChad/example_config.
3. Install one of the session managers listed above (I can provide simple sample configurations, if desired).
4. Load neovim with file1.txt and file2.txt on tab1 and file3.txt and file4.txt on tab2.
5. Save session and close neovim.
6. Reopen neovim and open session.

**Expected behavior**
I expected (or at least would like) the tabs and buffers to be restored as they existed before closing neovim.

**Desktop (please complete the following information):**
 - Operating System: macOS 14.2
 - Terminal: latest iTerm2 (3.4.22)
 - Version of Neovim: 0.9.1

Thanks.

**Comment by nDimensionalSpace** [comment]
A few pics . . .  Before restarting, screenshots for tab1 and tab2.

<img width="1167" alt="before_tab1" src="https://github.com/NvChad/NvChad/assets/34101746/7c775f19-91d4-42ce-88cc-5f7190d628b8">

<img width="1167" alt="before_tab2" src="https://github.com/NvChad/NvChad/assets/34101746/f51810d0-9685-4b35-896d-c09989fefa99">

**Comment by nDimensionalSpace** [comment]
After restarting . . .  For this simple case, file3.txt is "moved" from tab2 (where it was initially) to tab1.

<img width="1167" alt="after_tab1" src="https://github.com/NvChad/NvChad/assets/34101746/7c8c0da2-3f92-4ec7-a57f-5b3636dcbaea">

<img width="1167" alt="after_tab2" src="https://github.com/NvChad/NvChad/assets/34101746/381fc840-62e9-4845-b2f7-341e280cc608">

**Comment by siduck** [comment]
obviously, do you not know that vim buffers in general arent bound to any tabs? i.e if you open a buffer in tab 1 , it'll still show in tab 2 , thats why i created tabufline which goes against vim philosophy cuz buffers are assorted in their respective tabs kinda.

So imo its better to write own session manager! which probably would be done in the future

**Comment by nDimensionalSpace** [comment]
@siduck: Actually, I did go and read up on buffers, windows and tabs before I posted this issue . . .  What I don't quite understand at this point is how tabufline is representing something that kind of looks like different sets of buffers per tab.

The naiveté of my question notwithstanding, I will note a few things: (1) the session manager I use the most (auto-session) is solely an extension of the native neovim session management facility, and (2)  it is clear that there is some state not being maintained across sessions.  If you all can represent the state of neovim solely via some extra variables, then presumably that should be able to be saved and retrieved . . .  Once I get a better handle on tabufline, I will come back to this issue with a clearer question/suggestion.

**Comment by lucario387** [comment]
The problem is that session states do not store buffers per tab, it stores buffers. That's it

**Comment by nDimensionalSpace** [comment]
@lucario387: Of course, given that neovim has no notion of buffers per tab . . .  But when I say "some state that is not being maintained", I mean that tabufline has some _approximation_ of buffers per tab (in the sense that it is only showing the user certain files in the bufline, or whatever the NvChad devs call it, in each tab), and presumably that approximation is being tracked by some internal variables, and enforced by some particular logic.  Ultimately, my claim is that any state of the editor should be able to be described by some number of variables, and as such, should be able to be recreated on startup.

Again, I am completely amenable to the claim that I am being naive . . .  I need to do some more mucking around with tabufline to see if there is something that completely blocks this possibility.

**Comment by lucario387** [comment]
It's not doable, sadly, as the internal session file doesn't support storing arrays or lua tables at all

**Comment by nDimensionalSpace** [comment]
@lucario387: Ok, well, if that is the case, that is a problem . . .  Maybe not insurmountable (if there is some mapping between Lua and vimscript), but at the very least a major pita.

I will likely keep mucking around with it, but regardless, thanks for the discussion.  🙏
