### ISSUE TITLE
Prevent tabufline overflow NvimTree pane

### ISSUE THREAD

**Issue by h0pes** [NvChad/ui#220]
When opening multiple buffers, tabufline overflows over the NvimTree window (see attached image, NvimTree on standard left position).
Would it be possible to add a setting like for standard bufferline which prevents such behaviour?
I think (but I'm not sure) that bufferline manages it with `offsets`, like `{ { filetype = "NvimTree", text = "", padding = 1 } }`.
Thanks
![2023-12-22_19-35_tabufline](https://github.com/NvChad/ui/assets/25418553/377a8cfc-3950-4109-ae0b-2823af70f1ca)

**Comment by Corgile** [comment]
It's nothing todo with `offsets` because NvChad uses its own bufferline system, by default the NvimTree window's offset is filled with spaces in length of `getNvimTreeWidth()`, which is a relatively fixed value (default: 30). So I think the problem is related to these lines:

https://github.com/NvChad/ui/blob/1e5539ad0a2ece2dd72771d582d0dac58f47844d/lua/nvchad/tabufline/modules.lua#L101-L108

—— The padding is kind of big. 

A temporary solution is to modify `/home/xxx/.local/share/nvim/lazy/ui/lua/nvchad/tabufline/modules.lua` :
by just removing the padding (or you can adjust it to fit)

![image](https://github.com/NvChad/ui/assets/48396880/ccf0a196-0432-4e72-a050-3591ccb68369)

**Comment by Corgile** [comment]
also, if you want to keep paddings, do this: (set `maxname_len` equivalent to `padding`)

![image](https://github.com/NvChad/ui/assets/48396880/678ab72c-df48-41aa-974c-dafabb6cfb93)

**Comment by Corgile** [comment]
> When opening multiple buffers, tabufline overflows over the NvimTree window (see attached image, NvimTree on standard left position). Would it be possible to add a setting like for standard bufferline which prevents such behaviour? I think (but I'm not sure) that bufferline manages it with `offsets`, like `{ { filetype = "NvimTree", text = "", padding = 1 } }`. Thanks ![2023-12-22_19-35_tabufline](https://private-user-images.githubusercontent.com/25418553/292618076-377a8cfc-3950-4109-ae0b-2823af70f1ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDM3OTksIm5iZiI6MTcwMzUwMzQ5OSwicGF0aCI6Ii8yNTQxODU1My8yOTI2MTgwNzYtMzc3YThjZmMtMzk1MC00MTA5LWFlMGItMjgyM2FmNzBmMWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDExMjQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiOWVmNzNkZGFiOTUzMzcxODRkOWE4OTFiNDg2Zjc2Y2ZjYzBhMTUyZGY2YjU2MDgyYzRkMGViYTRkM2QzNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kRb63YuohLDv-EMFOLlmFwzHqjuFfN4H5erb998ZsiQ)

also, if you want to keep paddings, do this: (set `maxname_len` equivalent to `padding`)

![image](https://github.com/NvChad/ui/assets/48396880/678ab72c-df48-41aa-974c-dafabb6cfb93)

**Comment by siduck** [comment]
ok found the issue

**Comment by siduck** [comment]
![image](https://github.com/NvChad/ui/assets/59060246/efafcdd0-ad41-427b-b1fe-7bee5e689489)

**Comment by siduck** [comment]
and you have custom btns over the right, so thats causing it as its width isnt included in available space

**Comment by siduck** [comment]
this is fixed in v3.0 only. Fixing it in v2.0 will make a breaking change cuz v3.0's syntax is different

@h0pes  v3.0 syntax is easier btw


https://github.com/NvChad/ui/assets/59060246/ec5d74b6-1d8e-4603-9b8a-c521b2bd0d58

**Comment by Corgile** [comment]
cool！

**Comment by Corgile** [comment]
how to update? I can only see v2.5 in https://github.com/NvChad/ui

**Comment by siduck** [comment]
@Corgile https://nvchad.com/news/v2.5_release

**Comment by h0pes** [comment]
I think his question is: does NvChadUpdate fix it in v. 2.0?
In other words is this issue fixed on 2.0 too.
Drop my post if I intended it wrongly.

**Comment by siduck** [comment]
@h0pes no i cant fix it in v2.0 , cuz i can calculate available space ( all modules in tabufline except buffers ) in v2.5 well cuz of the syntax, look https://github.com/NvChad/ui/blob/v2.5/lua/nvchad/tabufline/modules.lua#L43

in v2.0 the user directly overrides the modules tables  so i cant track it well
