### ISSUE TITLE
NvimTree Title Suggestion

### ISSUE THREAD

**Issue by Corgile** [NvChad/ui#221]
https://github.com/NvChad/ui/blob/1e5539ad0a2ece2dd72771d582d0dac58f47844d/lua/nvchad/tabufline/modules.lua#L144C1-L146C4
```lua
---------------------------------------------------------- components ------------------------------------------------------------
local M = {}

M.NvimTreeOverlay = function()
  return "%#NvimTreeNormal#" .. (vim.g.nvimtree_side == "right" and "" or string.rep(" ", getNvimTreeWidth()))
end
```
Hey, I think it will be good if we can configure the `NvimTreeOverlay` instead of filling it with spaces (just an example): 

```lua 
  tabufline = {
    overriden_modules = function(modules)
      modules[1] = {
        text = "The Title",
        align = "left|center|right",
        ...
      }
    end,
  },

```

**Comment by siduck** [comment]
hmm this is out of scope of tabufline, i wanted to keep it minimal and nvimtree without title looks cleaner imo
