### ISSUE TITLE
every word equal to current theme name will get replaced by the new theme name in custom/chadrc.lua

### ISSUE THREAD

**Issue by logicalbhanu** [NvChad/ui#223]
**Describe the bug**
In custom/Chadrc.lua Every word which is equal to the word of the current selected theme get replaced by the newly selected theme name if theme is toggled through default theme changer.

**To Reproduce**
1. Go to 'custom/chadrc.lua'
2. let say your current theme is "catppuccin" then add a comment in the file say "my theme is catppuccin".
3. now change your theme to say "aquarium" from the theme switcher.
4. see the chadrc.lua, your comment should now be "my theme is aquarium".

**Expected behavior**
This should not happen and word for the theme name should only be replaced at places where necessary to change theme and not everywhere in chadrc.lua such as in comments and other places

**Screenshots**
before:
<img width="1512" alt="image" src="https://github.com/NvChad/NvChad/assets/40262328/c836c101-662f-430c-a90b-473021cbc4f4">
after:
<img width="1512" alt="image" src="https://github.com/NvChad/NvChad/assets/40262328/bfdaa459-2265-41e9-b96f-914f1b811386">
see the comment line at line with relative line number 10

**Desktop (please complete the following information):**
 - Mac os sonoma
 - wezterm
 - 0.9.4

**Comment by siduck** [comment]
https://github.com/NvChad/ui/blob/v2.0/lua/nvchad/utils.lua#L23 maybe we could replace theme = "abc" with theme = "xyz"  there

**Comment by logicalbhanu** [comment]
> https://github.com/NvChad/ui/blob/v2.0/lua/nvchad/utils.lua#L23 maybe we could replace theme = "abc" with theme = "xyz"  there
> 
> 

I didn't get it(still a noob on nvim config), can you please explain.

**Comment by siduck** [comment]
nvm it but thats the one only way we can change theme name in chadrc.lua so cant do anything about this, just dont write your theme name multiple times!

**Comment by logicalbhanu** [comment]
Thanks for the reply, what i acctually want to do is, based on a particular theme(which in my case is catppuccin), i want to change the color of cursearch highlight group, but since cursearch is linked to search group(and i don't know how to unlink it) i am thinking of changing search group color.
But since this is the issue so if i am doing this, while changing the theme from theme switcher, the "if" condition that i am using to detect current selected theme is "catppuccin", is itself getting changed and thus my problem is not getting solved.

**Comment by siduck** [comment]
read custom config's highlight section in nvchad.com
