### ISSUE TITLE
nvim-tree with right side menu causes a gap

### ISSUE THREAD

**Issue by guillenotfound** [NvChad/ui#224]
<img width="1440" alt="Screenshot 2024-01-07 at 14 42 14" src="https://github.com/NvChad/ui/assets/5492960/3dbc6ac7-2171-405c-b721-85324ad6126a">
<img width="1440" alt="Screenshot 2024-01-07 at 14 42 04" src="https://github.com/NvChad/ui/assets/5492960/a52a71df-8c5d-411a-9b57-ea0ab989da5b">

As shown in the first image, when the file menu is active, there will be a gap from the left side to the first opened tab which is a bit annoying. From my understanding, it should be related to buffline which is contained within this package, but if that's not the case please let me know.

This is the custom nvim-tree config:

```diff
diff --git a/configs/overrides.lua b/configs/overrides.lua
index d98328e..a831ef7 100644
--- a/configs/overrides.lua
+++ b/configs/overrides.lua
@@ -57,10 +57,6 @@ M.nvimtree = {
     },
   },
 
+  view = {
+    side = "right",
+    width = 35,
+  }
 }
 
 return M

```

**Comment by siduck** [comment]
read to override tabufline modules
http://localhost:3000/docs/config/nvchad_ui

HINT

1) table insert 1st module at end of modules table
2) table.remove 1st index

1st module cuz its the nvimtree offset module

**Comment by guillenotfound** [comment]
Thanks for the hint, could it be that I'm still learning that's why even with the docs I don't get it. Like yes I understand you are just playing with the indexes but it does not seem to be evident what's happening. Maybe a bit more in depth explanation would help 👍 

In any case got it working, just saying this so that it would help others in the future.

**Comment by siduck** [comment]
@guillenotfound basically statusline and tabufline are joined strings, before joining them into strings, they are just array of strings, you can assume that!

so you just change the indices to override em

**Comment by herself** [comment]
Any chance this will get a fix?

edit: Okay, never mind, managed to find a more straightforward workaround. Turns out that `tabufline` supports this! It checks if `vim.g.nvimtree_side` is set to `right` for that, but it doesn't look like `nvimtree` is updating it at all!

So I've put `vim.g.nvimtree_side = "right"` to my `init.lua` and looks like that annoying gap is gone 💪

**Comment by siduck** [comment]
> Any chance this will get a fix?
> 
> edit: Okay, never mind, managed to find a more straightforward workaround. Turns out that `tabufline` supports this! It checks if `vim.g.nvimtree_side` is set to `right` for that, but it doesn't look like `nvimtree` is updating it at all!
> 
> So I've put `vim.g.nvimtree_side = "right"` to my `init.lua` and looks like that annoying gap is gone 💪

i dont think that should work, i'd just suggest table.remove(modules, 1 ) , learn how to override tabufline modules https://nvchad.com/docs/config/nvchad_ui
