### ISSUE TITLE
NvChad unable to update itself due to space in username (windows)

### ISSUE THREAD

**Issue by Rexcrazy804** [NvChad/ui#228]
**Describe the bug**
the NvChadUpdate command fails to update nvchad itself due to (I assume) a space in my username.

**To Reproduce**
1. have a space in your user name (preferably windows)
2. execute NvChadUpdate

**Expected behavior**
Updation of nvchad.

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/37258415/dd54af20-669e-4b0f-b4c6-17b82e8eada1)
![image](https://github.com/NvChad/NvChad/assets/37258415/31625f80-3017-44f1-a24e-2076d393a963)

**Desktop (please complete the following information):**
 - Windows 11
 - Default Terminal
 - 9.5

**Additional context**
nothing more to add I believe.

**Comment by siduck** [comment]
![image](https://github.com/NvChad/ui/assets/59060246/40b803bc-a9fa-4d08-872f-ebf6b8aaa5b3)

nvim_config is the stdpath('config') here

**Comment by siduck** [comment]
show me output of `:lua vim.fn.stdpath('config')`

**Comment by lucario387** [comment]
Just wrap the string with quotes. This can happen on linux too (nvim-treesitter has dealt with this before)

**Comment by Rexcrazy804** [comment]
> ![image](https://private-user-images.githubusercontent.com/59060246/302109620-40b803bc-a9fa-4d08-872f-ebf6b8aaa5b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjAzNjUsIm5iZiI6MTcwNzMyMDA2NSwicGF0aCI6Ii81OTA2MDI0Ni8zMDIxMDk2MjAtNDBiODAzYmMtYTlmYS00ZDA4LTg3MmYtZWJmNmI4YWFhNWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE1MzQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYTE4ZWYxY2I0ZGE0N2NjOWMwYzE4ZmIxM2QyN2NjOTY0YTIxMjg5NmI2NTIyZTM5Mjk1OGI3M2FlNDM3YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ld0hLh6MPmQlTDYTFAXPk7Uf8bvmhatBjxYEkMLjsJw)
> 
> nvim_config is the stdpath('config') here

![image](https://github.com/NvChad/ui/assets/37258415/a1b35f28-a1c1-4e25-878f-1f24517b6876)

**Comment by lucario387** [comment]
Yes as I have said, nvim-treesitter have also suffered this issue before. Escape + wrap the strings :)

**Comment by siduck** [comment]
> Yes as I have said, nvim-treesitter have also suffered this issue before. Escape + wrap the strings :)

so "path"    ?

**Comment by lucario387** [comment]
ye

**Comment by Rexcrazy804** [comment]
hmm so I assume I have to re install nvchad with git clone once the change has been merged I suppose? or is there an easier alternative?

**Comment by lucario387** [comment]
you can git pull from CLI :)

**Comment by siduck** [comment]
@Rexcrazy804  try the fix branch, 

{  "NvChad/ui", branch = 'fix' } , in your custom plugins, and try

**Comment by Rexcrazy804** [comment]
![image](https://github.com/NvChad/ui/assets/37258415/2e83c584-6ee4-47c3-aa25-005b697e0a1c)

Neovim instantly quits after I get this message (hardly readable, had to screencapture to even get this screen shot), is that the expected behavior?

**Comment by Rexcrazy804** [comment]
@siduck tried running NvChadUpdate as instructed but it keeps asking me to reopen neovim and run NvChadUpdate

**Comment by siduck** [comment]
ok its working.
