### ISSUE TITLE
NvChadUpdate Currently Quits Neovim

### ISSUE THREAD

**Issue by UnsaltedScholar** [NvChad/ui#231]
Hello,

Currently, running `NvChadUpdate`  immediately exits neovim with some weird errors. I am making this issue here at the behest of @siduck. Below is the error in question:

```
Updated local branch! reopen neovim & run NvChadUpdate command again                                     
nvim: src/unix/core.c:148: uv_close: Assertion '!uv__is_closing(handle)' failed
```

This can be somewhat circumvented by first opening a new split via `:new` or `:vnew`.

**Comment by siduck** [comment]
ok fixed
