### ISSUE TITLE
Search count update in the statusline

### ISSUE THREAD

**Issue by idr4n** [NvChad/ui#238]
Hi,

I have a search count module in the statusline that looks like this:

```lua
local function search_count()
  if vim.v.hlsearch == 0 then
    return ""
  end

  local ok, search = pcall(vim.fn.searchcount, { recompute = true, maxcount = 500 })
  if (not ok or (search.current == nil)) or (search.total == 0) then
    return ""
  end

  return string.format("%d/%d", search.current, math.min(search.total, search.maxcount))
end

M.ui = {
  statusline = {
    theme = "vscode",
    -- stylua: ignore
    overriden_modules = function(modules)
      ...
      table.insert(modules, 6, search_count())
      ...
    end,
  },
}
```

I have used the same `search_count` in heirline and when setting the statusline without any plugins. In either case, when I start searching, the statusline would start showing me the number of results right away while typing, before hitting enter. However, in Nvchad this is not happening, that is, the statusline will only update after I hit enter, then the number of results are shown. Lualine does not update the statusline either while typing the search query.

Is there any way I can achieve this behavior?

**Comment by siduck** [comment]
you have to redraw statusline i think

**Comment by idr4n** [comment]
> you have to redraw statusline i think

But in heirline or the statusline without plugins, there is no need to redraw the status line on every keystroke. So was wondering what in particular makes the statusline in Nvchad to prevent from showing the search results as you type.

**Comment by siduck** [comment]
i'm assuming those plugins  probably handle it  so the user doesnt has to do it. I'll look into this , this weekend. 

Nvchad's statusline codebase is the simplest you'd see, a list of functions ,concanetated into a single string

**Comment by idr4n** [comment]
Thanks a lot for the help!

I think it is the plugin that stops this behavior actually because if I configure the statusline without any plugins (which I used to do before), there is no need to redraw the status line (otherwise this would require redrawing on every keystroke?).

> Nvchad's statusline codebase is the simplest you'd see, a list of functions ,concanetated into a single string

Yeah, that's pretty much what you do when configuring the statusline without plugins 🤔 

In terms of redrawing the statusline, I tried this but didn't work:

```lua
vim.api.nvim_create_autocmd("CmdlineChanged", {
  group = augroup "search_count",
  callback = vim.schedule_wrap(function()
    vim.cmd "redrawstatus"
  end),
})
```

Thanks again!

**Comment by siduck** [comment]
i tried your code and vim.v.hlsearch is always 0 until i press Enter. 

```lua
vim.on_key(function(char)
  if vim.fn.mode() == "n" then
    local new_hlsearch = vim.tbl_contains({ "<CR>", "n", "N", "*", "#", "?", "/" }, vim.fn.keytrans(char))
    if vim.opt.hlsearch:get() ~= new_hlsearch then
      vim.opt.hlsearch = new_hlsearch
    end
  end
end, vim.api.nvim_create_namespace "auto_hlsearch")
```
try this instead of that autocmd.

i found it here https://www.reddit.com/r/neovim/comments/zc720y/comment/iyvcdf0/?utm_source=share&utm_medium=web2x&context=3

**Comment by idr4n** [comment]
Thanks a lot for your help! I tried that by adding it in my `custom/init.lua` file instead of the other autocmd but is not working as expected (the search count does not updates as I type either, does it update for you?).

It is very strange actually. I trie disabling the Nvchad/ui statusline to test things out and adding a simple status line like this, but still the count does not update as I type:

```lua
-- in custom/plugins.lua
  {
    "NvChad/ui",
    config = function()
      vim.opt.statusline = ""
    end,
  },

-- in custom/init.lua
local function search_count()
  if vim.v.hlsearch == 0 then
    return ""
  end

  local ok, search = pcall(vim.fn.searchcount, { recompute = true, maxcount = 500 })
  if (not ok or (search.current == nil)) or (search.total == 0) then
    return ""
  end

  if search.incomplete == 1 then
    return "%#SLMatches# ?/? %#SLNormal#"
  end

  return string.format(" %d/%d", search.current, math.min(search.total, search.maxcount))
end

function StatusLine()
  local statusline = ""
  statusline = statusline .. "%="
  statusline = statusline .. search_count()
  statusline = statusline .. "%="
  statusline = statusline .. "%t"

  return statusline
end

vim.o.statusline = "%!v:lua.StatusLine()"
```

This is pretty much what I do in my own config with a vanilla statusline, in which the count does update as I type. I was trying to figure it out if by any chance I have another setting in that config which makes this happen but didn't find anything so far that I can think of.

**Comment by siduck** [comment]
if it happens with vanilla statusline then i cant do much about this! try asking on r/neovim and see
