### ISSUE TITLE
tabufline. closeAllBufs error

### ISSUE THREAD

**Issue by PushUpek** [NvChad/ui#24]
When I run nvim with Alpha dashboard active I'm getting this error:

`
E5108: Error executing lua ...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:48: Vim(bdelete):E516: No buffers were deleted: confirm bd1
stack traceback:
        [C]: in function 'cmd'
        ...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:48: in function 'close_buffer'
        ...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:61: in function 'closeAllBufs'
        [string ":lua"]:1: in main chunk
`

To reproduce this:
1. Enable Alpha plugin in configuration
2. Run nvim with command `nvim`
3. Open two files
4. Click the button to close all buffers

**Comment by siduck** [comment]
unable to reproduce the issue

**Comment by siduck** [comment]
are you sure that you have an upto data nvchad+ did packersync?

**Comment by PushUpek** [comment]
I found what was causing the problem. I had:
```dashboard.config.opts.noautocmd = true```
in Alpha configuration. After commenting on this option everything works.
