### ISSUE TITLE
Bugs when Interacting with mbbill/undotree

### ISSUE THREAD

**Issue by rennsax** [NvChad/ui#248]
**Describe the bug**
mbbill/undotree uses an extra buffer to show diff information like this:

![image](https://github.com/NvChad/NvChad/assets/93167100/c02dd82d-ccf4-4b93-9276-df1058ab5ff6)

The buffer appears on the tabufline, which is expected.

However, when the undotree is toggled down, the buffer remains:

![image](https://github.com/NvChad/NvChad/assets/93167100/4300a6ff-1058-482f-90da-3b227b8ae678)

When I tried to view the buffer with <Tab> or mouse click, Neovim immediately crashed.

**To Reproduce**
1. Install mbbill/undotree.
2. Open an arbitrary file.
3. Open undotree, then close.
4. Press <Tab>, or click to the diff buffer. Neovim immediately crashes.

**Expected behavior**
The buffer shouldn't appear on the tabufline after undotree is closed.

**Screenshots**
Above.

**Desktop (please complete the following information):**
 - Operating System: macOS 14.3.1
 - Terminal: iTerm2 / Neovide
 - Version of Neovim: v0.9.5

**Additional context**
None.

**Comment by siduck** [comment]
undotree uses eventignore... its hard to track it :/

https://github.com/mbbill/undotree/issues/174

**Comment by siduck** [comment]
@akinsho how do you handle such edgecases?

**Comment by siduck** [comment]
there is no choice but to use this now

```lua
local autocmd = vim.api.nvim_create_autocmd

autocmd("FileType", {
  pattern = "undotree",
  callback = function()
    vim.schedule(function()
      for i, buf in ipairs(vim.t.bufs) do
        if not vim.bo[buf].buflisted then
          vim.t.bufs = vim.list_slice(vim.t.bufs, 1, i - 1)
        end
      end
      vim.cmd.redrawtabline()
    end)
  end,
})

**Comment by siduck** [comment]
or use this https://github.com/jiaoshijie/undotree
