### ISSUE TITLE
Opening neovim in / directory causes the status line to error.

### ISSUE THREAD

**Issue by David-Aguilo** [NvChad/ui#250]
**Describe the issue**
Due to the way the `cwd` module of the statusline is generated. It produces an error when neovim is opened in the `/` directory.

```lua
M.cwd = function()
  local icon = "%#St_cwd_icon#" .. "󰉋 "
  local name = "%#St_cwd_text#" .. " " .. vim.loop.cwd():match "([^/\\]+)[/\\]*$" .. " "
  return (vim.o.columns > 85 and ("%#St_cwd_sep#" .. sep_l .. icon .. name)) or ""
end
```

I'm guessing the match statement cannot handle the directory just being `/` and it errors out.

I have already looked to see if the issue has been reported and it was for v2.0: https://github.com/NvChad/ui/issues/197

I have updated all my plugins to see if maybe I had an older version, but it still happens.

**To reproduce**
```
cd /
nvim
```

**Expected Behaviour**
No error.

**Screenshots**
![imatge](https://github.com/NvChad/ui/assets/89081503/1c76a3e6-f65e-45fc-abcb-f62af8681c1d)

**Desktop**

- Operating System: ArchLinux
- Terminal: alacritty
- Version of Neovim: v0.9.5

**Comment by David-Aguilo** [comment]
The issue can be fixed by replacing
```lua
vim.loop.cwd():match "([^/\\]+)[/\\]*$" .. " "
```
with
```lua
vim.fn.fnamemodify(vim.fn.getcwd(), ":t") .. " "
```
Though, then the working directory in the statusline appears blank.
![imatge](https://github.com/NvChad/ui/assets/89081503/2f814100-ad40-401c-8ff5-e5e8a7a4603b)

**Comment by lucario387** [comment]
PR Welcome

**Comment by David-Aguilo** [comment]
True, I don't know if this is the fix that is to be employed because it leaves the field blank, but sure, I'll make a PR. I'll try to see if I can get a better regex going which can handle both cases as well.

**Comment by lucario387** [comment]
When in doubt, if statements :)

**Comment by David-Aguilo** [comment]
Done
