### ISSUE TITLE
Statusline overide_modules not working after v2.5

### ISSUE THREAD

**Issue by ViiEx** [NvChad/ui#254]
I used to have a module that was checking if the copilot was running on the statusline

```lua
M.ui = {
-- ...other ui options
  statusline = {
    overriden_modules = function(modules)
      table.insert(
        modules,
        9,
        (function()
          --- @diagnostic disable: deprecated
          for _, client in pairs(vim.lsp.get_active_clients()) do
            if client.name == "copilot" then
              return "%#TeSTTCopilot#" .. "   "
            end
          end
          return "%#TeSTTCopilot#" .. "   "
        end)()
      )
    end,
    theme = "vscode_colored",
  },
-- ...other ui options
}
```

After v2.5 the module was not displayed in my statusline anymore.

I did notice that in the new `utils.lua` file in the `stl` folder has removed the part that was merging the custom modules.

```lua
-- From v2.0 statusline (ex: vscode_colored.lua)
M.run = function()
  -- modules
  if config.overriden_modules then
    config.overriden_modules(modules)
  end

  return table.concat(modules)
end
```
Is there any way in the v2.5 to add a custom module like before or is there any possibility that the overriden_modules will have a come back in a feature update?

**Comment by siduck** [comment]
it has been improved in v2.5!

https://nvchad.com/docs/config/nvchad_ui/

**Comment by ViiEx** [comment]
Ow ok I get it thanks, I had seen the docs but since the types didn't seem updated I got confused.

**Comment by lucario387** [comment]
the types are removed, not "not updated" :)

**Comment by siduck** [comment]
@KorigamiK i thought you added types for this too!!

**Comment by KorigamiK** [comment]
> @KorigamiK i thought you added types for this too!!

I didn't but let me do these too 😆

**Comment by siduck** [comment]
@KorigamiK go ahead buddy, who's stopping you :rofl:
