### ISSUE TITLE
Disable or Set order and modules for status line in v2.0

### ISSUE THREAD

**Issue by cscherrNT** [NvChad/ui#257]
How to do it? I've tried to dig through the code, but I cant find something. My configs are pretty heavily customized, updating to v2.5 is impractical.

**Comment by cscherrNT** [comment]
We can override `vim.opt.statusline` after nvchad ui has loaded:


Loading `lualine` with `lazy` for example:
```lua
  {
    "nvim-lualine/lualine.nvim",
    lazy = false,
    dependencies = {
      "nvim-tree/nvim-web-devicons",
      "NvChad/ui", -- load after nvchad ui
    },
    config = function()
      require("lualine").setup()
    end,
  },
```

This is okay for a workaround, but being able to change the order of the statusline would be helpful.

**Comment by siduck** [comment]
https://nvchad.com/docs/config/nvchad_ui/ ,v2.0 is depreceated. v2.5 has cleaner syntax for overriding modules btw

you should be loading lualine after ui plugin.... and why devicons there?  its already in default plugins, not needed.
