### ISSUE TITLE
Setting of sp or vsp terminal size not work  after migrate to v2.5

### ISSUE THREAD

**Issue by Myxhf** [NvChad/ui#267]
**Screenshots**
<img width="503" alt="shoot" src="https://github.com/NvChad/NvChad/assets/148979028/349dcf8e-b9db-4f81-8f0c-43122a0d8fcb">

<img width="1272" alt="shoot2" src="https://github.com/NvChad/NvChad/assets/148979028/8d7e9df0-278d-41c9-90e0-beb7f45712e9">

**Desktop (please complete the following information):**
 - Operating System : ubuntu 22.04lts
 - Terminal
 - Version of Neovim : v0.10.0

**Comment by siduck** [comment]
do know that those sizes will only work on the first launch of terminals

**Comment by le4ker** [comment]
Same for me, the following snippet doesn't have any effect:

```
term = { sizes = { sp = 0.5 } }
```

**Comment by siduck** [comment]
fixed, it  was happening because the functions called in our term mappings ( main nvchad repo ) had the "size" property , so obviously the term module will prefer it over the chadrc one :)
