### ISSUE TITLE
Disabling module produces invalid expression

### ISSUE THREAD

**Issue by martin-braun** [NvChad/ui#27]
I overwrite the UI config like so: 

```lua
local M = {}

M.override_options = {
    statusline = {
        separator_style = "arrow", -- default/round/block/arrow
    },

    tabufline = {
        overriden_modules = {
            buttons = function()
                return ""
            end
        }
    }
}

return M
```

I can verify my config loads, because it uses the arrow separator on the status line, but as soon as the tabufline would show, I get this:

```
^I...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lu...site/pack/packer/opt/ui/lua/nvchad_ui/tabufline/init.lua:97>
E15: Invalid expression: v:lua.require('nvchad_ui').tabufline()
```

I'd like to hide the theme toggle icon and the red X in the top right corner.

**Comment by siduck** [comment]
@martin-braun sorry for late reply! I think you misread the docs, overriden_modules is a function and not a table.

```lua
   overriden_modules = function()
          return {
            buttons = function()
              return ""
            end,
          }
        end
  ```

**Comment by martin-braun** [comment]
I falsely believed that `overriden_modules` is similar to `override_options` in the sense that it can be a table or function. I think it would be nice if this was the case. Thank you though, it's working great, @siduck. Absolutely made sense for me to hide those buttons, since I disabled mouse controls in Neovim entirely.

**Comment by siduck** [comment]
@martin-braun agreed, But if its a  table then you cant import other modules but yes that'll work great just to disable modules ( like your syntax above )
