### ISSUE TITLE
Can't use `Ctrl + i` to navigate forward through jump list 

### ISSUE THREAD

**Issue by MarLapuz** [NvChad/ui#270]
When navigating through the jump list, `Ctrl + o` works just fine, but `Ctrl + i` does not function properly when the `tabufline` is disabled.

My current `chardrc.lua` config:
```lua
---@type ChadrcConfig
local M = {}

M.ui = {
  ...
  tabufline = {
    enabled = false,
    lazyload = true,
    modules = nil,
  },
}

return M

``` 

Attached a gif for reference.

![CleanShot 2024-04-04 at 16 12 29](https://github.com/NvChad/ui/assets/31674631/00fc866b-fbce-428f-89d4-95af3f281f65)

**Comment by siduck** [comment]
disable tab mappings in nvchad and it'll work, its not a nvchad issue. more like nvim.

**Comment by MarLapuz** [comment]
> disable tab mappings in nvchad and it'll work, its not a nvchad issue. more like nvim.

@siduck any tips on how to do that?

**Comment by siduck** [comment]
@MarLapuz  `vim.keymap.del("n", "<tab>")`

i hope u know where to add that, if not then check nvchad docs! as nvchad v2.5 now has general nvim config structure so  you should know :))

**Comment by MarLapuz** [comment]
> @MarLapuz `vim.keymap.del("n", "<tab>")`
> 
> i hope u know where to add that, if not then check nvchad docs! as nvchad v2.5 now has general nvim config structure so you should know :))

Got it thanks a lot @siduck ! 🙌
