### ISSUE TITLE
Tabufline treeOffset doesn't align with nvim tree when it's on the right side

### ISSUE THREAD

**Issue by nowaylifer** [NvChad/ui#271]
So I changed nvim tree side to the right and overrided tabufline order like so (also removed buttons):
```javascript
tabufline = {
  order = { "buffers", "tabs", "treeOffset" }
}
```
Now I have this block above nvim tree slightly protruding leftwards:
![Screenshot 2024-04-06 001703](https://github.com/NvChad/ui/assets/116919411/ca3c224b-741f-48df-a871-f3374c7ab95a)

Desktop (please complete the following information):
Operating System : WSL ubuntu 22.04lts
Terminal: Windows Terminal
Version of Neovim : v0.9.4

**Comment by siduck** [comment]
it does align  , pls fix the line separator of  your nvimtree...

i.e make its bg and fg the same as nvimtree's bg

**Comment by nowaylifer** [comment]
Actually, it's neovim problem https://github.com/neovim/neovim/issues/24266
