### ISSUE TITLE
Cursor seems to be in the wrong position in nvterm?

### ISSUE THREAD

**Issue by Ethanscharlie** [NvChad/ui#274]
Whenever I use nvterm the cursor (Unless using some application in the terminal like gdb or ranger) Goes to the top after every command but the rest of the terminal doesn't clear so new commands are written over other outputs and new outputs are also being written over old outputs and it ends of being so weird and confusing I have to clear the terminal after almost every command, Is this normal?

![image](https://github.com/NvChad/ui/assets/96396138/5873dcae-09ff-47c2-bf70-a8c38183b7a7)

**Comment by siduck** [comment]
from nvchad v2.5 nvterm isnt being used. are you talking about the term module ?

**Comment by Ethanscharlie** [comment]
I don't think so
```  {
    "NvChad/nvterm",
    init = function()
      require("core.utils").load_mappings "nvterm"
    end,
    config = function(_, opts)
      require "base46.term"
      require("nvterm").setup(opts)
    end,
  },
```

Should I just update nvchad then?

**Comment by Ethanscharlie** [comment]
Btw I had this same exact issue when trying the toggleterm plugin

**Comment by siduck** [comment]
obv! update to nvchad v2.5

**Comment by siduck** [comment]
https://nvchad.com/news/v2.5_release

**Comment by Ethanscharlie** [comment]
Still doesn't work on fresh nvchad 2.5 install with no custom plugins, and yes I did wipe .local/share/nvim

**Comment by Ethanscharlie** [comment]
It looks like I was able to fix by resetting my .bashrc

**Comment by Ethanscharlie** [comment]
It was caused by powerline
```
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/share/powerline/bindings/bash/powerline.sh
```
