### ISSUE TITLE
Add support for lazy.nvim defined keymaps in cheatsheet?

### ISSUE THREAD

**Issue by ashb** [NvChad/ui#278]
I have this in my plugins config file:

```lua
  {
    "nvim-neo-tree/neo-tree.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-tree/nvim-web-devicons",
      "MunifTanjim/nui.nvim",
      "s1n7ax/nvim-window-picker",
    },
    cmd = { "Neotree" },
    opts = function()
      return require "configs.neo-tree"
    end,
    keys = {
      { "<C-n>", "<cmd>Neotree toggle<cr>", desc = "NeoTree Show" },
    },
  },
```

And I had a custom snippet In the v2 style `custom.mappings` that injected things so that my lazily defined keymaps showed up in "<spc>ch":

```lua
local group = vim.api.nvim_create_augroup("mappings", { clear = true })
vim.api.nvim_create_autocmd("User", {
  pattern = "LazyDone",
  group = group,
  callback = function()
    local config = require("core.utils").load_config().ui
    require("plenary.reload").reload_module("nvchad.cheatsheet." .. config.cheatsheet.theme)

    local lazyPlugins = require("lazy").plugins()

    for _, plugin in pairs(lazyPlugins) do
      if plugin._.handlers and plugin._.handlers.keys ~= nil then
        local name = require("plenary.path").new(plugin.name)
        if M[name.filename] == nil then
          M[name.filename] = { plugin = true }
        end
        for _, key in pairs(plugin._.handlers.keys) do
          local mode = key.mode or "n"
          if M[name.filename][mode] == nil then
            M[name.filename][mode] = {}
          end
          M[name.filename][mode][key.lhs] = { "", key.desc or key.id or "??" }
        end
      end
    end
  end,
})
```

This obviously doesn't work anymore. Would you be willing to accept a PR to have something like this work again? (The group is the plugin name in this case, it doesn't need to be the first word)

For example, this neotree and my surround config showed up as:

<img width="574" alt="Screenshot 2024-04-27 at 18 12 49" src="https://github.com/NvChad/ui/assets/34150/af108fdc-ae86-4eef-995f-a312ced82919">

**Comment by siduck** [comment]
![image](https://github.com/NvChad/ui/assets/59060246/30315878-7422-45df-b251-d0e79e7c6c14)

these are lazy ones, mappings will be loaded when they are available to neovim i.e we get it by `vim.api.nvim_get_keymap` function, so if lazy doesnt add mappings to it then cant do anything about it

**Comment by ashb** [comment]
Oh! It's this block that's causing me problem here as there's only a single mapping.

```lua
  -- remove groups which have only 1 mapping
  for key, x in pairs(tb_to_add) do
    if #x <= 1 then
      tb_to_add[key] = nil
    end
  end
```


Would you accept some (non-monkeypatching) way of making this pluggable:

```lua
  local mappings_tb = {}
  require("nvchad.cheatsheet").organize_mappings(mappings_tb)
```

That way I could set what ever tables/blocks I wanted?

**Comment by siduck** [comment]
can you test the bugfix branch?

{ 
  "NvChad/ui" , branch = "bugfix"
 }

**Comment by ashb** [comment]
```     ui 2.62ms  start
        dir    /Users/ash/.local/share/nv2_5/lazy/ui
        url    https://github.com/NvChad/ui
        branch bugfix
        commit 9a1ff4f
        readme README.md
```

Yup, that now shows the neotree, and also removes the other `<Plug>` mappings that I was going to ask about. Nice!

**Comment by ashb** [comment]
I did however notice some weird glitch with closing the cheatsheet -- once the cheetsheet is closed, it doesn't seem to display buffers (editing a file, or opening a new split.


To reproduce:

- `nvim LICENSE`
- `<spc>ch`
- `<esc>`
- `:sp init.lua`

The init split opens, but the view is empty

**Comment by siduck** [comment]
https://github.com/NvChad/ui/assets/59060246/aa48f2be-56c9-45e8-831e-879eaa2c2be4

it works fine here, i hope you are using latest nvchad aka lazy sync

**Comment by ashb** [comment]
Using `NVIM_APPNAME` to get a clean cache etc. Commands ran:

- `git clone git@github.com:NvChad/starter ~/.config/nvclean && cd ~/.config/nvclean`
- `NVIM_APPNAME=nvclean nvim LICENSE`

(I quit and re-opened it just incase?)

and then in vim:

`<spc>ch`
`<esc>`
`sp lazy-lock.json`

https://github.com/NvChad/ui/assets/34150/179897e0-85bc-44ef-9a7d-5cf25a02fdb6

There is also no tab bar once the split opens. Neovim 0.9.5. I should probably move this in to a separate issue?

**Comment by siduck** [comment]
@ashb  do lazy sync and try now

**Comment by ashb** [comment]
Yup that got it, thanks for the speedy fix
