### ISSUE TITLE
Insert mode signature_help not work?

### ISSUE THREAD

**Issue by whitemoon** [NvChad/ui#279]
https://github.com/NvChad/ui/blob/525b0767cb19260adb256910e6d4c5715529ad3e/lua/nvchad/lsp/signature.lua#L18

When i changed `%s+` to `%s+$`, it's working, this changed is corrected?

**Comment by danielrs** [comment]
Same issue for me today, here's a PR:
https://github.com/NvChad/ui/pull/281
