### ISSUE TITLE
Make changing the vim.notify optional

### ISSUE THREAD

**Issue by anstadnik** [NvChad/ui#29]
This part:
https://github.com/NvChad/ui/blob/514958a9dba4fd95e0fdf49749e9e38f5dad5212/lua/nvchad_ui/lsp.lua#L29-L39
breaks compatibility with this plugin: https://github.com/folke/noice.nvim/, because it overwrites `vim.notify` which has been already changed from the noice.nvim. I'd like to opt out of the modification of `vim.notify` by NvChad.

**Comment by siduck** [comment]
what happens if you load noice.nvim in your custom lspconfig?

**Comment by anstadnik** [comment]
Here:
https://github.com/folke/noice.nvim/blob/main/lua/noice/util/health.lua#L34-L38
It understands that it has overwritten the `vim.notify`, but it was again overwritten by something else.

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/195995533-50ece2bf-7196-4e2b-b800-cba3cbdff68e.png)

ok so the vim.notify code is loaded here in the default lspconfig and then you loading noice.nvim ( will obviously override vim.notify ) , shouldnt that work?

**Comment by anstadnik** [comment]
It would if I wouldn't lazy load noice.nvim on vim enter, hence creating a race condition.

**Comment by anstadnik** [comment]
Well, in this particular case since I want this plugin to be loaded all the time it could as well be loaded not lazily.

If you don't consider it to possibly become a problem in general case, you can close the issue :)

**Comment by siduck** [comment]
hmm i  think so but what does the plugin do? It handles error messages and cmdline stuff right?

**Comment by siduck** [comment]
if yes, then cant it just load at events like cmdlineEnter? i doubt if there's an event that gets triggered whenever messages are printed in the cmdline

**Comment by anstadnik** [comment]
I believe that it forwards everything to https://github.com/rcarriga/nvim-notify
https://github.com/folke/noice.nvim/blob/27adc00728261a4368206105b4bc1b4a6fb196f8/lua/noice/config/init.lua#L88-L90

**Comment by siduck** [comment]
hmm, then can you just put `vim.notify = require("noice").notify` in your custom lspconfig?

**Comment by anstadnik** [comment]
Oh that's a great idea actually, it solves the current issue, thx!

**Comment by siduck** [comment]
also @anstadnik feel free to join any of our communities, you'll get help there in my absence 

![image](https://user-images.githubusercontent.com/59060246/195996761-c4b3f49e-bd55-4632-87e3-4457a3ef69a0.png)
