### ISSUE TITLE
Lazygit strange size

### ISSUE THREAD

**Issue by HayKor** [NvChad/ui#298]
**Describe the bug**
I made a keybinding to open LazyGit in a floating terminal window. When I open the lazygit, it is always 2-3 columns bigger than the float term.

**To Reproduce**
```lua
map({ "n", "t" }, "<A-l>", function()
    require("nvchad.term").toggle {
        pos = "float",
        id = "lazygit",
        cmd = "lazygit",
        float_opts = {
            relative = "editor",
            row = 0,
            col = 0,
            width = 1,
            height = 1,
            border = "single",
        },
    }
end, { desc = "Toggle floating LazyGit window" })
```

**Expected behavior**
It's expected to be all the window size

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/63199429/dbb4508b-a571-42f3-9104-c89aae384722)

![image](https://github.com/NvChad/NvChad/assets/63199429/0706df81-24ec-4e42-9dc2-d1c6c3c6623c)

![image](https://github.com/NvChad/NvChad/assets/63199429/d14e926f-61f2-4000-9846-20d4057170b9)

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 22.04
 - Terminal: kitty
 - Version of Neovim: NVIM v0.10.0

**Comment by siduck** [comment]
its expected, as you copied float opts and the row col is from 0 0  indices... just remove the float_opts, its not needed

**Comment by HayKor** [comment]
## Removed float opts
![image](https://github.com/NvChad/ui/assets/63199429/6cef089b-fba1-4ffe-99bc-989a471f9146)

It's still there) I meant that lazygit window is cut on the left.

It became even worse, cuz default `float_opts` got applied and they are too small

**Comment by siduck** [comment]
> Describe the bug
I made a keybinding to open LazyGit in a floating terminal window. When I open the lazygit, it is always 2-3 columns bigger than the float term.

what do you expect then? you say its bigger than float term which is already small by default :/

**Comment by HayKor** [comment]
I expect it to fit into the float term but it doesn't no matter what size I try

**Comment by siduck** [comment]
because lazygit is a huge tool, it needs larger screensize,  you need to increase the size of the float term

**Comment by siduck** [comment]
please read the open win api of neovim, then you'll understand what are those row/col width stuff

**Comment by HayKor** [comment]
> because lazygit is a huge tool, it needs larger screensize, you need to **increase the size of the float term**

Didn't I? I literally pinned 3 screens of me changing size and seeing absolutely the same result. It doesn't matter what size I make the float term, it's always those 2-3 strange cols

**Comment by siduck** [comment]
then whats wrong with your code? it just looks fullscreen floating window, normal
