### ISSUE TITLE
Terminal width and height settings in chadrc.lua stopped working 

### ISSUE THREAD

**Issue by kolach** [NvChad/ui#299]
I used to set this configuration to control horizontal/vertical terminal width and height in my chadrc.lua :

```
local M = {}

M.ui = {
 term = {
   sizes = { sp = 0.5, vsp = 0.5 }
 },
}

return M
```

But after some recent changes in it stopped working for me. I always have default 0.2 for vertical and 0.3 for horizontal terminal.
Other settings in my chadrc.lua work fine.

I tried clean install and have same issue.

**Comment by siduck** [comment]
hi @kolach , its M.term now.

**Comment by kolach** [comment]
thank you!!!
