### ISSUE TITLE
Is there any way to get just the **tabufline** module as a plugin?

### ISSUE THREAD

**Issue by evertonse** [NvChad/ui#301]
I really wish to install only the tab related plugin because of the buffer per tab feature.
I couldn't find this exact feature anywhere else.
At the same time I don't wanna buy in to the whole NvChad ui.

**Comment by siduck** [comment]
no

**Comment by siduck** [comment]
https://github.com/nanozuki/tabby.nvim
https://github.com/backdround/tabscope.nvim
https://github.com/tiagovla/scope.nvim
