### ISSUE TITLE
How to use as a plugin

### ISSUE THREAD

**Issue by kareemmahlees** [NvChad/ui#302]
## Description
I am using [LazyVim](https://www.lazyvim.org/) for my configuration, but I like the way NvChad styles the completion suggestions so I went off coping and pasting some stuff from [here](https://github.com/NvChad/NvChad/blob/v2.5/lua/nvchad/configs/cmp.lua) to try and get the same styling.
But every time I try  to `require("nvchad")` or `require("nvconfig")` I get the error `module chadrc not found`, although I am getting correct autocompletions for the underlying enums and fields when I try to require either.

Here is how I import `NvChad/ui` ( which is the same as [here](https://github.com/NvChad/NvChad/blob/v2.5/lua/nvchad/plugins/init.lua)) :
```lua
  {
    "NvChad/ui",
    branch = "v2.5",
    lazy = false,
    config = function()
      require("nvchad")
    end,
  },

```
## Stacktrace
<img width="911" alt="image" src="https://github.com/NvChad/ui/assets/89863279/d93c3958-10b7-4a73-9944-3b9775ba16c3">

## Environment info
- LazyVim: v12.21.1
- NeoVim: v.0.10.0
- NvChad/ui: branch v2.5
## Os info
- Windows: 11

**Comment by siduck** [comment]
you need chadrc to be in your path! lua/chadrc.lua. Thats the configuration used over the standard .setup(), due to a variety of reasons

**Comment by siduck** [comment]
and the ui plugin needs base46 as dependency too 

https://gist.github.com/siduck/cc7305db586d512b5fd3f4ea73c9cc81
