### ISSUE TITLE
sign_define is deprecated. 

### ISSUE THREAD

**Issue by awurorawr** [NvChad/ui#303]
sign_define on current nightly (NVIM v0.11.0-nightly+3e6cec0) is deprecated and now is replaced with vim.diagnostic.config

**Comment by siduck** [comment]
@synqqrawr  we only support stable stuff, not nightly, tons of apis are deprecated on nightly, so please use LTS

**Comment by lucario387** [comment]
> @synqqrawr we only support stable stuff, not nightly, tons of apis are deprecated on nightly, so please use LTS

https://neovim.io/doc/user/deprecated.html#_deprecated-features

Btw `sign_define` is depreacated in 0.10 aka stable. Not nightly @siduck

**Comment by siduck** [comment]
Hmm, strange I didn't get any warnings at all

**Comment by siduck** [comment]
![image](https://github.com/NvChad/ui/assets/59060246/9b568dca-c862-4c24-8cd4-bc3dc30c9720)

is this the new way?

**Comment by awurorawr** [comment]
Yes, that should do it.

**Comment by siduck** [comment]
https://github.com/NvChad/ui/commit/c7b11478f4079fdaa6b5395dae08fdfe4c1c1cfe
