### ISSUE TITLE
Theme switcher changes key in the changed_themes table resulting in errors

### ISSUE THREAD

**Issue by tesarlukas** [NvChad/ui#310]
**Describe the bug**

When using starter config and and overrding the theme via the changed_themes in the chadrc.lua, the theme switcher changes currently used theme as well as the key in the changed_themes table. This results in possible errors in config because there are some themes which have dash in their name. For example using rosepine theme and having chadrc.lua file like this:
```
-- This file needs to have same structure as nvconfig.lua
-- https://github.com/NvChad/ui/blob/v2.5/lua/nvconfig.lua

---@type ChadrcConfig
local M = {}

M.ui = {
  theme = "rosepine",
  changed_themes = {
    rosepine = {
      base_16 = {
        base0F = "#ffffff",
      },
    },
  },

  -- hl_override = {
  -- 	Comment = { italic = true },
  -- 	["@comment"] = { italic = true },
  -- },
}

return M
```

and then using theme switcher to change it to material-darker results in this

```
-- This file needs to have same structure as nvconfig.lua
-- https://github.com/NvChad/ui/blob/v2.5/lua/nvconfig.lua

---@type ChadrcConfig
local M = {}

M.ui = {
  theme = "material-darker",
  changed_themes = {
    material-darker = {
      base_16 = {
        base0F = "#ffffff",
      },
    },
  },

  -- hl_override = {
  -- 	Comment = { italic = true },
  -- 	["@comment"] = { italic = true },
  -- },
}

return M
```

which results in this error
```
"~/.config/nvim/lua/chadrc.lua" 23L, 421B written
Error detected while processing BufWritePost Autocommands for "/home/user_name/.config/nvim/lua/chadrc.lua":
Error executing lua callback: vim/loader.lua:0: /home/user_name/.config/nvim/lua/chadrc.lua:10: '}' expected (to close '{' at line 9) near '='
stack traceback:
        [C]: in function 'error'
        vim/loader.lua: in function <vim/loader.lua:0>
        [C]: in function 'require'
        /home/user_name/.local/share/nvim/lazy/ui/lua/nvconfig.lua:89: in main chunk
        [C]: in function 'require'
        /home/user_name/.local/share/nvim/lazy/ui/lua/nvchad/init.lua:2: in main chunk
        [C]: in function 'require'
        /home/user_name/.local/share/nvim/lazy/ui/lua/nvchad/utils.lua:61: in function 'reload'
        /home/user_name/.local/share/nvim/lazy/ui/lua/nvchad/au.lua:55: in function </home/user_name/.local/share/nvim/lazy/ui/lua/nvchad/au.lua:50>
```

**To Reproduce**
1. clone the starter config
2. set theme without the dash
2. use theme switcher to set the the theme with the dash

**Expected behavior**
Juding from possible key `all` in the changed_themes table I'd expect it to not change the keys when switching the theme.

**Desktop (please complete the following information):**
 - Operating System
 EndeavourOS Linux x86_64 (6.6.38-1-lts)
 
 - Terminal
alacritty 0.13.2 (bb8ea18e)
(with tmux and zsh)

 - Version of Neovim
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1720049189

edit:
I hope this is a correct repo because while it does happen with the starter configuration, I assumed the problematic logic behind it is in this repo.

**Comment by siduck** [comment]
for now just move changed_themes table into another file, i'll fix this tomorrow

**Comment by siduck** [comment]
try lazy sync & reopen nvim and check

**Comment by tesarlukas** [comment]
Working perfectly, thanks a lot.
