### ISSUE TITLE
Statusline should show the current pwd in nvim-tree rather than what neovim entered in

### ISSUE THREAD

**Issue by SomniaUmbra** [NvChad/ui#311]
When pwd is changed in neovim-tree, the status line should show that directory, instead of the directory neovim entered with.

**Comment by siduck** [comment]
i'll look into this tomorrow, maybe dirchanged event can be handy

**Comment by siduck** [comment]
https://github.com/user-attachments/assets/6c5b7b06-dd05-4c67-8513-b99ccb193ec0

hmm wait, the statusline does show current pwd, when commands like `cd` is run or with nvimtree
