### ISSUE TITLE
buffer appearing in terminal

### ISSUE THREAD

**Issue by KELs7** [NvChad/ui#312]
### Describe the bug
Clicking a deselected tab heading of a buffer when there is a terminal already opened causes the buffer to 

appear in the terminal.

### To Reproduce

1. Open a file with neovim
2. open a horizontal or vertical terminal (`leader<A-h>`/`leader<A-v`)
3. click on the deselected tab heading

### Expected behavior
Expectation is the terminal buffer should remain unchanged. The current buffer should not reappear in the terminal

### Desktop

OS: Linux
Terminal: Alacritty
Version of Neovim: 0.10

https://github.com/user-attachments/assets/b9ae96ea-cd73-40fe-b312-25d98fa5e100

**Comment by LeonardoMor** [comment]
This is not a problem with NvChad. It's a Neovim issue. Take a look at [stickybuff](https://github.com/stevearc/stickybuf.nvim)

**Comment by LeonardoMor** [comment]
> This is not a problem with NvChad. It's a Neovim issue. Take a look at [stickybuff](https://github.com/stevearc/stickybuf.nvim)

It seems this was fixed in Neovim itself. See [here](https://github.com/neovim/neovim/issues/12517). Not sure how to take advantage of the fix.

**Comment by KELs7** [comment]
> This is not a problem with NvChad. It's a Neovim issue. Take a look at [stickybuff](https://github.com/stevearc/stickybuf.nvim)

Oh ok thanks

**Comment by KELs7** [comment]
Can [this](https://www.reddit.com/r/neovim/comments/1bbuh3z/big_news_winfixbuf_has_merged_into_neovims_core/?rdt=49459) help?

**Comment by KELs7** [comment]
I am guessing 
```
vim.bo[opts.buf].winfixbuf = true
```
somewhere in [M.display](https://github.com/NvChad/ui/blob/7edd4819c398f5557e62ad818b559e0a0239a0de/lua/nvchad/term/init.lua#L54) can fix it.
Can someone test for me? I don't know how to work with nvchad locally. `term` plugin is a binary in `base64` folder.

**Comment by siduck** [comment]
@KELs7  to make changes locally you can do this 

![image](https://github.com/user-attachments/assets/8bf19a58-8cf9-4fb9-a07b-e1c86f7606f1)
and in your plugins table

```lua
{  "NvChad/ui", dev = true }
```
```bash
git clone https://github.com/NvChad/ui/ ~/projects/ui
```

**Comment by KELs7** [comment]
@siduck thank you for the direction

**Comment by KELs7** [comment]
![image](https://github.com/user-attachments/assets/6855d18e-9310-46d4-9a90-d121aed0c783)
Using `vim.wo[win].winfixbuf = true` fixes it.
placed it below this [line](https://github.com/NvChad/ui/blob/7edd4819c398f5557e62ad818b559e0a0239a0de/lua/nvchad/term/init.lua#L84)

**Comment by KELs7** [comment]
Probably there should be a way to avoid showing that error message and also having to press continue

**Comment by KELs7** [comment]
That error is coming from `tabufline/module` on this [line](https://github.com/NvChad/ui/blob/7edd4819c398f5557e62ad818b559e0a0239a0de/lua/nvchad/tabufline/modules.lua#L16)

**Comment by siduck** [comment]
@KELs7 thanks for your effort! wait, for a day or two i'll try to do this without winfixbuf

**Comment by siduck** [comment]
```lua
M.term = {
  winopts = { winfixbuf = true },
}
```

seems like winfixbuf is the only way @KELs7 , just add the above code in your chadrc!

**Comment by KELs7** [comment]
> ```lua
> M.term = {
>   winopts = { winfixbuf = true },
> }
> ```
> 
> seems like winfixbuf is the only way @KELs7 , just add the above code in your chadrc!

Thanks! But you forgot to add that you have to remove the `dev` property  from `{  "NvChad/ui", dev = true }` in `~/.config/nvim/init.lua` . It was producing errors

**Comment by siduck** [comment]
obviously @KELs7 , that change was temporary and only for testing!
