### ISSUE TITLE
Cursor jumps to lsp.signature

### ISSUE THREAD

**Issue by GArecoT** [NvChad/ui#315]
Cursor jumps to lsp.signature when typing on insert mode. This seems to happen with vue files.

https://github.com/user-attachments/assets/cfa890a8-d48e-4402-84d1-789b9d20dfdf

Reverting to commit 6381d40 fix the issue.

https://github.com/user-attachments/assets/772a59a7-806e-4a4b-b32e-505752d7fdd1

My dotfiles: https://github.com/GArecoT/dotfiles/tree/nvim_v2.0/nvim

**Comment by siduck** [comment]
weird, that commit has nothing to do with signature module

**Comment by GArecoT** [comment]
oh, that commit is one commit behind commit 8af9231 (lsp.signature: rm un-needed border config). The bug started to happen on 8af9231

**Comment by GArecoT** [comment]
Adding back focusable=false seems to fix the issue. Created a PR here: https://github.com/NvChad/ui/pull/316
