### ISSUE TITLE
Not an editor command: MasonInstallAll

### ISSUE THREAD

**Issue by SavingBigHead** [NvChad/ui#322]
When I re-downloaded nvim, run `:MasonInstallAll` command after lazy.nvim finishes downloading plugins. The following error occurred:
```
Not an editor command: MasonInstallAll
```

![image](https://github.com/user-attachments/assets/57d5bc1a-21da-4a15-8327-d4156f3c809b)

Then I run `:lazy sync`, and it says ui build failed

![471b9c44ca6ceb4ce370d27ae3838cb8](https://github.com/user-attachments/assets/73224b0e-4c15-41ab-833d-6c8e53171c4d)

Then I close nvim, reopen it and run `:lazy sync` again, and it says ui already up to data, but it still gives an error: `Not an editor command: MasonInstallAll`

![616d80fddb179f088b2279c3a75bc855](https://github.com/user-attachments/assets/98a9f6e7-80b1-4621-ae8b-19620e682205)

我的nvim配置是：https://github.com/SavingHeaume/NvimBasedOnNvchad.git

**Comment by siduck** [comment]
https://github.com/user-attachments/assets/44464343-813b-45e7-a34c-8d8f74315b7d

unable to reproduce. probably your lazylock pulled old commit  of ui plugin

**Comment by SavingBigHead** [comment]
I found the reason, it conflicts with jay-babu/mason-nvim-dap.nvim

**Comment by siduck** [comment]
@SavingHeaume  currently i added support for getting mason pkg names from lspconfig, nvim-lint, conform.

idk use dap so maybe someone else can add its support too!
