### ISSUE TITLE
Toggle dark/light theme bttn not working propperly

### ISSUE THREAD

**Issue by n6v26r** [NvChad/ui#325]
Hey! The toggle theme switch checks for the default in base46, not ui.

So if have something like:
```{lua}
M.ui = {
  theme_toggle = { "catppuccin", "github_light" },
  theme = "catppuccin"
}
```
The toggle button will give:
```Set your current theme to one of those mentioned in the theme_toggle table (chadrc)```
Even if it's set.
Idk if this is intentional to use base46, but the documentation shows M.ui as example

Either way, even if I modify M.base46, I can no longer update the default theme from the theme picker.

**Comment by n6v26r** [comment]
Ok. I saw now that the change is intentional.

**Comment by siduck** [comment]
@n6v26r  yes M.ui is the 1st fallback, but you can add in M.base46 too
