### ISSUE TITLE
Make lsp signature help on insert message silent

### ISSUE THREAD

**Issue by n6v26r** [NvChad/ui#326]
Right now, any time i type a keyword and (), I get the message: ```No signature help available```
Could it be changed so it can be made silent?

**Comment by n6v26r** [comment]
Oh, just saw his guy did a pr: https://github.com/NvChad/ui/pull/318
Could this be approved?

**Comment by siduck** [comment]
@n6v26r that PR adds other code too, i'll try tomorrow

**Comment by siduck** [comment]
@n6v26r  done!
