### ISSUE TITLE
Statusline - lsp_msg and lsp icons not showing

### ISSUE THREAD

**Issue by carried-away** [NvChad/ui#327]
Hello,

After the 2.5 update, the lsp_msg module do not load in statusline

![image](https://github.com/user-attachments/assets/ed59f035-959b-461e-a0f4-718ff3b929d0)

I checked the updated UI docs, and I understand where the override is

https://github.com/NvChad/NvChad/blob/6833c60694a626615911e379d201dd723511546d/lua/nvconfig.lua#L22

As I understand it, all of the modules load with default orders

https://github.com/NvChad/ui/blob/v2.5/lua/nvchad/stl/utils.lua#L13

I toggled default and vscode just to make sure it responded to the override in chadrc.lua, and it did. But the LSP modules never load. When I check LSPInfo(), I do see the C lsp client attached. And I do get LSP help in the file.

Is there a way I can check whats going on with the module  orders table for statusline?

**Comment by siduck** [comment]
update neovim to 0.10
