### ISSUE TITLE
Terminal output flows outside of Term window

### ISSUE THREAD

**Issue by fishBone000** [NvChad/ui#332]
NvChad: v2.5
zsh: 5.9
alacritty: 0.13.2
Using default Term config

Try hold down any key inside Term, for example "j", then notice the "jjjjjj" will gradually grow to the right side of Term, then overflows. 
![Screenshot_20240904_072817](https://github.com/user-attachments/assets/849a53d7-d65c-47bd-9918-1c3556c5437c)
![Screenshot_20240904_072831](https://github.com/user-attachments/assets/f3991509-f4e5-4cd0-b218-cdd74c925a79)
![Screenshot_20240904_072849](https://github.com/user-attachments/assets/034aa0d9-3bcd-40da-8ae8-d8bb8f494dca)
The "62m" is actually "62ms", which indicates how long did last command cost. It's affected by the overflow issue, so the "s" is missing.

**Comment by siduck** [comment]
increase the floating window size?

**Comment by fishBone000** [comment]
I don't think it's working?
I tried to increase the width to 0.6, the width increases but overflow still happens.  
If I'm right it's a regression, I remember on last version the term works just fine.

**Comment by siduck** [comment]
does it happen on non float terms?

**Comment by fishBone000** [comment]
Yes, floating, horizontal and vertical.  
All of them overflows 2 characters.  
This doesn't happen to you?

**Comment by siduck** [comment]
i dont type such long commands, and my shell will just keep it in  1 line

![image](https://github.com/user-attachments/assets/9bf1057a-7532-4087-b92e-a1f934388c6d)

**Comment by fishBone000** [comment]
In one line? Even if you hold "f" long enough?  
I don't type such long command neither, actually I found it out by the "62m", it should be "62ms" so I know it overflowed.

**Comment by siduck** [comment]
> In one line? Even if you hold "f" long enough?

yes

i think its your shell prompt issue

**Comment by fishBone000** [comment]
Hmm wait. 

By my understandings, in regular terminals (alacritty, Konsole e.t.c., not Term), those "fffffff" will get truncated and appears as multiple lines if it gets too long. I think it happens to you right?

And in Term, "ffffff" gets truncated to new lines too, it's just that on my end it overflows 2 character. 

> and my shell will just keep it in 1 line

Does it happen to Term only or regular terminals too?

I think I will do more research.

**Comment by siduck** [comment]
yes mine gets trunacated too! 

try in :term , if issue happens there too then i cant do nothing about it

**Comment by fishBone000** [comment]
No it doesn't happen in `:term`.

Plus I found that it gets itself fixed if I unmaximize and maximize my alacritty.
I can guess there might be a resize event that somehow gets the Term size parameters or whatever right?

**Comment by siduck** [comment]
use :term and resize your terminal window to small

Also you can message in our discord/matrix server, i'm more active there than here

**Comment by fishBone000** [comment]
Sure, will join discord after I have some food

**Comment by siduck** [comment]
> Sure, will join discord after I have some food

you can join the matrix server if you care about FOSS and all :grin:  . or telegram, all 3 are bridged! :rocket:

**Comment by fishBone000** [comment]
Sure, will try Matrix

**Comment by drcrees** [comment]
I'm facing this exact issue, was there a fix?

**Comment by fishBone000** [comment]
> I'm facing this exact issue, was there a fix?

There's not for now...
Me and @siduck discussed about it on Matrix, but didn't come to a conclusion. I tried to research a bit more on my own, but I have no clue...

**Comment by drcrees** [comment]
I was able to work around the issue by setting `opts.style="minimal"` when opening the floating window.

**Update:**
More specifically, this is resolvable by setting `signcolumn = "auto"` in `winopts`. This will fix both float and split terminals.

```
winopts = {  signcolumn = "auto" }
```

**Comment by fishBone000** [comment]
@drcrees how did you find this solution? It's working!

**Comment by drcrees** [comment]
@fishBone000 I just got lucky messing around with the `nvchad.term` Lua and reading Neovim API docs.

https://neovim.io/doc/user/api.html#_floating-windows

^ that bit of documentation led me to try `opts.style="minimal"` which worked for floating terminals, but not split.

So I looked further into what `style` did and I was able to narrow it down to the specific option.

> style: (optional) Configure the appearance of the window. Currently only supports one value:
"minimal" Nvim will display the window with many UI options disabled. This is useful when displaying a temporary float where the text should not be edited. Disables ['number'](https://neovim.io/doc/user/options.html#'number'), ['relativenumber'](https://neovim.io/doc/user/options.html#'relativenumber'), ['cursorline'](https://neovim.io/doc/user/options.html#'cursorline'), ['cursorcolumn'](https://neovim.io/doc/user/options.html#'cursorcolumn'), ['foldcolumn'](https://neovim.io/doc/user/options.html#'foldcolumn'), ['spell'](https://neovim.io/doc/user/options.html#'spell') and ['list'](https://neovim.io/doc/user/options.html#'list') options. ['signcolumn'](https://neovim.io/doc/user/options.html#'signcolumn') is changed to auto and ['colorcolumn'](https://neovim.io/doc/user/options.html#'colorcolumn') is cleared. ['statuscolumn'](https://neovim.io/doc/user/options.html#'statuscolumn') is changed to empty. The end-of-buffer region is hidden by setting eob flag of ['fillchars'](https://neovim.io/doc/user/options.html#'fillchars') to a space char, and clearing the [hl-EndOfBuffer](https://neovim.io/doc/user/syntax.html#hl-EndOfBuffer) region in ['winhighlight'](https://neovim.io/doc/user/options.html#'winhighlight').

**Comment by fishBone000** [comment]
> @fishBone000 I just got lucky messing around with the `nvchad.term` Lua and reading Neovim API docs.
> 
> https://neovim.io/doc/user/api.html#_floating-windows
> 
> ^ that bit of documentation led me to try `opts.style="minimal"` which worked for floating terminals, but not split.
> 
> So I looked further into what `style` did and I was able to narrow it down to the specific option.
> 
> > style: (optional) Configure the appearance of the window. Currently only supports one value:
> > "minimal" Nvim will display the window with many UI options disabled. This is useful when displaying a temporary float where the text should not be edited. Disables ['number'](https://neovim.io/doc/user/options.html#'number'), ['relativenumber'](https://neovim.io/doc/user/options.html#'relativenumber'), ['cursorline'](https://neovim.io/doc/user/options.html#'cursorline'), ['cursorcolumn'](https://neovim.io/doc/user/options.html#'cursorcolumn'), ['foldcolumn'](https://neovim.io/doc/user/options.html#'foldcolumn'), ['spell'](https://neovim.io/doc/user/options.html#'spell') and ['list'](https://neovim.io/doc/user/options.html#'list') options. ['signcolumn'](https://neovim.io/doc/user/options.html#'signcolumn') is changed to auto and ['colorcolumn'](https://neovim.io/doc/user/options.html#'colorcolumn') is cleared. ['statuscolumn'](https://neovim.io/doc/user/options.html#'statuscolumn') is changed to empty. The end-of-buffer region is hidden by setting eob flag of ['fillchars'](https://neovim.io/doc/user/options.html#'fillchars') to a space char, and clearing the [hl-EndOfBuffer](https://neovim.io/doc/user/syntax.html#hl-EndOfBuffer) region in ['winhighlight'](https://neovim.io/doc/user/options.html#'winhighlight').

Coool, i thought nvim calculated the terminal dimension incorrectly

You did well!
