### ISSUE TITLE
Remove treeOffset from Tabufline

### ISSUE THREAD

**Issue by idr4n** [NvChad/ui#333]
Hi,

I use Nvin-tree in floating mode only, therefore, I removed the `treeOffset` module from the `order` table, which was working for me:

```lua
M.ui = {
  tabufline = {
    enabled = true,
    lazyload = false,
    order = { "buffers", "tabs", "btns" },
  },
}
```

However, recently, I noticed that doing so duplicates the `btns` module:

![CleanShot 2024-09-06 at 09 45 56@2x](https://github.com/user-attachments/assets/07aa0332-b2bf-4992-be4d-9a0e41578ab0)

If I change the config to something like this, it does work as expected:

```lua
M.ui = {
  tabufline = {
    enabled = true,
    lazyload = false,
    order = { "offset", "buffers", "tabs", "btns" },
    modules = {
      offset = function()
        return ""
      end,
    },
  },
}
```

I just want to confirm if this is the expected behavior and the way to remove the `offset` module. As mentioned above, just `order = { "buffers", "tabs", "btns" }` was working for me before.

Thanks in advance!

**Comment by siduck** [comment]
![image](https://github.com/user-attachments/assets/3e708592-f68a-4884-bc3d-26fad520270f)
unable to reproduce

**Comment by idr4n** [comment]
Thanks for letting me know. I will explore on my end why this is happening then. Haven't found a reason why, but will keep looking.

**Comment by idr4n** [comment]
Actually, it started happening after the last nightly Nvim update. I rolled back to Aug-31 nighlty version, and then it does work as expected. So to reproduce you would have to be in the latest nightly.

**Comment by siduck** [comment]
interesting, i'll test in few hours

**Comment by siduck** [comment]
looks like `vim.tbl_deep_extend` has changed in nightly :(


![image](https://github.com/user-attachments/assets/2a2aaf7c-f058-48bf-9e23-6a350a66c8e3)

**Comment by idr4n** [comment]
Thanks for letting me know. Looks like the discussion is going on, and you guys are pushing to revert the commit and get the old behavior back.

**Comment by siduck** [comment]
yes its reverted
