### ISSUE TITLE
[Question] Tab styles 

### ISSUE THREAD

**Issue by konstantin-mohin** [NvChad/ui#336]
hi, 

is it possible to to style tabs ? 
also they are small, is it possible to increase their height ?
![Screenshot 2024-09-11 at 23 33 50](https://github.com/user-attachments/assets/45f294b1-429f-48c3-bc54-e2e3e178e4bd)

**Comment by siduck** [comment]
cant increase height, the screenshot you showed is of 1 line too, like ours.

no, not possible to style tabs like that as of now.

**Comment by konstantin-mohin** [comment]
@siduck hi, 
mb possible to remove `X` from tabs together with languages prefix ? (so it will be only filename and its extension)

**Comment by siduck** [comment]
@konstantin-mohin  not possible as of now :fearful:
