### ISSUE TITLE
Add 'neovim-plugin' as topic to the GitHub repository

### ISSUE THREAD

**Issue by Frestein** [NvChad/ui#341]
I would like to request the addition of the 'neovim-plugin' tag to this repository. This tag is necessary for the plugin to be listed on [dotfyle.com](https://dotfyle.com/), which is a valuable resource for Neovim users.
Please consider adding the appropriate tag to this repository and all other new plugins.

Congratulations on v3.0! Thank you!

![image](https://github.com/user-attachments/assets/816c0f09-59db-4589-99f3-8a171134864f)

**Comment by siduck** [comment]
done!

**Comment by Frestein** [comment]
> done!

Thanks! Could you also add this for [minty](https://github.com/NvChad/minty), [menu](https://github.com/NvChad/menu) and [base46](https://github.com/NvChad/base46)?
