### ISSUE TITLE
Enable/Disable specific UIs

### ISSUE THREAD

**Issue by blazkowolf** [NvChad/ui#343]
I noticed `tabufline` has the helpful option to disable it like so.

```lua
M.ui = {
  tabufline = { enabled = false },
}
```

I couldn't find the same option for the other UI integrations. Is there an alternative method for disabling the UIs I don't want to use?

I love this plugin for its beautiful UI, but I'd like to disable the ones I don't want to use so they don't conflict with custom configuration that I have.

Thanks in advance for any info, and thanks for the great work!

**Comment by siduck** [comment]
which ones ?

statusline can be disabled by just `vim.o.stl =""` , in the config function of UI plugin

**Comment by blazkowolf** [comment]
@siduck statusline is the main one I'd like to disable from this plugin because I prefer the vanilla Neovim statusline. I'll try your suggestion when I'm at my computer - Thanks!

**Comment by idr4n** [comment]
Hi @siduck. I have been using lualine in my own config and wanted to see how it fits with Nvchad. I did what you suggested above, that is, added this to `lua/plugins/init.lua`:

```lua
  {
    "nvchad/ui",
    config = function()
      require "nvchad"
      vim.o.stl = ""
    end,
  },
```

This works overall with regular buffers, but the lualine extensions do not show for special buffers such as lazy, mason, NvimTree, etc. It just shows a blank statusline (the extensions are supposed to show some different info or statusline in those buffers)

**Comment by siduck** [comment]
@idr4n @blazkowolf  try the new change!

**Comment by siduck** [comment]
```lua
M.ui = {
    statusline = { enabled = false }
}
```

**Comment by idr4n** [comment]
Thanks @siduck, the `enabled` options for statusline is nice to have. I tried already and it works as expected, also with lualine extensions.

Thanks again!
