### ISSUE TITLE
Recent UI Update is Broken

### ISSUE THREAD

**Issue by DJPoland** [NvChad/ui#344]
Recently updated my packages with Lazy, and now the new theme picker breaks when hitting enter. Photo attached:

![Screenshot 2024-10-02 at 11 01 33 PM](https://github.com/user-attachments/assets/0d98fe3f-b856-4e20-b6b0-1f24bb651a59)

chadrc.lua no longer updates to the new chosen theme.

**Comment by siduck** [comment]
please move your theme  related options to M.base46...

**Comment by siduck** [comment]
that change was announced in july 

https://github.com/NvChad/NvChad/issues/2938

**Comment by DJPoland** [comment]
ah, that resolved my issue. Ty.
