### ISSUE TITLE
NvChad Error after open vertical window buffer Control + v

### ISSUE THREAD

**Issue by siduck** [NvChad/ui#345]
### Discussed in https://github.com/NvChad/NvChad/discussions/3011

<div type='discussions-op-text'>

<sup>Originally posted by **hajirasyafi** October  3, 2024</sup>
this Error happened after open new buffer vertical window (control + v)

```sh
Error executing vim.schedule lua callback: ...local/share/nvim/lazy/ui/lua/nvchad/colorify/methods.lua:68: Invalid 'col': out of range
stack traceback:
        [C]: in function 'set_extmark'
        ...local/share/nvim/lazy/ui/lua/nvchad/colorify/methods.lua:68: in function 'handler'
        .../neovim/0.10.0/share/nvim/runtime/lua/vim/lsp/client.lua:685: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

<img width="1163" alt="Screenshot 2024-10-03 at 12 46 23" src="https://github.com/user-attachments/assets/a7811d15-e7c7-4d90-bd59-117537a4e7b1">

please help</div>

**Comment by siduck** [comment]
```lua
M.colorify = {
  mode = "bg"
  }
```
  
   @hajirasyafi for now put that in your chadrc, can you show a video of the issue? i cant reproduce

**Comment by hajirasyafi** [comment]
This is the video, I will try your config


https://github.com/user-attachments/assets/2cf28aa3-cdb4-4086-896c-adc6846481a5

thats Error show after i press control + v

**Comment by hajirasyafi** [comment]
> ```lua
> M.colorify = {
>   mode = "bg"
>   }
> ```
> 
> @hajirasyafi for now put that in your chadrc, can you show a video of the issue? i cant reproduce

I've try this one, but the Error still appear

**Comment by siduck** [comment]
you got tailwindcss?

**Comment by hajirasyafi** [comment]
yes, the class colored

**Comment by siduck** [comment]
good, i'm able to reproduce this, debugging!

**Comment by siduck** [comment]
@hajirasyafi  should be fixed now

**Comment by hajirasyafi** [comment]
Thankyou
