### ISSUE TITLE
Header scaling issue causes terminal command history and line numbers display problems nvchad 3.0v

### ISSUE THREAD

**Issue by YaroslavTheOmen** [NvChad/ui#346]
If you crop parts of the header (by making the window smaller than the header), it stops scaling. -> Entering a command causes line numbers to appear. -> After quitting out of nvim, some terminal commands (or the entire history) may disappear, and a new line number may appear.

- Turning off the header resolves the problem

https://github.com/user-attachments/assets/5337d8f0-5284-48a4-bcf5-8bea950f5d71

**Comment by siduck** [comment]
fixed
