### ISSUE TITLE
E5108: Error executing lua: ....ui/lua/nvchad/themes/mappings.lua:81: attempt to index field 'base46' (a nil value)

### ISSUE THREAD

**Issue by kraken-afk** [NvChad/ui#350]
I think someone messing up with base46, and suddenly everything broke. There's an error when I try to change the theme, and my UI configuration isn't loaded.
![image](https://github.com/user-attachments/assets/cb599a2b-a91d-4249-a12e-1d42ccd77fe2)
![image](https://github.com/user-attachments/assets/c2d6ae3a-24d1-4c9e-ab04-ebc4d47621d1)

**Comment by siduck** [comment]
please move your theme related options to M.base46
