### ISSUE TITLE
Colorify issue with UnoCSS

### ISSUE THREAD

**Issue by raggesilver** [NvChad/ui#353]
The colorify plugin throws errors constantly when using any sort of color provided by UnoCSS (I have an lsp for Uno).

As I edit or scroll the buffer it throws this error repeatedly:

```
Error executing vim.schedule lua callback: ...local/share/nvim/lazy/ui/lua/nvchad/colorify/methods.lua:51: attempt to perform arithmetic on local 'r' (a nil value)                                 
stack traceback:                                                                                                                                                                                    
        ...local/share/nvim/lazy/ui/lua/nvchad/colorify/methods.lua:51: in function 'handler'                                                                                                       
        ...m/HEAD-0a0962a/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''                                                                                                             
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Version**: just ran `Lazy sync`, still broken

> I am on v3.0 and have only tested this error on Vue files. All TS languages have been installed.
>
> This error is only thrown when there are colors/color related classes in a document.

**Comment by siduck** [comment]
unable to reproduce , can you show a video?

![image](https://github.com/user-attachments/assets/786ef305-db55-4e91-b698-815f539e097b)

**Comment by siduck** [comment]
update your unocss lsp version
