### ISSUE TITLE
Switching default branch to v3.0 breaks NvChad v2.5 installs

### ISSUE THREAD

**Issue by endoze** [NvChad/ui#356]
Currently any installation of NvChad on v2.5 who updates their plugins will get the v3.0 branch of the ui plugin. I believe in order to fix this, you should swap the default branch back to 2.5 and update the NvChad plugin list on v2.5 branch to pin the ui plugin to v2.5 as well. Otherwise the ui plugin doesn't work correctly with NvChad v2.5 as there are breaking changes for v3.0.

**Comment by siduck** [comment]
v3.0 is the latest and users must only use it, please do lazy sync twice, and it'll get fixed

**Comment by endoze** [comment]
This isn't a problem that can be solved by updating plugins. There are configuration level breaking changes that are included now in v3.0. This means that when updating this plugin, configuration values that previously worked are now not applied correctly.

To be very specific, since you moved the NvDash configuration out of the ui table, my dash stopped working as configured. I had to look across both NvChad and UI repos at recent commits just to determine what changed and how to fix my config.

I guess my expectation was that by staying on NvChad v2.5, I wouldn't need to worry about configuration options changing/breaking when upgrading plugins. From a user perspective after upgrading, things I previously had configured to my preferences now no longer work. I have to dive into commits and look at what was recently changed and determine how to adapt what I was doing to work with how things are changed.

I very much appreciate your hard work on this project and all of the related repositories as they are incredibly useful for having a fantastic Neovim experience. I just hope breaking changes end up being more opt-in in the future versus a simple plugin update breaking setups. If you pin NvChad v2.5 to use UI v2.5 and ensure no breakage, then you can make this breaking change an opt-in one by having users specify they want NvChad v3.0 which pulls in UI v3.0.

**Comment by siduck** [comment]
> To be very specific, since you moved the NvDash configuration out of the ui table, my dash stopped working as configured. I had to look across both NvChad and UI repos at recent commits just to determine what changed and how to fix my config.

https://nvchad.com/news/nvui
