### ISSUE TITLE
Colorify is mentioned twice in README.md

### ISSUE THREAD

**Issue by a-usr** [NvChad/ui#362]
https://github.com/NvChad/ui/blob/f2a10cd525a0a26579e500b1710ffd861b7a49e8/README.md?plain=1#L82-L90

and 

https://github.com/NvChad/ui/blob/f2a10cd525a0a26579e500b1710ffd861b7a49e8/README.md?plain=1#L123-L128

**Comment by siduck** [comment]
removed
