### ISSUE TITLE
Unwanted padding in terminal window

### ISSUE THREAD

**Issue by Nanito111** [NvChad/ui#365]
There is padding inside the terminals window, that trims terminal's content

With padding
![image](https://github.com/user-attachments/assets/1eee9309-0256-4c2a-8fae-00f10a98b35e)
![image](https://github.com/user-attachments/assets/765c82e9-add6-47d5-a7db-3ca664cb9215)

No padding (terminal from `:terminal` command)
![image](https://github.com/user-attachments/assets/667e59e9-984c-4120-a44b-3ac7711d4370)

**Comment by siduck** [comment]
thats the signcolumn, read :h nvui.term and disable signcolumn in winopts

**Comment by Nanito111** [comment]
thanks @siduck

**Comment by Kushal-Chandar** [comment]
Hi @siduck , just wondering why is this not disabled by default. Is there any practical utility?

**Comment by siduck** [comment]
> Hi @siduck , just wondering why is this not disabled by default. Is there any practical utility?

it just looks good, thats why i didnt bother adding scl='no' win opt
