### ISSUE TITLE
colorify not working when split

### ISSUE THREAD

**Issue by baiyuechuu** [NvChad/ui#366]
When i split, colorify not working
![Shot-2024-10-12-190331](https://github.com/user-attachments/assets/4f130d81-1e9d-40d2-9d79-b42bc6b19861)

**Comment by siduck** [comment]
can you show a video so I could reproduce this?

**Comment by baiyuechuu** [comment]
https://github.com/user-attachments/assets/da782b51-f0d8-4dab-b4e3-a63d2ff9254f
