### ISSUE TITLE
Can we customize the glyph on the statusline by configuration?

### ISSUE THREAD

**Issue by yusiwen** [NvChad/ui#368]
I'm using a custom made font merged from multiple fonts including nerd fonts, for my terminal. The glyph limit is 65535 for a font, so I've dropped the material glyphs to comply with this limit. Unfortunately, the statusline is using these material glyphs, such as '\udb80\ude56'.

Can I customize the statusline's folder glyph with another glyph by configuration?

Thanks!

**Comment by siduck** [comment]
it wont be easy, you will have to override each module's function. read `:h nvui.statusline`
