### ISSUE TITLE
Restoring a session opens all previously open buffers in a single overlapping buffer

### ISSUE THREAD

**Issue by charludo** [NvChad/ui#37]
**Describe the bug**
Restoring a session appears to only be opening a single buffer containing the last-editet file. Closing this buffer reveals another buffer, closing this one revelas the previous one, and so on. This also happens with a fresh install / no custom config

**To Reproduce**
1. remove custom config
2. PackerSync to uninstall plugins
3. open nvim, open two arbitrary files in two buffers
5. create a session with `mksession ~/Session.vim`
6. exit nvim
7. reopen nvim
8. `source ~/Session.vim`
9. only the last-opened buffer is displayed.
10. it is also not possible to tab-switch between them
11. close the buffer
12. the other buffer is revelaed
13. exit nvim and reopen again
14. `source ~/Session.vim`, same behaviour
15. run `PackerCompile`
16. interestingly, now both buffers show up

**Expected behavior**
sourcing a session file opens all previous buffers next to each other in the bufferline

**Desktop (please complete the following information):**
 - Arch linux
 - alacritty
 - 0.8.0

**Comment by jtuz** [comment]
@charludo, this is not a NvChad related issue, this is with nvim, and no matter what config are you using, I had the same problem in the past, but this solve my needs:  https://github.com/natecraddock/sessions.nvim

**Comment by siduck** [comment]
@jtuz probably, but if it doesnt happen with other bufferline plugins then we will have to fix our tabufline too

**Comment by charludo** [comment]
> @charludo, this is not a NvChad related issue, this is with nvim, and no matter what config are you using, I had the same problem in the past, but this solve my problems: https://github.com/natecraddock/sessions.nvim

Are you sure? I have done some further testing, and it turns out the buffers are loaded (I can cycle them with e.g. `:bprevious`, and make all of them appear with `:bufdo e`). It seems they simply aren't being displayed until *some* event affects them (cycling, reloading, closing the currently displayed one).

**Comment by charludo** [comment]
> @charludo do the buffers show with bufferline.nvim plugin? ( disable tabufline temporarily for testing )

Yes, they do!

Seeing as everything worked perfectly up until a couple of days ago, I have a hunch this might have been broken in #33?

**Comment by siduck** [comment]
@lll9p watchout out

**Comment by lll9p** [comment]
> @lll9p watchout

Sorry for not replying in time. To identify a buf's validation is complicated and it is difficult to test all situations. I think we need more test on different situations.

For this Issue, I have proposed a PR, please review, thanks!
