### ISSUE TITLE
Error detected while processing LspProgress Autocommands for "begin": 

### ISSUE THREAD

**Issue by JavaHello** [NvChad/ui#371]
```log
Error detected while processing LspProgress Autocommands for "begin":                                                                           
Error executing lua callback: .../.local/share/nvim/lazy/ui/lua/nvchad/stl/utils.lua:170: attempt to concatenate local 'icon' (a nil value)
                                                                                                                                                
stack traceback:                                                                                                                                
        .../.local/share/nvim/lazy/ui/lua/nvchad/stl/utils.lua:170: in function <.../.local/share/nvim/lazy/ui/lua/nvchad/stl/utils.lu
a:164>                                                                                                                                          
        [C]: in function 'nvim_exec_autocmds'                                                                                                   
        /usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:54: in function 'handler'                                                        
        /usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:1007: in function ''                                                               
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by jrc2139** [comment]
occurring here: https://github.com/NvChad/ui/commit/39c7a72e739e2bff8be39024d9710c16fde237b3#diff-eb947c2bdcfd8e75c5ad65b2da39f6dcf4bdd29c8fe7323977bb80381374cb5fR170

**Comment by RenovZ** [comment]
Same error. ChatGPT told me the following code for fixing this.
```lua
local spinners = { "", "󰪞", "󰪟", "󰪠", "󰪢", "󰪣", "󰪤", "󰪥" }
local spinner_w = 100 / #spinners

M.autocmds = function()
  vim.api.nvim_create_autocmd("LspProgress", {
    pattern = { "begin", "end" },
    callback = function(args)
      local data = args.data.params.value
      local progress = ""

      if data.percentage then
        local index = math.floor(data.percentage / spinner_w) + 1
        
        -- Ensure index is within bounds
        if index >= 1 and index <= #spinners then
          local icon = spinners[index]
          progress = icon .. " " .. data.percentage .. "%% "
        end
      end
      
      -- (Handle cases where index is out of bounds, if needed)
      
      -- You can now use 'progress' as needed
    end,
  })
end
```

**Comment by Crescent617** [comment]
```
❯ lua 
Lua 5.4.7  Copyright (C) 1994-2024 Lua.org, PUC-Rio
> a = 0
> if a then
>> print('hhhh')
>> end
hhhh
```
https://github.com/NvChad/ui/commit/04ed330c30b1a34641b638b4f94a6bb08f158c74#diff-eb947c2bdcfd8e75c5ad65b2da39f6dcf4bdd29c8fe7323977bb80381374cb5fL168

still raise error. I found that, 0 is ture in lua.

**Comment by Crescent617** [comment]
maybe it should be `if data.percentage and data.percentage > 0 then`
https://github.com/NvChad/ui/commit/04ed330c30b1a34641b638b4f94a6bb08f158c74#diff-eb947c2bdcfd8e75c5ad65b2da39f6dcf4bdd29c8fe7323977bb80381374cb5fL168

**Comment by jwbrandon** [comment]
this is quite fixed yet @siduck.  imo I would do:
```lua
        local idx = math.max(1, math.floor(data.percentage / 10))
        local icon = spinners[idx]
```
Reason being that `math.floor(data.percentage / 10)` can result in `0` which isn't an index for spinners.

EDIT: PR up, feel free to fix it however though.

**Comment by Crescent617** [comment]
> this is quite fixed yet @siduck.  imo I would do:
> ```lua
>         local idx = math.max(1, math.floor(data.percentage / 10))
>         local icon = spinners[idx]
> ```
> Reason being that `math.floor(data.percentage / 10)` can result in `0` which isn't a index for spinners.

😁 i also prefer this solution.

**Comment by ChangeCaps** [comment]
> > this is quite fixed yet @siduck.  imo I would do:
> > ```lua
> >         local idx = math.max(1, math.floor(data.percentage / 10))
> >         local icon = spinners[idx]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Reason being that `math.floor(data.percentage / 10)` can result in `0` which isn't a index for spinners.
> 
> 😁 i also prefer this solution.

This exact problem is happening to me
