### ISSUE TITLE
issue in Tabufline

### ISSUE THREAD

**Issue by simoonas** [NvChad/ui#373]
The rest of the plugin seems to work perfectly fine, however, upon opening a second buffer, an error pops up:
`...ocal/share/nvim/lazy/ui/lua/nvchad/tabufline/modules.lua:119: in function <...ocal/share/nvim/lazy/ui/lua/nvchad/tabufline/modules.lua:109>`
`E15: Invalid expression: "v:lua.require('nvchad.tabufline.modules')()"`

After adding the tabufline table, the whole plugin's config falls back to default, i.e. all other settings in chadrc.lua don't come in effect

```lua
local M = {}

M.base46 = {
  theme = 'gruvbox'
}

M.ui = {
  statusline = { theme = 'vscode' }
  tabufline = {
    enabled = true,
    lazyload = true,
    order = { "treeOffset", "buffers", "tabs", "btns" },
    modules = nil,
  },
}

return M
```

**Comment by siduck** [comment]
add comma after statusline table

**Comment by simoonas** [comment]
my bad, it's parsed correctly now, however the aforementioned error is still there. I don't think it's related to `chadrc.lua` as it just overrides the default config.

**Comment by obarbier** [comment]
@simonasGit  was facing same issue make sure to install 
	{ "nvim-tree/nvim-web-devicons", lazy = true },
