### ISSUE TITLE
Strange bufferline behaviour when nvimtree is opened

### ISSUE THREAD

**Issue by machinoro** [NvChad/ui#377]
Currently, Im using my own config (which is also heavily based on NvChad) and this UI plugin. However, when I open nvimtree, the bufferline got shifted to the right for some reason. Since I  can not find any solution for this, I think this issue is rather an ask for help than an actual issue? 

![image](https://github.com/user-attachments/assets/754543b2-f92a-4bf6-85bc-4c9f00a56910)

This is my neovim config : https://github.com/mhiuuu/neovim

**Comment by siduck** [comment]
hmm thas not strange, thats for nvimtree offset. Go to your chadrc and change the order of nvimtree offset in tabufline order. Do read `:h nvui.tabufline`

right now the first module in tabufline is the treeoffset so whenever nvimtree is opened, it'll show! but your nvimtree is on the right so change the order
