### ISSUE TITLE
Q: Can the process to upgrade from v2.5 -> v3.0 be properly documented?

### ISSUE THREAD

**Issue by ghost-in-the-zsh** [NvChad/ui#378]
The documentation has the "Install" and "Post Install" sections, both of which assume a new user performing a new installation from scratch. Part of that process includes deleting the `.git` repo dir [after cloning](https://nvchad.com/docs/quickstart/install):

> Delete the `.git` folder from [sic] nvim folder.

From there, we proceed with our personal configs, etc. which, effectively, means we're branching from upstream. Having a section with update/upgrade steps, and so on, would be very helpful.

If the expectation is that users should be nuking their setups and restarting their personal configs from scratch, without any guidance other than sinking time/effort looking through commit messages and/or other code[^1], then I suggest that's not optimal, efficient, or user-friendly. Documenting an update/upgrade process to proactively minimize/solve problems for the user-base would save us a lot of time overall and improve our experience with using the project.

As a note, while this question is focusing on v2.5 -> v3.0, it shouldn't be limited to this instance alone. It should be applicable for future releases, especially since my experience moving up to v2.5 included several backwards-incompatible/breaking changes, it seems the same holds true for moving up to v3.0, and it seems likely future updates (e.g. v3.5 *et. al.*) will do the same. While breaking changes are expected, helping users keep up would be very helpful.

Thanks.

[^1]: This was my experience when I upgraded to v2.5 and [other issues/comments](https://github.com/NvChad/ui/issues/356) suggest a similar problem when trying to upgrade to v3.0, suggesting a better user upgrade process experience would be very beneficial for both users and the project itself.

**Comment by siduck** [comment]
v3.0 is just changes in the UI repo. not the main repo

**Comment by siduck** [comment]
https://nvchad.com/news/nvui#changelog

**Comment by siduck** [comment]
> update/upgrade steps


lazy sync

**Comment by ghost-in-the-zsh** [comment]
I'll give that a try soon and see how it goes. Thanks.

**Comment by ghost-in-the-zsh** [comment]
It seems to have worked. I got the wrong impression from the previously-linked issue seemingly showing that the upgrade was causing problems.

Thanks.

**Comment by siduck** [comment]
btw do check my new plugins, showkeys & timerly!
