### ISSUE TITLE
Extended documentation

### ISSUE THREAD

**Issue by enfantrichedeprime** [NvChad/ui#379]
I'm eternally grateful for this plugin; it's simply stunning.
However, the video tutorial is disorienting, and when following it exactly, even extracting frames to make it easier to view the code, it still didn't work fully.

This is the setup that made everything work for me. I thought I'd share, and if wanted, I can write a full and clear installation guide as documentation.

``` lua
-- /lua/plugins/nvui.lua

return {
  -- Main UI plugin
  {
    "nvchad/ui",
    config = function()
      require("nvchad")
    end,
  },
  -- Theme picker, didn't work unless this was manually added.
  { "nvchad/volt" },

  -- Menu plugin, added this just in case
  { "nvchad/menu" },

  -- colors
  {
    "nvchad/base46",
    lazy = true,
    build = function()
      require("base46").load_all_highlights()
    end,
  },
}
```

The rest of the setup is clear in the video.

```Lua
-- Loading before anything else 
vim.g.base46_cache = vim.fn.stdpath("data") .. "/base46/"

for _, v in ipairs(vim.fn.readdir(vim.g.base46_cache)) do
  dofile(vim.g.base46_cache .. v)
end

-- Or some of these for lazyloading

-- dofile(vim.g.base46_cache .. "defaults")
-- dofile(vim.g.base46_cache .. "syntax")
-- dofile(vim.g.base46_cache .. "treesitter")
-- dofile(vim.g.base46_cache .. "statusline")

```

Once again, this UI is amazing, and your work is immensely appreciated. I might be an idiot and did something wrong on my part. I just thought I'd post this to help others.

**Comment by siduck** [comment]
i added volt to the doc

as for the menu, the UI plugin aint dependent on it so wont add it.
