### ISSUE TITLE
NvDashAscii hl override no longer working

### ISSUE THREAD

**Issue by Pairadux** [NvChad/ui#385]
I have previously adjusted my NvDashAscii hl to be the same color as the footer, in this case, "#f7768e", however, it no longer shows as such, and seems to be reverting to the original color.

```lua
	hl_override = {
		NvDashAscii = { fg = "#f7768e" },
		Comment = { italic = true },
		["@comment"] = { italic = true },
	},
```

this is my hl_override code for reference. I have fully converted my chadrc to UI 3.0, so that is not the issue, as it has been working fine up until a few hours ago.

**Comment by Pairadux** [comment]
tried clearing ~/.local/share/nvim, to see if it was a caching issue, had no effect, have noticed that manually reloading Neovim fixes the issue until I close Neovim and open it again

**Comment by Pairadux** [comment]
![2024-10-28 18-00-44](https://github.com/user-attachments/assets/feaae56f-0c58-4519-b185-1a3c8a9e2e1b)

**Comment by Pairadux** [comment]
I apologize for the extremely slow video, converting it from mkv to gif seems to have slowed it down quite a bit.

**Comment by siduck** [comment]
should be fixed, do lazysync
