### ISSUE TITLE
Add the option to use the tabufline module without showing the bar

### ISSUE THREAD

**Issue by yoplat** [NvChad/ui#386]
I would like to use the functionality of tabufline, mainly close buffer, next and previous buffer without actually seeing the buffer list itself on the top. 
Using the standard way of neovim with bnext and bprev creates some problems but your implementation is much nicer.
Would it be possible? Thanks

**Comment by siduck** [comment]
use `showtabline` option to hide the bar

**Comment by yoplat** [comment]
> use `showtabline` option to hide the bar

I think somewhere in your plugin you re enable it, I can't seem to disable is

**Comment by yoplat** [comment]
> use `showtabline` option to hide the bar

You make an autocmd that activates it if lazyload is true, I made it false and now I can change it normally

**Comment by yoplat** [comment]
> use `showtabline` option to hide the bar

Tried to fix it by putting lazyload to false in the tabufline (I saw you create an autocmd if true that activates it) in chardc and it works but everytime I save it activates again, strange

**Comment by siduck** [comment]
lazyload=false, 
then your logic for showtabline

**Comment by yoplat** [comment]
> lazyload=false, then your logic for showtabline

Yeah but as I said it turns back on when saving files, I don’t know what is causing it

**Comment by siduck** [comment]
hmmm the autocmd is causing it. Ig you should just make some wrapper functions around `bd` . Using tabufline stuff whilst not showing it is out of scope.

**Comment by yoplat** [comment]
> hmmm the autocmd is causing it. Ig you should just make some wrapper functions around `bd` . Using tabufline stuff whilst not showing it is out of scope.

That's fair, thanks anyway

**Comment by siduck** [comment]
> > hmmm the autocmd is causing it. Ig you should just make some wrapper functions around `bd` . Using tabufline stuff whilst not showing it is out of scope.
> 
> That's fair, thanks anyway

just copy from the tabufline utils

**Comment by yoplat** [comment]
> > > hmmm the autocmd is causing it. Ig you should just make some wrapper functions around `bd` . Using tabufline stuff whilst not showing it is out of scope.
> > 
> > 
> > That's fair, thanks anyway
> 
> just copy from the tabufline utils

Yeah I copied the utils file and part of the lazy load file
