### ISSUE TITLE
Make optional vim.notify in lsp.lua

### ISSUE THREAD

**Issue by axdank** [NvChad/ui#39]
Could this section be made optional, as it makes it impossible to use rcarriga/nvim-notify. When trying to implement it in NvChad, it has no effect, and keeps printing messages in console.

By removing this section of code, everything works.

https://github.com/NvChad/ui/blob/63201c01757b60fb23268a4d9e4fbc96a1915e18/lua/nvchad_ui/lsp.lua#L29-L39

with this code there are these problems:

`noise`
![imagen](https://user-images.githubusercontent.com/55039048/201983968-4962eca9-c2bf-4946-90a4-b0db32ed243d.png)

`command line`:
![imagen](https://user-images.githubusercontent.com/55039048/201984650-d5483cba-1d2e-45df-adae-fa1ad81c0097.png)

`With the problem`
![imagen](https://user-images.githubusercontent.com/55039048/201984711-24b1069e-0247-4bb5-b2ae-419fd2b1e5d5.png)

`expected result`
![imagen](https://user-images.githubusercontent.com/55039048/201984906-87033bf2-9e7c-4ad0-895c-eb8c6140fbcd.png)

**Comment by siduck** [comment]
@axdank i'll do it today, thanks for reporting the issue.
