### ISSUE TITLE
Feature request: trigger `ColorScheme` event when changing theme?

### ISSUE THREAD

**Issue by typicode** [NvChad/ui#391]
Hi,

Thanks for NvChad! Would it be possible to trigger `ColorScheme` event when changing theme?

```lua
vim.cmd("doautocmd ColorScheme")
```

**Comment by siduck** [comment]
```lua
autocmd("User", {
  pattern = "NvThemeReload",
  callback = function()
 
  end
})
```

**Comment by siduck** [comment]
![image](https://github.com/user-attachments/assets/dc06efeb-ff31-4964-a493-61cb0a6efdd3)

whenever base46 theme changes

**Comment by siduck** [comment]
![image](https://github.com/user-attachments/assets/062d1d24-cfd8-4345-8202-4fd3949bdd00)

if thats ok then pushing the change

**Comment by typicode** [comment]
Thank you!
