### ISSUE TITLE
Setup nvim-cmp to show lsp import path

### ISSUE THREAD

**Issue by magicalpuffin** [NvChad/ui#393]
After updating plugins, `nvim-cmp` was no longer displaying the import path and file path from lsp. I see that nvchad ui configures the item menu text for `nvim-cmp` but I can't tell how the import paths were added.

Is there a way to configure nvchad to display this? Or is this something caused by other plugins?

**Example of autocomplete with lsp import paths:**
![Screenshot_20241109 before plugin update](https://github.com/user-attachments/assets/5f44510d-a2e4-4a4a-bacf-da722bdd0b16)

**Example of autocomplete with lsp without import paths:**
![Screenshot_20241109 after plugin update](https://github.com/user-attachments/assets/a4ce29c9-7dee-4673-9c47-383a4214e6e5)

**Here are my nvim dot files:**
https://github.com/magicalpuffin/dotfiles/tree/update-all/.config/nvim

## Update:
I think this is a nvchad issue, I have another example branch which tries to just update nvchad.
https://github.com/magicalpuffin/dotfiles/tree/update-nvchad/.config/nvim

**Comment by siduck** [comment]
try another config and see. I dont think i handle import path stuff in our cmp config

**Comment by magicalpuffin** [comment]
I have been messing around and I still have no idea. Tried uninstalling and reinstalling and it still doesn't work.

I'm pretty sure it is related to the config in nvchad and nvchad ui because it shows up when updating those packages. Maybe there is some difference in the format options which is now trimming something?

https://github.com/NvChad/NvChad/blob/5189f3e32c87478632bb471817db1df13f8b16d1/lua/nvchad/configs/cmp.lua#L13

https://github.com/NvChad/ui/blob/b6c237702449792a2d8c495909029fdd59e9781d/lua/nvchad/cmp/init.lua#L9

I also can't seem to override the formatting in `lua/plugins/init.lua`.

```lua
  {
    "hrsh7th/nvim-cmp",
    opts = function()
      local cmp = require "cmp"
      cmp.setup {
        formatting = {
          fields = { "menu", "abbr", "kind" },
          format = function(entry, item)
            item.menu = "testing"
            item.kind = "override"
            return item
          end,
        },
      }
    end,
  },
```

**Comment by siduck** [comment]
try ui 2.5 branch and see

**Comment by siduck** [comment]
clone the ui repo locally and use its v2.5 branch and test

**Comment by magicalpuffin** [comment]
I cloned the v3 branch of ui repo and was able to get it working with this in `lua/nvchad/cmp/init.lua`

```lua
  formatting = {
    format = function(entry, item)
      local icons = require "nvchad.icons.lspkind"
      local icon = icons[item.kind] or ""

      if atom_styled then
        item.menu = cmp_ui.lspkind_text and item.kind or ""
        item.menu_hl_group = "LineNr"
        item.kind = icon
      else
        item.kind = cmp_ui.lspkind_text and icon .. " " .. item.kind or ""
      end

      if not cmp_ui.icons_left then
        item.kind = " " .. item.kind
      end

      if cmp_ui.format_colors.tailwind then
        format_kk.tailwind(entry, item)
      end

      return item
    end,

    fields = fields,
  },
```

The issue was with overriding the `item.menu` when not using atom styles.
https://github.com/NvChad/ui/blob/c59c5fc078cc22a28604e154552c41705359145b/lua/nvchad/cmp/init.lua#L14

In previous versions, the menu would only get replaced when using atom styles.
https://github.com/NvChad/NvChad/blob/5189f3e32c87478632bb471817db1df13f8b16d1/lua/nvchad/configs/cmp.lua#L17

I created https://github.com/NvChad/ui/pull/394 with the changes. I don't use atom styles but the highlighting and autocomplete looks fine for me after the change. Tell me if I need anything else for the PR.

![Screenshot_20241110 after fix attempt](https://github.com/user-attachments/assets/d0299f50-79fa-40b4-a124-59e007bd7809)

**Comment by siduck** [comment]
![image](https://github.com/user-attachments/assets/9ed83284-2926-424c-822b-3f730d182564)

hmm this messes up icon_left feature :thinking:

**Comment by magicalpuffin** [comment]
I updated it to be `if atom_styled or cmp_ui.icons_left`

I still have no idea what the intention of each style is supposed to be.

cmp_style_atom
![image](https://github.com/user-attachments/assets/f21e6d84-eccc-4041-8d0b-bcd9c61401e4)

cmp_ui.icons_left = true
![image](https://github.com/user-attachments/assets/c78d3823-471f-4f13-a90a-93a999d5c5f2)

default
![image](https://github.com/user-attachments/assets/72e6adea-7d9e-499f-9240-5a285231368e)

**Comment by siduck** [comment]
icon_left is only for non atom styles

**Comment by magicalpuffin** [comment]
So does this fix the issue then? The pull request was updated.

**Comment by siduck** [comment]
it works but i'd want this feature on atom styles too. seems like "menu" by default has those paths.

is it not possible to get the default value of item.menu? and then add item.kind to it

**Comment by magicalpuffin** [comment]
It is possible to combine item kind and item menu but it looks bad. Do you want this?

`item.menu = cmp_ui.lspkind_text and item.kind .. " " .. (item.menu or "") or ""`

![image](https://github.com/user-attachments/assets/ec30742c-0e95-4949-87c9-b2b8aeafd0d7)

Again, I don't know what your intention for the styles are. To me, it feels like overriding item.menu with item.kind is a bug. 

It sounds like there are 3 styles, `cmp_style = "atom"`, `cmp_ui.icons_left = true`, and the default style. Each of these styles are mutual exclusive of each other, ex. you would never need to combine atom style with icons left. And only the default style has the default menu.

Based on the original code before I started making changes, menu is supposed to get replaced by item.kind for atom style.
https://github.com/NvChad/NvChad/blob/5189f3e32c87478632bb471817db1df13f8b16d1/lua/nvchad/configs/cmp.lua#L17

**Comment by magicalpuffin** [comment]
I updated my commit to fix the color issue with icons left. This is what it currently looks like

`cmp_style = "atom"`
![image](https://github.com/user-attachments/assets/1a65c34d-87ec-470e-96d5-b9f86260e8fb)

`cmp_ui.icons_left = true`
![image](https://github.com/user-attachments/assets/a96fa96b-3465-42ba-8c38-10ab4d0b5efb)

default
![image](https://github.com/user-attachments/assets/bd46e954-b5a4-48a8-8622-c00a142a4f80)

**Comment by siduck** [comment]
yes it looks bad in atom styled cuz not aligned well so we wont have on it

**Comment by siduck** [comment]
updated the PR
