### ISSUE TITLE
Centering the editor after toggling away from horizontal terminal

### ISSUE THREAD

**Issue by albankurti** [NvChad/ui#402]
Hi,

The problem this is solving is that when we toggle <A-h> the terminal, it pushes the buffers above lines up, which is not bad optically as the new focus is the terminal. However, when we toggle it away again, the buffer above is further pushed up - this becomes an issue. You start looking at the terminal and two clicks away you're in a completely different context in the file.

As a workaround I have added this zz centering such that as soon as the terminal is toggled away the line I was on is centralized.

```
-- Toggle terminal without disrupting the editor
vim.api.nvim_del_keymap("t", "<M-h>")

map({ "n", "t" }, "<A-h>", function()
  require("nvchad.term").toggle { pos = "sp", id = "htoggleTerm" }
  vim.cmd "normal! zz" -- Center the current line
end, { desc = "terminal toggleable horizontal term with centering" })

```

First I think this behavior is better than the current random moving anyways, but ideally there is a way to revert the exact cursor position and vertical position of the buffer, although I am not sure how possible that is and I recognize it can get complicated with multiple buffers. 

Hopefully it's something other users find helpful and I would suggest the zz centering is more intuitive than the current behavior at the very least.

**Comment by siduck** [comment]
can u show a video?

**Comment by albankurti** [comment]
Without the fix:

[Screencast_20241215_155604.webm](https://github.com/user-attachments/assets/8635e029-696d-43e0-a401-e3ca2a2d5bad)

With the fix:

https://github.com/user-attachments/assets/adfc125c-f790-4d7a-a8c2-94a7ed8abd5f

**Comment by siduck** [comment]
https://github.com/user-attachments/assets/f03fd188-a094-43c2-a342-fccceff70fb1

unable to reproduce.

**Comment by siduck** [comment]
try with vanilla nvchad config, i think your config has an issue
