### ISSUE TITLE
File name in status line should be configurable

### ISSUE THREAD

**Issue by rakotomandimby** [NvChad/ui#405]
When working on a project with multiple files with the same name but different paths, such as:
- `foo/bar/index.ts`
- `foo/tuu/index.ts`
- `lorem/ipsum/dolor/index.ts`

Having the just `index.ts` in the statusline is confusing.
In those cases, it is relevant to have either the full path or relative path displayed.

I will propose a configuration and a patch to the code.

Let's discuss the configuration.

I propose that in `chadrc.lua`, we can put this:

```lua
-- This file needs to have same structure as nvconfig.lua 
-- https://github.com/NvChad/ui/blob/v2.5/lua/nvconfig.lua
-- Please read that file to know all available options :( 

---@type ChadrcConfig
local M = {}
M.ui = {
  statusline = {
    filename = "just_filename"
    -- filename = "full_path"
    -- filename = "relative_path"
  }
}
return M
```

And depending on what is the setting, we will display the right information.

The affected piece of code will be https://github.com/NvChad/ui/blob/e0f06a9aa43112e94beca8283516e6804112fb8e/lua/nvchad/stl/utils.lua#L84

```lua
-- ...
M.file = function()
  local icon = "󰈚"
  local path = vim.api.nvim_buf_get_name(M.stbufnr())
  local name = (path == "" and "Empty ") or path:match "([^/\\]+)[/\\]*$"

  if name ~= "Empty " then
    local devicons_present, devicons = pcall(require, "nvim-web-devicons")

    if devicons_present then
      local ft_icon = devicons.get_icon(name)
      icon = (ft_icon ~= nil and ft_icon) or icon
    end
  end
  return { icon, name }
end
-- ...
```

The value of the configuration should be passed to this function.

**Comment by siduck** [comment]
I want to keep the statusline minimal. User can just use overriden_modules

**Comment by rakotomandimby** [comment]
@siduck , please point me to some documentation

**Comment by siduck** [comment]
@rakotomandimby  :h nvui

**Comment by androidStern** [comment]
I ran into this today @rakotomandimby. I'm new to lua and scripting neovim but here's the config i ended up with in case anyone in the future finds it useful. 
```lua
local utils = require "nvchad.stl.utils"

M.ui = {
  statusline = {
    theme = "minimal",
    modules = {
      file = function()
        local x = utils.file()
        local filepath = vim.fn.expand("%:p") -- Full file path
        local parent_dir = vim.fn.fnamemodify(filepath, ":h:t") -- Parent directory name
        local filename = vim.fn.fnamemodify(filepath, ":t") -- File name
        local formatted_name = " " .. parent_dir .. "/" .. filename .. " "

        return "%#StText# " .. x[1] .. formatted_name
      end
    },
  }
}
```

also would welcome a better way to do this

**Comment by rakotomandimby** [comment]
Hello @androidStern , I found how to do it in the documentation.

You may do it in `~/.config/nvim/chadrc.lua`.

- First, you have to give a name to you module: say "stern". 
- Then you have to overwrite the statusline layout by enumerating the elements that will be displayed, and include the "stern" module to the statusline.
- Last, you define what your module will display.

The code below will use the "stern" module to display "Lorem ipsum" between the "mode" and "git" ones:

```lua
M.ui = {
  statusline = {
    default = { "mode", "stern", "git", "%=", "lsp_msg", "%=", "diagnostics", "lsp", "cwd", "cursor" },
    theme = "vscode",
    modules = {
      stern = function()
                return "Lorem ipsum"
      end
    },
  },
}
```

**Comment by geraldzm** [comment]
Full path from getcwd

```lua
M.ui = {
	statusline = {
		theme = "minimal",
		modules = {
			file = function()
				local filepath = vim.fn.expand("%:p") -- Absolute file path
				local root = vim.fn.getcwd() -- Default fallback root

				-- Try to get LSP root_dir if available
				local clients = vim.lsp.get_clients({ bufnr = 0 })
				if #clients > 0 and clients[1].config.root_dir then
					root = clients[1].config.root_dir
				end

				-- Path relative to root
				local rel_path = vim.fn.fnamemodify(filepath, ":." .. root)

				local icon = utils.file()[1]

				return "%#StText# " .. icon .. " " .. rel_path .. " "
			end,
		},
	},
}
```
