### ISSUE TITLE
How do I disable Term?

### ISSUE THREAD

**Issue by shanestillwell** [NvChad/ui#408]
I'm trying to disable `nvterm`, but coming up short. I'd like to completely disable it, esp since I keep accidentally starting one with `<leader>h`.

I've tried `plugins/init.lua`
```
  {
    "NvChad/nvterm",
    enabled = false,
  },
```

I've tried `chadrc.lua`
```
M.ui = {
  term = {
    enabled = false,
  },
```

**Comment by siduck** [comment]
just disable that mapping. ui's term is  only called by mappings, not by default
