### ISSUE TITLE
fzf-lua + tabufline is broken when opened in split and then hid.

### ISSUE THREAD

**Issue by Sreinumder** [NvChad/ui#411]
On [fzf-lua](https://github.com/ibhagwan/fzf-lua)
1. open a finder in split. 
```:FzfLua files wintopts={split = "botright new"}```
2. ```<M-Esc>``` to hide the finder
  ```
      :h fzf-lua
      line 736
      ["<M-Esc>"]     = "hide",     -- hide fzf-lua, `:FzfLua resume` to continue
  ```
  (This already breaks the fzf-lua)
3. fzf resume.
```:FzfLua resume```
(This breaks the Tabufline)

Alternatively,
1. open a finder in split. 
```:FzfLua files wintopts={split = "botright new"}```
2. open the nvcahd split terminal 
```require("nvchad.term").toggle({ pos = "sp", id = "htoggleTerm" })```
also breaks both.

error: 
```
^I...ocal/share/nvim/lazy/ui/lua/nvchad/tabufline/modules.lua:122: in function <...ocal/share/nvim/lazy/ui/lua/nvchad/tabufline/modules.lua:112>
E15: Invalid expression: "v:lua.require('nvchad.tabufline.modules')()"
```

For now i can only use one of them in bottom split.

**Comment by siduck** [comment]
hmm lemme try, share ur fzf-lua setup!

**Comment by siduck** [comment]
https://github.com/user-attachments/assets/5ce0ecaa-1af2-49c3-97ff-a2b537f15d51

**Comment by siduck** [comment]
unable to reproduce

**Comment by Sreinumder** [comment]
I am sorry the first command should have been ```lua require"fzf-lua".files({winopts = { split = "botright new" },})```

This is first bug. It only occurred when fzf-lua is opened in split with the opt ```{winopts = { split = "botright new" },})```
![1](https://github.com/user-attachments/assets/7f822f05-ef89-4a62-826e-eeb12d78dd6e)
1. ```lua require"fzf-lua".files({winopts = { split = "botright new" },})```
2. ``` <M-ESC>```
3. ```:FzfLua resume```


this is second bug it occurred regardless of fzf-lua option.
![2](https://github.com/user-attachments/assets/25e84464-20e6-4dce-9702-d8a2735ee96b)
1. ```lua require"fzf-lua".files({winopts = { split = "botright new" },})```
2. opened toggleterm with this mapping:
```
map({ "n", "t" }, "<A-/>", require("nvchad.term").toggle({ pos = "sp", id = "htoggleTerm" }) end, 
{ desc = "terminal toggleable horizontal term" })
```

**Comment by Sreinumder** [comment]
my current fzf-lua setup
```
{
	-- winopts = { split = "botright new" },              -- this cause error
	winopts = { -- this is floating window setting
		row = 0.9, -- window row position (0=top, 1=bottom)
		col = 0.00, -- window col position (0=left, 1=right),
		height = 0.60, -- window height
		width = 1.00, -- window width
	},
	oldfiles = { include_current_session = true },
	keymap = {
		fzf = {
			["ctrl-q"] = "select-all+accept",
			-- ["<A-r>"] = "<Esc>",
		},
	},
	previewers = {
		builtin = {
			extensions = {
				["png"] = { "viu", "-b" },
				["jpg"] = { "viu" },
			},
			-- ueberzug_scaler = "cover",
		},
	},
}
```

**Comment by siduck** [comment]
:FzfLua  
and then run :Lazy command

this is a weird issue

**Comment by siduck** [comment]
so if fzflua when opened, and then u open a floating window it closes it off instantly

**Comment by siduck** [comment]
happens in lazyvim too. 
![image](https://github.com/user-attachments/assets/9049d053-451e-45ae-b219-0391d04b7756)

So dont open floating window when fzflua is opened, it brings weird bugs

**Comment by siduck** [comment]
as for the tabufline, it breaks because when fzflua is opened, fzflua's buffer is in the vim.t.bufs variable of tabufline
but when its closed then that buffer is still there in the table. weird. 

on bufdelete delete buffers must be removed from vim.t.bufs.I hope fzflua isnt ignoring events :sob:
