### ISSUE TITLE
Tabufline - override 

### ISSUE THREAD

**Issue by carried-away** [NvChad/ui#413]
Hello,

Is it possible to put custom text in a empty tab buffer? Right now it says `No Name` if a new buffer is opened without a file.

I see the `No Name` string is set here in the `style_buf` function

https://github.com/NvChad/ui/blob/912f4064e4fab183f860204e385a21c022f1c886/lua/nvchad/tabufline/utils.lua#L53

I see that the buffer module uses the `style_buf` function 
https://github.com/NvChad/ui/blob/912f4064e4fab183f860204e385a21c022f1c886/lua/nvchad/tabufline/modules.lua#L65

Is it possible to write a function to swap in a string like "foo" for an empty new buffer?

**Comment by siduck** [comment]
dont want to add another opt for this! But i think No Name is a good default, as its there in vanilla nvim too

**Comment by carried-away** [comment]
that's fair, i just wanted to make sure i wasn't overlooking an override.
