### ISSUE TITLE
Change Visual mode hl color

### ISSUE THREAD

**Issue by jfvillablanca** [NvChad/ui#42]
I am not familiar with the nvim option/plugin that highlights the current scope context. From the screenshot below, the div is highlighted since cursor is within the scope.

![Screenshot from 2022-11-23 18-41-21](https://user-images.githubusercontent.com/31008330/203530250-55b3256f-002b-417d-9d55-4b6ca6e807e3.png)

This presents an issue with Visual mode highlight since both colors are indistinguishable from each other. In the example screenshot below, the highlight supposedly starts in "class..." and ends in "... detai".

![Screenshot from 2022-11-23 18-41-41](https://user-images.githubusercontent.com/31008330/203530253-64c3021c-5560-4e9e-a873-1fa1cf4be60e.png)

## Expected behavior
- Deactivate current scope highlighting 
- OR a better alternative is to override Visual mode hl color.

**Comment by siduck** [comment]
@jfvillablanca override Visual highlight group  https://nvchad.com/config/theming

**Comment by jfvillablanca** [comment]
This directory does not exist/was not generated:

`~/.local/share/nvim/site/pack/packer/opt/base46`

I updated and synced packer to check if I'm outdated. Nothing changed.

**Comment by siduck** [comment]
oh my bad, its not opt its start
