### ISSUE TITLE
I want to not show statusline in dap

### ISSUE THREAD

**Issue by j2501987804** [NvChad/ui#44]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem was.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Screenshot**
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/41771911/209045155-b745007e-0621-4ad1-b713-048b029b4619.png">
I want to not display suatusline in a certain type of window, how to set it up

**Comment by siduck** [comment]
@j2501987804 laststatus=2 wont work properly with our statusline

**Comment by siduck** [comment]
so cant help with it

**Comment by siduck** [comment]
```lua
vim.cmd  [[ 
 autocmd FileType dapui* set statusline=\ 
 autocmd FileType dap-repl set statusline=\ 
]]
```

put this into your custom init.lua

**Comment by siduck** [comment]
also it seems like youre using laststatus=2 and the same filenames show up for it! to fix that check this issue https://github.com/NvChad/ui/issues/26#issuecomment-1315947084
