### ISSUE TITLE
Tabufline error

### ISSUE THREAD

**Issue by ternenges** [NvChad/ui#5]
I ran an update today then  i got this 
![bufline erro](https://user-images.githubusercontent.com/102123629/182225037-63faf9da-1da4-4c66-ab39-71449080df46.png)

then this on buffline 
![buffline error2](https://user-images.githubusercontent.com/102123629/182225165-6217f3ac-6b4a-4e9b-bdd7-90a21a00117e.png)

i removed ui folder from plugins intallation path then cloned this [repo](https://github.com/tomasky/nvchad-ui)  to replace it.
now every thing i alright

[ QUESTION ]
is it possible to modify status line icons without modifying the source.

**Comment by JulesNP** [comment]
The same issue was happening to me whenever I saved a file. The suggested workaround solved it for me also.

**Comment by ternenges** [comment]
> I ran an update today then  i got this 
> ![bufline erro](https://user-images.githubusercontent.com/102123629/182225037-63faf9da-1da4-4c66-ab39-71449080df46.png)
> 
> then this on buffline 
> ![buffline error2](https://user-images.githubusercontent.com/102123629/182225165-6217f3ac-6b4a-4e9b-bdd7-90a21a00117e.png)
> 
> i removed ui folder from plugins intallation path then cloned this [repo](https://github.com/tomasky/nvchad-ui)  to replace it.
> now every thing i alright
> 
> [ QUESTION ]
> is it possible to modify status line icons without modifying the source.
> 

I have come to notice that doing this will break down nvchad so I resolved it by adding this field to 

plugins/init.lua  -> 

[NvChad/ui ] = {
...
commit = "6d18c5482b30bbcb02ac20049f2b0b67be9ea164",
...
}


this will will lock to that particular head .

**Comment by siduck** [comment]
ok got the culprit, this is causing it 

```lua
   -- check for same buffer names under different dirs
    for _, value in ipairs(vim.t.bufs) do
      if name == fn.fnamemodify(api.nvim_buf_get_name(value), ":t") and value ~= bufnr then
        name = api.nvim_buf_get_name(bufnr):match "[^/]*/?[^/]*$"
      end
    end
    ```

**Comment by tomasky** [comment]
@siduck  You can adopt my method
and check :messages
why `buflist`  function is called more times if open more files

**Comment by siduck** [comment]
> @siduck You can adopt my method and check :messages why `buflist` function is called more times if open more files

i dont understand your method!!

**Comment by tomasky** [comment]
i said ,you can print the method result first .
the method just   records duplicate values

**Comment by tomasky** [comment]
the reason I wrote it this way, because `bufferflist` function is called more times

**Comment by siduck** [comment]
> i said ,you can print the method result first . the method just records duplicate values

that just prints stuff to the cmdline area

**Comment by tomasky** [comment]
check :messages

**Comment by siduck** [comment]
ok can u provide a git diff of the changes that could be done now

**Comment by tomasky** [comment]
```lua
+    local buf = vim.g.bufnrs[name]
+    if not buf then
+      vim.g.bufnrs[name] = {id = bufnr, num = 0}
+    elseif buf.id ~= bufnr and buf.num == 0 then
+      buf.num = buf.num + 1
+    elseif buf.num > 0 then
+     name = api.nvim_buf_get_name(bufnr):match "[^/]*/?[^/]*$"
+    end
```
```diff
new_cmd("Tbufclose", function()
+  vim.g.bufnrs = {}
   require("core.utils").close_buffer()
 end, {})

```

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/182285058-1697dbc4-0cb0-458f-9785-0f75d8a8145d.png)
![image](https://user-images.githubusercontent.com/59060246/182285042-668a6a09-34a8-4e54-b120-01288a067707.png)

**Comment by tomasky** [comment]
hold on ,i will check that

**Comment by tomasky** [comment]
sorry, forgot init bufnrs table

**Comment by tomasky** [comment]
You can't use vim global here, just use local bufnrs:

```lua
    local buf = bufnrs[name]
    if not buf then
      bufnrs[name] = {id = bufnr, dup = false}
    elseif buf.id ~= bufnr and not buf.dup then
      buf.dup = true
    elseif buf.dup then
     name = api.nvim_buf_get_name(bufnr):match "[^/]*/?[^/]*$"
    end

```

```diff
+local bufnrs = {}
 new_cmd("Tbufclose", function()
+  bufnrs = {}
   require("core.utils").close_buffer()
 end, {})

```

**Comment by siduck** [comment]
ok error is gone but when there's just one buffer, it doesnt update the value

![image](https://user-images.githubusercontent.com/59060246/182288019-ea730a11-54d7-491e-96d7-05d327801aca.png)

**Comment by tomasky** [comment]
i said , map <leader>x to Tbufclose

**Comment by siduck** [comment]
ok done, now the dirname updates only when i cycle through buffer


https://user-images.githubusercontent.com/59060246/182290080-a695b6cc-15bb-4935-b508-e3233f6516ae.mp4

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/182290536-b996d745-c342-4303-9ebb-b993a8981ec0.mp4

look @tomasky

**Comment by tomasky** [comment]
i dont understand your mean ,i just test it by opening the same name files  using nvim-tree,
can you give me your reproduce steps ?

**Comment by tomasky** [comment]
oh ,i got it ,i will check that

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/182292666-969463ba-4bfd-401b-be14-99bb337bc00f.mp4

**Comment by tomasky** [comment]
I already know why that is

**Comment by tomasky** [comment]
i will check why that is

**Comment by siduck** [comment]
> I already know why that is， This is because this `bufferlist` function is only called once, when the file is opened from telescope result list

maybe, then why did my method worked? :thinking:

**Comment by tomasky** [comment]
only such:
```diff
     elseif buf.id ~= bufnr and not buf.dup then
       buf.dup = true
+      name = api.nvim_buf_get_name(bufnr):match "[^/]*/?[^/]*$"
```

**Comment by siduck** [comment]
> ```diff
> name = api.nvim_buf_get_name(bufnr):match "[^/]*/?[^/]*$"
> ```


![image](https://user-images.githubusercontent.com/59060246/182296371-5994f3ea-89ea-4069-81ed-86a2a0346a3a.png)

after going to next buffer
![image](https://user-images.githubusercontent.com/59060246/182296405-8203a5f2-e603-4fb5-b66f-f8f98bc81a0c.png)

**Comment by tomasky** [comment]
i know , why is your method working?

**Comment by siduck** [comment]
> i know , why is your method working?

idk :thinking:

**Comment by tomasky** [comment]
@siduck look this, i open three files ,but print() six `open`  at `bufferlist`, i dont cycle through buffer 
![images](https://user-images.githubusercontent.com/1411118/182313740-dee93042-d230-45c3-b6ea-21ac8fa56f24.png)

**Comment by tomasky** [comment]
@siduck  look this: , i open three files , and print `open` at `bufferlist`  function top,i dont cycle through buffer and dont open telescope

![images](https://user-images.githubusercontent.com/1411118/182315181-4f1993e5-36e4-49ad-8b6f-825e82f35111.png)

**Comment by tomasky** [comment]
And I found the problem that fixed your way， try this:
```diff
    for _, value in ipairs(vim.t.bufs) do
-      if name == fn.fnamemodify(api.nvim_buf_get_name(value), ":t") and value ~= bufnr then
+      if value ~= bufnr and name == fn.fnamemodify(api.nvim_buf_get_name(value), ":t") then
         name = api.nvim_buf_get_name(bufnr):match "[^/]*/?[^/]*$"
+        break
       end
     end

```

**Comment by siduck** [comment]
@tomasky what to do then :thinking:

**Comment by siduck** [comment]
my method isnt that heavy, it will stop looping when the result is found but it breaks whole bufferline when  format on save

**Comment by tomasky** [comment]
no, you need to break foreach , because there may be three of the same file names, i dont know why the bufferlist function is called only once when opening from telescope. if it is called twice ,my method will work

**Comment by siduck** [comment]
> no, you need to break foreach , because there may be three of the same file names, i dont know why the bufferlist function is called only once when opening from telescope. if it is called twice ,my method will work

3 files will still work with my method, try

**Comment by tomasky** [comment]
i know  it works, but you need to break foreach

**Comment by siduck** [comment]
> i know it works, but you need to break foreach

yes we need alternative for it which works

**Comment by tomasky** [comment]
why i cant reproduce the problem of your method?

**Comment by siduck** [comment]
> why i cant reproduce the problem of your method?

add this in your null-ls  setup
```lua
 on_attach = function(client)
    if client.resolved_capabilities.document_formatting then
      vim.cmd "autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()"
    end
  end,
```

**Comment by siduck** [comment]
ok fixed it 
```
 for _, nr in ipairs(vim.t.bufs) do
      if name == fn.fnamemodify(fn.bufname(nr), ":t") and nr ~= bufnr then
        name = fn.bufname(bufnr):match "[^/]*/?[^/]*$"
      end
    end
    ```
    
    i used bufname function instead of api_nvim_get_buf_name

**Comment by tomasky** [comment]
```diff
 for _, nr in ipairs(vim.t.bufs) do
      if name == fn.fnamemodify(fn.bufname(nr), ":t") and nr ~= bufnr then
        name = fn.bufname(bufnr):match "[^/]*/?[^/]*$"
+       break
      end
    end
    ```
```

**Comment by siduck** [comment]
> ```lua
>    for _, value in ipairs(vim.t.bufs) do
>       if name == fn.fnamemodify(api.nvim_buf_get_name(value), ":t") and value ~= bufnr then
>         name = api.nvim_buf_get_name(bufnr):match "[^/]*/?[^/]*$"
>       end
>     end
> ```

yea thats better

**Comment by siduck** [comment]
@tomasky invalid bufname is causing this, whenever formatting lsp stuff does some shady stuff in the background

![image](https://user-images.githubusercontent.com/59060246/182390136-2818cc7e-6ee2-4403-811e-80fdf3ae195c.png)

**Comment by siduck** [comment]
not sure how fn.bufname handles this

**Comment by tomasky** [comment]
my method can work, but needs more refactoring of file tabufline/modules.lua, also because i dont known when the `bufferlist`  is   called

**Comment by tomasky** [comment]
> > my method can work, but needs more refactoring of file tabufline/modules.lua, also because i dont known when is the `bufferlist` called . I am troubled by this problem
> 
> it needs more work, u told me to clear the buf table in tbufclose command but if i close buffers by clicking their close buttons then this wont work cuz they dont use tbufclose command at all, they use the core utils function directly

yea, so  i said , map `<leader>x` to `tbufclose`

**Comment by siduck** [comment]
> > > my method can work, but needs more refactoring of file tabufline/modules.lua, also because i dont known when is the `bufferlist` called . I am troubled by this problem
> > 
> > 
> > it needs more work, u told me to clear the buf table in tbufclose command but if i close buffers by clicking their close buttons then this wont work cuz they dont use tbufclose command at all, they use the core utils function directly
> 
> yea, so i said , map `<leader>x` to `tbufclose`

that will work for current buffer only and those who lazyload tbufline wont have tbufclose command unless tabufline starts

**Comment by siduck** [comment]
any of this works but which is faster?   

```lua
 for _, nr in ipairs(vim.t.bufs) do
      if name == fn.fnamemodify(fn.bufname(nr), ":t") and nr ~= bufnr then
        name = fn.bufname(bufnr):match "[^/]*/?[^/]*$"
         break
      end
    end
    ```
    ```lua
        for _, value in ipairs(vim.t.bufs) do
      if api.nvim_buf_is_valid(value) then
        if name == fn.fnamemodify(api.nvim_buf_get_name(value), ":t") and value ~= bufnr then
          name = api.nvim_buf_get_name(bufnr):match "[^/]*/?[^/]*$"
          break
        end
      end
    end
    ```
    
    @max397574 @tomasky

**Comment by tomasky** [comment]
Why didn't the first one check  `nvim_buf_is_valid`， if the buf not valid , what is   it significance

**Comment by siduck** [comment]
> Why didn't the first one check `nvim_buf_is_valid`， if the buf not valid , what is it significance

i asked someone and he told me that it just returns some empty string

**Comment by tomasky** [comment]
you mean , ` fn.bufname(nr)`  will return empty string if buf not valid

**Comment by tomasky** [comment]
i think the first method should check   `nvim_buf_is_valid` , and its efficiency  should be a litter better

**Comment by siduck** [comment]
> you mean , ` fn.bufname(nr)` will return empty string if buf not valid?

ig so, but that still works

**Comment by tomasky** [comment]
> that will work for current buffer only, if i click other buffer's close btn then it wont work and those who lazyload tbufline wont have tbufclose command unless tabufline starts

you mean , using mouse to click other close button , oh ,i  hadn't thought of that.
if tabufline not starts ,how can we close buf

**Comment by siduck** [comment]
> > that will work for current buffer only, if i click other buffer's close btn then it wont work and those who lazyload tbufline wont have tbufclose command unless tabufline starts
> 
> you mean , using mouse to click other close button , oh ,i hadn't thought of that. if tabufline not starts ,how can we close buf

yea so i'll remove tbufclose command

**Comment by tomasky** [comment]
i sent a pic yesterday,    theme = "gruvbox",
![images](https://user-images.githubusercontent.com/1411118/182066436-ae22952f-8931-46ec-8f48-86777b2c0326.png)

**Comment by siduck** [comment]
> i sent a pic yesterday, theme = "gruvbox", ![images](https://user-images.githubusercontent.com/1411118/182066436-ae22952f-8931-46ec-8f48-86777b2c0326.png)

so this grey text color isnt visible?

![image](https://user-images.githubusercontent.com/59060246/182403027-32ee780b-b627-41eb-8b64-041406c68ec1.png)

**Comment by tomasky** [comment]
It's too dark

**Comment by siduck** [comment]
> It's too dark

packersync and check

**Comment by tomasky** [comment]
The first file name on the left is not legible


![images](https://user-images.githubusercontent.com/1411118/182418813-c493c9f1-120a-42fd-9b87-0d1387732b00.png)

**Comment by siduck** [comment]
> @siduck The first file name on the left is not legible, the name is `vimrc` ,here displays `<mrc (1)`, my nvim-tree is at right side
> 
> ![images](https://user-images.githubusercontent.com/1411118/182418813-c493c9f1-120a-42fd-9b87-0d1387732b00.png)

how many buffers do you have opened? or you shrinked nvim's window size?

**Comment by tomasky** [comment]
no custom configs about tabufline,nvim-tree width=25, open more than four files and nvim-tree
And you should check the input of getchar   ,it may   be inputed others chars like empty 
And should allow to cancel input

**Comment by siduck** [comment]
> no custom configs about tabufline,nvim-tree width=25, open more than four files and nvim-tree And you should check the input of getchar ,it may be inputed others chars like empty And should allow to cancel input

make an issue on the ui repo for this

**Comment by tomasky** [comment]
you still  should check the input of the  tbufpick`s getchar ,it may be inputed others chars like empty And should allow to cancel input
