### ISSUE TITLE
Is it possible to only show tabs in Tabufline?

### ISSUE THREAD

**Issue by foersben** [NvChad/ui#52]
I would like to only see the tabs (with path/partial path/filename) instead of buffers, since I'm used to handling buffers with blindly or by using ":ls" and some key mappings.

Is something like this supported/possible?

**Comment by siduck** [comment]
@foersben not by default, you can however override the default tabufline 
```lua
  ["NvChad/ui"] = {
    override_options = {
      tabufline = {
        overriden_modules = function()
          local tabufline_modules = require "nvchad_ui.tabufline.modules"

          return {
            bufferlist = function()
              return ""
            end,

            buttons = function()
              return "%#TblineFill#%=" .. tabufline_modules.buttons()
            end,
          }
        end,
      },
    },
  }
```

**Comment by siduck** [comment]
it looks like this 
![image](https://user-images.githubusercontent.com/59060246/212443951-3f751fb8-3941-45b3-9725-98669b9c5c4e.png)

**Comment by siduck** [comment]
docs for this https://nvchad.com/config/nvchad_ui

**Comment by siduck** [comment]
"%#TblineFill#%=" 

- %#TblineFill#    is the highlight group related to the tabufline, bg color of it basically
- %= will add empty space
