### ISSUE TITLE
Silence 'No signature help available' message

### ISSUE THREAD

**Issue by vypxl** [NvChad/ui#54]
The automatic signature help is really nice, however, I am constantly reminded that there is no signature help when I type stuff like commas outside of function calls. 

When using [rcarriga/nvim-notify](/rcarriga/nvim-notify), this means there's a big green box every time I type a comma.

In my opinion, the message doesn't provide anything useful (I know there is no help when it doesn't show up).

I did some research on how to silence it:

In [signature.lua](https://github.com/NvChad/ui/blob/main/lua/nvchad_ui/signature.lua#L75), where the signature window is called, options to the nvim signature help provider are passed. Passing `silent = true` disables the message.

```lua
      vim.lsp.with(M.signature_window, {
        border = "single",
        focusable = false,
        silent = true,
      })
```

**Comment by vypxl** [comment]
Another option would be to make it configurable.

I'd be willing to implement that if you don't want to just disable it for everyone

**Comment by jtuz** [comment]
Could you please attach a video to see behavior about the issue?

**Comment by siduck** [comment]
@vypxl PR in v2.0 branch

**Comment by vypxl** [comment]
@jtuz I'm using neovim v0.9.0 nightly on Manjaro Linux 6.0.17 in fish terminal and kitty as a terminal emulator.

Here's a video:
https://asciinema.org/a/wDHMzdL8UhI7PY6f9MUuHL3mi
