### ISSUE TITLE
nvimtree rename error cause tabufline disapper

### ISSUE THREAD

**Issue by Marskey** [NvChad/ui#57]
E5108: Error executing lua: Vim:E15: Invalid expression: v:lua.require('nvchad_ui').statusline()
stack traceback:
        [C]: in function 'input'
        ...ew/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/ui.lua:91: in function 'input'
        ...t/nvim-tree.lua/lua/nvim-tree/actions/fs/rename-file.lua:74: in function 'handle_tree_actions'
        ...ker/opt/nvim-tree.lua/lua/nvim-tree/actions/dispatch.lua:123: in function 'dispatch'
        .../packer/opt/nvim-tree.lua/lua/nvim-tree/actions/init.lua:273: in function <.../packer/opt/nvim-tree.lua/lua/nvim-tree/actions/init.lua:272>
        

1 select a file in nvimtree,then press 'r' to rename a file.
2 ctrl-f enter command-line mode.
3 press ctrl+shift+^ and then the error message came out.
4 modify the name after error occur. press enter to confirm the modify.
5 then tabufline disapear
![Screenshot 2023-02-03 at 09 56 18](https://user-images.githubusercontent.com/13499986/216493166-49112613-e13c-4b43-8321-3fd30ce7b88c.png)

**Comment by siduck** [comment]
@Marskey why ctrl-f to enter command line mode? just press 'r' on file name and then type your filename

**Comment by Marskey** [comment]
for editing more convenient

**Comment by siduck** [comment]
ok I just confirmed it here,  its an issue. Btw it happens when you press Ctrl ^ in normal mode. works fine in insert mode

**Comment by siduck** [comment]
steps to reproduce it without nvchad 

```lua
function ST()
  return vim.o.columns
end

vim.opt.statusline = "%!v:lua.ST()"
```

**Comment by siduck** [comment]
So only ways to fix I can think of is press Ctrl +  ^ when you're in insert mode rather than normal mode
