### ISSUE TITLE
Change color for each item in statusline

### ISSUE THREAD

**Issue by hungnguyen1503** [NvChad/ui#59]
Hi, I'd like to change the color for these items in status line
Could you please support me to set up it?

**Screenshot**
![image](https://user-images.githubusercontent.com/58872428/217838891-c75c8acb-1c6b-4447-9cc7-ac8f3bd9ef87.png)

**Comment by siduck** [comment]
@hungnguyen1503 look at the highlight groups associated with statusline, which is in our base46 repo's integration dir 

then read the docs at nvchad.com related to overriding highlight groups  ( hl_override )

**Comment by hungnguyen1503** [comment]
Thank you for your support. I have set up successfully
