### ISSUE TITLE
When more files are opened, the first file name on the  left of tabufline is not legible

### ISSUE THREAD

**Issue by tomasky** [NvChad/ui#6]
![images](https://user-images.githubusercontent.com/1411118/182418813-c493c9f1-120a-42fd-9b87-0d1387732b00.png)

No custom configs about tabufline,  my nvim-tree is on the right side of window, open more than four files and nvim-tree
the name is `vimrc` ,here displays `<mrc (1)` 

when i open more than six files and  cycle through buffer ,some file name not found

**Comment by siduck** [comment]
can u show full image of tabufline

**Comment by tomasky** [comment]
![images](https://user-images.githubusercontent.com/1411118/183556183-fd1756e9-f206-4f94-9ac0-897f9cebd16b.png)

**Comment by tomasky** [comment]
![images](https://user-images.githubusercontent.com/1411118/183556562-a7a954c1-1d16-407c-9a81-5c66f6e9417e.png)

**Comment by tomasky** [comment]
my terminal is not fullscreen, and when i exec :TbufPick, it displays this, but if i dont bufpick, it is normal

**Comment by siduck** [comment]
how does it look when normal?

**Comment by siduck** [comment]
and whats your screen size?

**Comment by tomasky** [comment]
Display: 15.60 inch, 16:9, 1366 x 768 pixels

**Comment by tomasky** [comment]
![images png](https://user-images.githubusercontent.com/1411118/183560514-2908d172-d9a1-4805-80ac-efdc20aea207.png)

normal state

**Comment by tomasky** [comment]
when  exist the same file name,this problem also occurs

**Comment by siduck** [comment]
weird that only 4 buffers show

**Comment by tomasky** [comment]
no , i opened six files

**Comment by siduck** [comment]
> no , i opened six files,here only displays four buffers

does it happen when nvimtree is on left?

**Comment by tomasky** [comment]
it doesn't seem to have that problem if nvimtree is on left. By the way, maybe:
```diff
--- a/lua/core/utils.lua
+++ b/lua/core/utils.lua
@@ -10,7 +10,7 @@ M.close_buffer = function(bufnr)
     print "save the file bruh"
   else
     bufnr = bufnr or api.nvim_get_current_buf()
-    require("core.utils").tabuflinePrev()
+    require("core.utils").tabuflineNext()
     vim.cmd("bd" .. bufnr)
   end
 end

```

**Comment by siduck** [comment]
i dont understand why changing this function would fix this issue :thinking:

**Comment by tomasky** [comment]
> i dont understand why changing this function would fix this issue thinking

no , this change has nothing to do with the question, just a suggestion

**Comment by tomasky** [comment]
by the way, if i open more then 10 files, tbufpick command will have some problems, so you shouldn't use the index of vim.t.bufs

**Comment by siduck** [comment]
> by the way, if i open more then 9 files, tbufpick command will have some problems, so mabe you shouldn't use the index of vim.t.bufs

problems like? show a vid!

**Comment by tomasky** [comment]
i must input  char 11  ,but i only can input 0-9

**Comment by siduck** [comment]
> i must input char like 10, 11 ,but i only can input 0-9

oh maybe we can put a check in the tbufpick function

- if `#vim.t.bufs` > 9 then run that getchar function twice else only once

**Comment by tomasky** [comment]
That's a solution too, but I think we should renumber buf,　it is the most convenient to use

**Comment by siduck** [comment]
> That's a solution too, but I think we should renumber visible buf,　it is the most convenient to use

renumber visible buf? i dont get it

**Comment by tomasky** [comment]
Normally, tabufline only shows 4-6 buffers.  just need to number these buffers

**Comment by siduck** [comment]
> Normally, tabufline only shows 4-6 buffers. just need to number these buffers

depends on your screen size too

**Comment by tomasky** [comment]
There are usually no more than nine

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/184467794-8fa92e13-5b68-4ea0-bb43-5da867784875.png)

yes thats normal, just cycle around the buffers

**Comment by siduck** [comment]
more than 9 cuz lots of space was saved by decreasing terminal font

![image](https://user-images.githubusercontent.com/59060246/184467838-3149cb46-5b80-43cd-ba23-d49891281434.png)

**Comment by tomasky** [comment]
My computer screen is already large, but it only displays six at most，　Why can your computer  show so much
You adjust your resolution?

**Comment by tomasky** [comment]
My computer screen is already large, but it only displays six at most，　Why can your computer  show so much
You adjust your resolution?

**Comment by siduck** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/184467794-8fa92e13-5b68-4ea0-bb43-5da867784875.png)
> 
> yes thats normal, just cycle around the buffers

this is my actual resolution and shows 9 buffers at max 

my screen resolution : `1920 x 1080` and screen width `40.6cm`

**Comment by tomasky** [comment]
desktop？,oh Mine is a laptop　,Envy your screen

**Comment by siduck** [comment]
> desktop？,oh Mine is a laptop　,Envy your screen

no its a laptop, acer nitro 5 

![image](https://user-images.githubusercontent.com/59060246/184470147-cf886882-a12c-401d-bad6-2be329b8bdf1.png)

**Comment by tomasky** [comment]
screen width 40.6cm? oh I misread and  thought it was 40 inches, your computer should be  15.6 inches like my computer,but the resolution is higher than mine
