### ISSUE TITLE
Opening Dashboard/Alpha when all buffer closed

### ISSUE THREAD

**Issue by notokrs** [NvChad/ui#62]
**Is your feature request related to a problem? Please describe.**
Not a problem, but it will be nice if after all buffer closed then open the dashboard instead new empty buffer :)

**Additional context**
I think it's a bit suboptimal if the alpha only appears for the first time when opening nvim.

**Comment by siduck** [comment]
hi @notokrs, can you install nvchad v2.0 ? just clone the v2.0 branch and open nvim.

I have written my own dashboard module for it, :NvDash is the command and just enable its load_on_startup option in default_config.lua.

**Comment by notokrs** [comment]
I haven't tried it yet, maybe I will. 

But is the custom configuration still the same as the main branch one?

**Comment by siduck** [comment]
> I haven't tried it yet, maybe I will.
> 
> But is the custom configuration still the same as the main branch one?

some changes, v2.0 is using 100% lazy.nvim so the syntax looks a lil different.

**Comment by nzlov** [comment]
In v2.0
no open nvdash when all buffer closed.
and has a empty buffer when use nvdash open file.

**Comment by siduck** [comment]
> In v2.0 when all buffer closed, no open nvdash , only a empty bufffer. and has a empty buffer when use nvdash open file.

will try to fix soon!

**Comment by siduck** [comment]
> In v2.0 when all buffer closed, no open nvdash , only a empty bufffer. and has a empty buffer when use nvdash open file.

https://github.com/NvChad/ui/issues/60
