### ISSUE TITLE
v2.0 tabbufline error

### ISSUE THREAD

**Issue by nvthuong1996** [NvChad/ui#63]
i run nvim with command
```
docker run -w /root -it --rm alpine:latest sh -uelic '
  apk add git nodejs neovim ripgrep alpine-sdk --update
  git clone https://github.com/NvChad/NvChad ~/.config/nvim
  nvim
  '
```
when i open file from nvimtree

![image](https://user-images.githubusercontent.com/24992586/224583066-92d22d5f-22fb-4df0-a4c9-6a5ee856c4be.png)

**Comment by siduck** [comment]
hi @nvthuong1996 could   you share a video of  this?

**Comment by KorigamiK** [comment]
I experience the same issue. Is there any update?

**Comment by siduck** [comment]
> I experience the same issue. Is there any update?

i will look into this , this weekend

**Comment by siduck** [comment]
> I experience the same issue. Is there any update?

fixed!
