### ISSUE TITLE
[Dashboard] Disappears without throwing error if ASCII art has several more lines than default

### ISSUE THREAD

**Issue by DanWiseProgramming** [NvChad/ui#64]
**Describe the bug**
Whenever the header text is set to include a few more lines than the default, the dashboard fails to appear on startup.
This is an issue with the v2 NvChad release and was not an issue with the Alpha dashboard (v1 release).

**To Reproduce**
1. Enable dashboard on startup in configuration.
2. Copy and a paste a 6 extra lines to the default ASCII image.
3. Restart neovim and see that the dashboard appears for a split-second before it disappears and you are left with a new Unnamed buffer.
4. Remove extra lines.
5. Restart neovim.
6. See that dashboard is appears as expected.

**Expected behavior**
Dashboard should throw an error and maybe support extra lines of ASCII art.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS
 - neovide 0.10.3
 - Version of Neovim v0.8.3

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/225322652-3318d65b-ca7b-448c-9a14-e8bd7bc20006.png)

you sure?

**Comment by siduck** [comment]
show a video

**Comment by DanWiseProgramming** [comment]
Hmm, just re-tested just through iTerm2. It appears to be an issue isolated to Neovide. Apologies.
