### ISSUE TITLE
Nvdash won't open

### ISSUE THREAD

**Issue by Hurricaane** [NvChad/ui#66]
**Describe the bug**
Hi ! I'm somewhat of a new user of neovim. I wanted to try Nvchad. Everything went great for the install, but when I want to setup Nvdash, it doesn't work. Nothing appears, even after inputting the command `Nvdash`.

Here's my `chadrc.lua` : 

```lua
-- Chadrc file
-- Custom NvChad configuration (main file)
local M = {}

-- UI Settings
M.ui = {
  -- Theme
  theme = "onedark",
  -- Dashboard
  nvdash = {
    load_on_startup = true,

    header = {
      [[]],
      [[   ⣴⣶⣤⡤⠦⣤⣀⣤⠆     ⣈⣭⣭⣿⣶⣿⣦⣼⣆         ]],
      [[    ⠉⠻⢿⣿⠿⣿⣿⣶⣦⠤⠄⡠⢾⣿⣿⡿⠋⠉⠉⠻⣿⣿⡛⣦       ]],
      [[          ⠈⢿⣿⣟⠦ ⣾⣿⣿⣷⠄⠄⠄⠄⠻⠿⢿⣿⣧⣄     ]],
      [[           ⣸⣿⣿⢧ ⢻⠻⣿⣿⣷⣄⣀⠄⠢⣀⡀⠈⠙⠿⠄    ]],
      [[          ⢠⣿⣿⣿⠈  ⠡⠌⣻⣿⣿⣿⣿⣿⣿⣿⣛⣳⣤⣀⣀   ]],
      [[   ⢠⣧⣶⣥⡤⢄ ⣸⣿⣿⠘⠄ ⢀⣴⣿⣿⡿⠛⣿⣿⣧⠈⢿⠿⠟⠛⠻⠿⠄  ]],
      [[  ⣰⣿⣿⠛⠻⣿⣿⡦⢹⣿⣷   ⢊⣿⣿⡏  ⢸⣿⣿⡇ ⢀⣠⣄⣾⠄   ]],
      [[ ⣠⣿⠿⠛⠄⢀⣿⣿⣷⠘⢿⣿⣦⡀ ⢸⢿⣿⣿⣄ ⣸⣿⣿⡇⣪⣿⡿⠿⣿⣷⡄  ]],
      [[ ⠙⠃   ⣼⣿⡟  ⠈⠻⣿⣿⣦⣌⡇⠻⣿⣿⣷⣿⣿⣿ ⣿⣿⡇⠄⠛⠻⢷⣄ ]],
      [[      ⢻⣿⣿⣄   ⠈⠻⣿⣿⣿⣷⣿⣿⣿⣿⣿⡟ ⠫⢿⣿⡆     ]],
      [[       ⠻⣿⣿⣿⣿⣶⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⢀⣀⣤⣾⡿⠃     ]],
      [[     ⢰⣶  ⣶ ⢶⣆⢀⣶⠂⣶⡶⠶⣦⡄⢰⣶⠶⢶⣦  ⣴⣶     ]],
      [[     ⢸⣿⠶⠶⣿ ⠈⢻⣿⠁ ⣿⡇ ⢸⣿⢸⣿⢶⣾⠏ ⣸⣟⣹⣧    ]],
      [[     ⠸⠿  ⠿  ⠸⠿  ⠿⠷⠶⠿⠃⠸⠿⠄⠙⠷⠤⠿⠉⠉⠿⠆   ]],
      [[]],
    },

    buttons = {
      { "  Find File", "Spc f f", "Telescope find_files" },
      { "  Recent Files", "Spc f o", "Telescope oldfiles" },
      { "  Find Word", "Spc f w", "Telescope live_grep" },
      { "  Bookmarks", "Spc b m", "Telescope marks" },
      { "  Themes", "Spc t h", "Telescope themes" },
      { "  Mappings", "Spc c h", "NvCheatsheet" },
    },
  },
}

return M
```

**To Reproduce**
1. Freshly install Nvchad (v2.0)
2. Customize your `chadrc.lua` file to enable Nvdash on startup
3. Restart neovim
4. Launch command `:Nvdash`

**Expected behavior**
A dashboard with my custom header.

**Screenshots**
![image](https://user-images.githubusercontent.com/57406021/225906302-7fd198aa-50db-40fd-aa8f-dc56a95adfaa.png)

**Desktop (please complete the following information):**
 - Linux - OS : ZorinOS 16.2
 - Using Tmux inside of Wezterm
 - Neovim version : v0.8.3

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/225920559-b430c957-7f04-46f4-95a5-53947e6dd142.png)

works for me

**Comment by siduck** [comment]
nvdash = {
    load_on_startup = true,
    header = {
      "   ⣴⣶⣤⡤⠦⣤⣀⣤⠆     ⣈⣭⣭⣿⣶⣿⣦⣼⣆         ",
      "    ⠉⠻⢿⣿⠿⣿⣿⣶⣦⠤⠄⡠⢾⣿⣿⡿⠋⠉⠉⠻⣿⣿⡛⣦       ",
      "          ⠈⢿⣿⣟⠦ ⣾⣿⣿⣷⠄⠄⠄⠄⠻⠿⢿⣿⣧⣄     ",
      "           ⣸⣿⣿⢧ ⢻⠻⣿⣿⣷⣄⣀⠄⠢⣀⡀⠈⠙⠿⠄    ",
      "          ⢠⣿⣿⣿⠈  ⠡⠌⣻⣿⣿⣿⣿⣿⣿⣿⣛⣳⣤⣀⣀   ",
      "   ⢠⣧⣶⣥⡤⢄ ⣸⣿⣿⠘⠄ ⢀⣴⣿⣿⡿⠛⣿⣿⣧⠈⢿⠿⠟⠛⠻⠿⠄  ",
      "  ⣰⣿⣿⠛⠻⣿⣿⡦⢹⣿⣷   ⢊⣿⣿⡏  ⢸⣿⣿⡇ ⢀⣠⣄⣾⠄   ",
      " ⣠⣿⠿⠛⠄⢀⣿⣿⣷⠘⢿⣿⣦⡀ ⢸⢿⣿⣿⣄ ⣸⣿⣿⡇⣪⣿⡿⠿⣿⣷⡄  ",
      " ⠙⠃   ⣼⣿⡟  ⠈⠻⣿⣿⣦⣌⡇⠻⣿⣿⣷⣿⣿⣿ ⣿⣿⡇⠄⠛⠻⢷⣄ ",
      "      ⢻⣿⣿⣄   ⠈⠻⣿⣿⣿⣷⣿⣿⣿⣿⣿⡟ ⠫⢿⣿⡆     ",
      "       ⠻⣿⣿⣿⣿⣶⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⢀⣀⣤⣾⡿⠃     ",
      "     ⢰⣶  ⣶ ⢶⣆⢀⣶⠂⣶⡶⠶⣦⡄⢰⣶⠶⢶⣦  ⣴⣶     ",
      "     ⢸⣿⠶⠶⣿ ⠈⢻⣿⠁ ⣿⡇ ⢸⣿⢸⣿⢶⣾⠏ ⣸⣟⣹⣧    ",
      "     ⠸⠿  ⠿  ⠸⠿  ⠿⠷⠶⠿⠃⠸⠿⠄⠙⠷⠤⠿⠉⠉⠿⠆   ",
    },
  },

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/225921417-611c1ef8-3a82-42ee-b656-a0b5fea87901.png)

**Comment by siduck** [comment]
and then you can override nvdash highlight groups to invert the colors etc

**Comment by Hurricaane** [comment]
I reinstalled Nvchad, and launched `:Nvdash` which worked with the default config, but as soon as I change the config (replacing [[]] by ""), nothing works...

I don't know what I am doing wrong

**Comment by siduck** [comment]
@Hurricaane can you make a video? I find it hard to believe!

**Comment by siduck** [comment]
and make sure your fontsize isnt large or else the dashboard height wont be sufficient and hence dashboard wont open

**Comment by Hurricaane** [comment]
It was the fontsize (I feel dumb...) 
Sorry for the disturbance and thank you !

**Comment by inneroot** [comment]
> and then you can override nvdash highlight groups to invert the colors etc

@siduck Can you please share how to disable inverting of the picture? I the example in https://nvchad.com/docs/features dashboard screenshot, but cant find proper value in config

**Comment by siduck** [comment]
@inneroot read https://nvchad.com/docs/config/theming

1) find highlight groups associated with nvdash ( within base46 repo itself's integration dir )
2) add them to hl_override

Or if you are lazy to find in that repo, just type nvdash in hl_override table and  u will see the available hl groups, thanks to lucario

![image](https://github.com/NvChad/ui/assets/59060246/dfbf684d-56ff-48b9-ab78-1eee15161cc4)

so just set there bg to "none" and fg to some color :D

**Comment by inneroot** [comment]
Thx, @siduck, found config in [NvChad/base46 repo](https://github.com/NvChad/base46) 
Applied to chadrc.lua
```
M.ui = {
  hl_override = {
    NvDashAscii = {
      fg = "blue",
      bg = "black",
    },
  },
```
![image](https://github.com/NvChad/ui/assets/26004035/9faf9441-df1c-4e3b-b236-52e097a92650)
