### ISSUE TITLE
signature.lua:1: attempt to index field 'lsp' (a nil value)

### ISSUE THREAD

**Issue by sykuang** [NvChad/ui#67]
Hi,
I am getting an error message as the below. I am using v2.0 branch.
`Error executing vim.schedule lua callback: ...ng/.local/share/nvim/lazy/ui/lua/nvchad_ui/signature.lua:1: attempt to index field 'lsp' (a nil value)`
After remove `local config = require("core.utils").load_config().ui.lsp.signature` everything works fine.
I take a quick look at NvChad v2.0 and the example config, but I can't find any member named `lsp` in the ui config. Could you help take a look?

**Comment by siduck** [comment]
hi @sykuang do lazy sync
