### ISSUE TITLE
Dashboard not working on V2.0

### ISSUE THREAD

**Issue by MadeByJay** [NvChad/ui#71]
Pulled and installed NvChad yesterday and the dashboard seems to not work. Whenever I `nvim .` into a code base I just get a blank/empty screen instead of the dashboard with the header graphics. 

Everything else still works, and I'm loving it. The blank screen on startup is a little disorienting tho. I checked Lazy on startup in a project and the UI package looks to be loaded - just no Dashboard.

Using NVIM v0.8.3 on WSL. Let me know what other info I can provide for debugging.

I believe I have dashboard enabled in .chadrc:
``` 
M.ui = {
...other config stuff...
 
  nvdash = {
    load_on_startup = true,
  }
}
```

**Comment by siduck** [comment]
hi @sanchay9  did you increase your font size too much? if there's less height available for dashboard then it wont open

**Comment by MadeByJay** [comment]
Font-size is 14. Tried smaller/bigger sizes with no change. Is there a debug option to show logs? Will check docs in a bit.

**Comment by siduck** [comment]
BTW just run nvim and not nvim .

**Comment by mikededo** [comment]
I have it working. Do you have your configuration in github so we can check it out?

**Comment by MadeByJay** [comment]
Solved: It was using `nvim` vs `nvim .`

I get the awesome dashboard now. My bad if I missed that in the docs. Is NvChad grabbing the working directory on it's own? Pretty nice behavior just didn't expect it. I still have to dot into my working dir with other setups I think.

**Comment by siduck** [comment]
@MadeByJay isnt nvim . the same as just nvim? btw if you want to have this behavior `nvim somedir` then add this function in  your shell config i.e bashrc , zshsrc etc

`nv() { cd "${1:-.}" && nvim; }` 

usage : `nv somedir`

**Comment by MadeByJay** [comment]
@siduck I think so - I'm just used to handing vim a path from working on ssh servers instead of cd-ing everywhere. Unless it's a new workspace. So typing `nvim .` is pretty natural for me to use only because I might start adding/tabbing a path to a folder/file.

So currently if a user does `nvim path/to/folder` they won't get the Nv dashboard. They have to cd there or use a similar function to your example.

Not a real issue. Just a workflow difference I think

**Comment by siduck** [comment]
> @siduck I think so - I'm just used to handing vim a path from working on ssh servers instead of cd-ing everywhere. Unless it's a new workspace. So typing `nvim .` is pretty natural for me to use only because I might start adding/tabbing a path to a folder/file.
> 
> So currently if a user does `nvim path/to/folder` they won't get the Nv dashboard. They have to cd there or use a similar function to your example.
> 
> Not a real issue. Just a workflow difference I think

nvim . would work on vanilla nvim but in nvchad we have disabled netrw as we're using nvimtreee and I recall nvim-tree provides an autocmd in its docs to auto-cd but i think my alias is easier :laughing:
