### ISSUE TITLE
Is there some option to limit lsp message length?

### ISSUE THREAD

**Issue by hankji** [NvChad/ui#72]
if some err in lsp status like this:
![image](https://user-images.githubusercontent.com/4995120/227114246-4f705c5f-b205-413b-b42e-bc59f60b2b26.png)

how can I limit the lsp message length?
thank u !

**Comment by siduck** [comment]
hi @hankji there isn't any but added it for you. 

```lua
M.ui = {
  statusline = {
    theme = 'vscode',
    lsprogress_len = 15,
  },
}
```

**Comment by hankji** [comment]
thank u so much
