### ISSUE TITLE
Having `NvChad/ui` as a plugin

### ISSUE THREAD

**Issue by mikededo** [NvChad/ui#73]
I'm rewritting part of the `statusline` configuration and I would like to change the `run` function. However, there are some modules that I would like to keep from the default configuration. So, copying everyting inside `nvchad_ui.statusline.minimal` and then it can be changed. Still, there are too many things that I would have to clone internally.

It would be ideal that we could `require('NvChad/ui')` and then use whatever dependencies that we need.

Is it doable?

**Comment by siduck** [comment]
@mikededo i'd suggest you to override the modules https://nvchad.com/docs/config/nvchad_ui

**Comment by mikededo** [comment]
Hm, so having this inside the function would not break?

```lua 
local st_modules = require "nvchad_ui.statusline.default"
```

I was trying to import file wide.

**Comment by mikededo** [comment]
Yep, that works. However the `run` it is not override. Any recommendation?

**Comment by siduck** [comment]
> Yep, that works. However the `run` it is not override. Any recommendation?

hmm the run function is just for positioning the modules,  why do you want to override it?

**Comment by mikededo** [comment]
For example to change the position of the elements, to add or hide elements. To hide/remove elements, we just have to return an empty string from the module, don't we? We could probably add this in to the docs.
