### ISSUE TITLE
feature: when cheatsheet is visible, typing should reduce the listed keymaps to those that match the typed text 

### ISSUE THREAD

**Issue by airtonix** [NvChad/ui#75]
would help finding particular keymaps, especially if i put `#this` `#and` `#that` `#the` `#other` in my keymap descriptions

- [x] willing to try provide a PR

**Comment by siduck** [comment]
I think you can search with / ?

**Comment by airtonix** [comment]
> I think you can search with / ?

Ok that seems to work if the amount of things are entirely fitting on one screen.

But when the cheatsheet requires scrolling, what then? 

I mean I'm a mouse using `<c-c>`, `<c-v>`, `<c-s>`, kind of heretic. the kind that will spend months and months crafting keymaps so i can avoid vim motions. Dont want them don't need them.
I'm now going to spend the next 10 years trying to work out how to avoid typing `/?` and instead make that work with `<c-f>` like the rest of the planet does.

So this kind of user will find the cheatsheet helpful.


I mean if this is too hard, then how about creating a grid renderer for telescope?

**Comment by siduck** [comment]
`Telescope current_buffer_fuzzy_find`

**Comment by siduck** [comment]
btw searching with / will autoscroll to the matched text too. I dont think i'd have to implement a telescope picker for this. Just use Telescope keymaps then.
