### ISSUE TITLE
option to only display modified buffers in Tabufline?

### ISSUE THREAD

**Issue by jonahlund** [NvChad/ui#78]
It would be helpful if there was a way to only display modified buffers in Tabufline, like in vscode, because it's often hard to navigate when every opened buffer displays as a new tab.

**Comment by siduck** [comment]
could you show an image?

**Comment by jonahlund** [comment]
![only_show_modified_tabs_in_tabufline](https://user-images.githubusercontent.com/126015019/227951261-7907c109-84c6-4e01-8cde-8e685c810903.png)
Like this, where the modified tabs 'stay' meanwhile non modified tabs gets overriden if you open another file for example, if that makes sence

**Comment by siduck** [comment]
override non-modified? you mean hide non-modified?

**Comment by jonahlund** [comment]
Yeah well hide or override, basically if you open a file it opens it like it normally does and shows the tab, and if you open another file it hides (overrides) the previous tab unless that tab was modified, which keeps it much more organized if you move between alot of files. I can show how vscode does it if you would like a better example

**Comment by siduck** [comment]
hmm add this in your custom init.lua file
```lua
vim.api.nvim_create_autocmd({ "BufAdd", "BufEnter", "tabnew" }, {
  callback = function()
    local bufs = {}

    for _, bufnr in ipairs(vim.t.bufs) do
      if vim.api.nvim_buf_get_option(bufnr, "modified") then
        table.insert(bufs, bufnr)
      end
    end

    vim.t.bufs = bufs
  end,
})
```

**Comment by siduck** [comment]
that'll just show modified buffers and new buffer if its current buffer

**Comment by jonahlund** [comment]
Yes thats exactly what i ment!! Thanks alot. Im still wondering though if this should be a standard option, since many people would like to have this behaviour, not sure though. In any case i appreciate the help.

**Comment by siduck** [comment]
I will add this in the api section https://nvchad.com/docs/api

Basically our tabufline module saves buffer numbers in `vim.t.bufs` table variable . 

as the code I shared above runs in your custom.init.lua, that code runs after the default behavior code. it overrides the default behaviour and filters the modified buffer numbers only.

**Comment by siduck** [comment]
if you need shorter code!

```lua
vim.api.nvim_create_autocmd({ "BufAdd", "BufEnter", "tabnew" }, {
  callback = function()
    vim.t.bufs = vim.tbl_filter(function(bufnr)
      return vim.api.nvim_buf_get_option(bufnr, "modified")
    end, vim.t.bufs)
  end,
})
```
