### ISSUE TITLE
Show which folder name , only (not the complete path), the file belongs in tabufline

### ISSUE THREAD

**Issue by TiLopes** [NvChad/ui#79]
Using this example:
![image](https://user-images.githubusercontent.com/106965010/228310825-0ed3248e-1ebb-404d-b7bd-f2f7a19eba77.png)
I can't see which file I'm actually editing.

How could I override this behavior?

**Comment by siduck** [comment]
@TiLopes will look onto this tomorrow, for now just look at your statusline, it shows current filename

**Comment by TiLopes** [comment]
Thank you! Since if you have files with the same name it can be confusing, although the statusline helps but if the user does not pay attention they may change the wrong file.

**Comment by kingavatar** [comment]
@siduck @TiLopes I think this issue is resolved by the latest PR https://github.com/NvChad/ui/pull/76, with this you should only see unique directory name and filename in tabufline
