### ISSUE TITLE
NvChad doesn't open file I want after Lazy Prompt

### ISSUE THREAD

**Issue by greed-d** [NvChad/ui#88]
**Describe the bug**
When I install a new plugin via `custom/plugin.lua`, close nvim and then open a file [say `custom/plugin.lua`] the lazy prompts opens and installs the plugin but the file doesn't open

**To Reproduce**
1. Go to `lua/custom/plugins.lua` [ for example ]
2. Add a new plugin and close nvim
3. Try to open a file [ say `custom/plugin.lua`]
4. The lazy prompt opens and installs plugin but after that doesn't open the file I want [ `custom/plugin.lua` in my case ]

**Expected behavior**
Open the file I want after lazy finishes installing the plugin

**Screenshots

https://user-images.githubusercontent.com/58597122/231165786-820df4d7-6d59-4a9c-bc68-a9de4c3b8bf6.mp4

**

**Desktop (please complete the following information):**
- OS : 
 Arch Linux 6.2.10-zen1-1-zen
- Terminal : 
 alacritty 0.12.0 (5a728195)
- Neovim : 
`NVIM v0.9.0 `
`type: Release`
`LuaJIT 2.1.0-beta3`

**Comment by greed-d** [comment]
https://user-images.githubusercontent.com/58597122/231181526-eae59804-55bf-47da-81c3-22023ab95030.mp4

And don't watch these video in firefox !!

**Comment by siduck** [comment]
@GRR3ED does it occur when u disable dashboard?

**Comment by greed-d** [comment]
@siduck Yes, it does open after disabling dashboard

**Comment by siduck** [comment]
ok so i was right, this is nvdash's issue. I'm glad i moved this to the UI repo beforehand :D . will check on this tomorrow

**Comment by siduck** [comment]
I was a lil  busy, will fix today
