### ISSUE TITLE
entering a file from telescope makes it automatically enter insert mode

### ISSUE THREAD

**Issue by lucario387** [NvChad/ui#89]
**Describe the bug**
Like the title suggest, entering a second file makes it go into insert mode right when entering

**To Reproduce**
1. cd ~/.config/nvim && nvim
2. `:Telescope find_files`
3. open any file
4. `:Telescope find_files` again
5. Open a different file

**Expected behavior**
To not enter insert mode upon pressing enter

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: Archlinux 
 - Terminal: Kitty
 - Version of Neovim: nvim-0.10.0-dev

**Additional context**

**Comment by siduck** [comment]
can reproduce the issue with nvim 0.10, but not 0.8.3

**Comment by lucario387** [comment]
https://github.com/neovim/neovim/commit/d52cc668c736ef6ca7ee3655a7eb7fe6475afadc 
@siduck commit that introduces the issue, which will be backported to 0.9.1

**Comment by siduck** [comment]
Hmm so not related to nvchad

**Comment by lucario387** [comment]
> Hmm so not related to nvchad

Don't close it, this is related. I cannot reproduce the same error with telescope with `nvim --clean`
This is related to tabufline, surprisingly

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/233525497-ebde7c7d-f094-4628-8d9f-d116ff91fa7e.mp4

@lucario387  unable to reproduce!!

**Comment by ctrl-alt-adrian** [comment]
I'm able to reproduce this.  It's been happening for a few weeks now.

**Comment by siduck** [comment]
> I'm able to reproduce this. It's been happening for a few weeks now.

seems like its an issue with our tabufline module

**Comment by siduck** [comment]
> I'm able to reproduce this. It's been happening for a few weeks now.

```lua
-- bootstrap plugins & lazy.nvim
local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim" -- path where its going to be installed

if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath,
  }
end

vim.opt.rtp:prepend(lazypath)

local plugins = {

  {
    "nvim-telescope/telescope.nvim",
    dependencies = "nvim-lua/plenary.nvim",
    config = function()
      require("telescope").setup()
    end,
  },
}

require("lazy").setup(plugins)

vim.keymap.set("n", "<Space>fo", ":Telescope oldfiles <CR>", {})

-- create issue
vim.api.nvim_create_autocmd({ "BufAdd", "BufEnter" }, {
  callback = function(args)
    if vim.bo[args.buf].buflisted then
    end
  end,
})
```

minimal config to reproduce this, so i think its related to upstream.

So for now just use neovim 0.9 or 0.8.3

**Comment by lucario387** [comment]
It's actually closed now, not 3 weeks ago @siduck

**Comment by siduck** [comment]
> It's actually closed now, not 3 weeks ago @siduck

can  you link the issue?

**Comment by lucario387** [comment]
https://github.com/neovim/neovim/commit/b46f61ac050e6eb530ceb4d4b510b612596427c5
