### ISSUE TITLE
Navigate among buffers like `BufferLine`?

### ISSUE THREAD

**Issue by GreenSleeper** [NvChad/ui#90]
I used to navigate through buffers using `<leader>1` `<leader>2` and so on in `BufferLine`, is there any way to do that in `tabufline`?

**Comment by siduck** [comment]
https://nvchad.com/docs/api

check GotoTab section, put it in custom/init.lua ( change mapping in it,  A- to leader )

**Comment by GreenSleeper** [comment]
forgive me, but how to display the numbers of tabs with `tabufline`?
