### ISSUE TITLE
Accomodate for currently unhandled editor modes in statusline

### ISSUE THREAD

**Issue by ritiek** [NvChad/ui#91]
I stumbled upon one such editor mode `ntT`, which can be entered through:

1. Launch `nvim`.
2. Run `:terminal`.
3. Enter into insert mode in this terminal with <kbd>i</kbd>.
4. Enter into normal mode using `<C-\><C-o>`.
5. Nvim raises the following:

```lua
.../share/nvim/lazy/ui/lua/nvchad_ui/statusline/default.lua:174: in function <.../share/nvim/lazy/ui/lua/nvchad_ui/statusline/default.lua:166>
E15: Invalid expression: v:lua.require('nvchad_ui.statusline.default').run()
Press ENTER or type command to continue
```

6. Statusline goes bad continuing post this error.

--------------------

List of all currently available modes in nvim can be found here: https://github.com/neovim/neovim/blob/c2e47e7bec0394a2cc12c8f83e3e5950ad99d1b4/runtime/doc/builtin.txt#L5579-L5615

Modes currently handled in statusline ui can be found here:
https://github.com/NvChad/ui/blob/3e52dbbfff31912a5d1897fcb15051ad62d0c300/lua/nvchad_ui/statusline/default.lua#L19-L47

I reproduced this on the latest commit on ui repo as of now 3e52dbbfff31912a5d1897fcb15051ad62d0c300. 

If accomodating for currently unhandled editor modes seems like a good idea, happy to make a PR!

**Comment by siduck** [comment]
hi @ritiek fixed!
