### ISSUE TITLE
Icons not loaded until reload theme

### ISSUE THREAD

**Issue by BrunoKrugel** [NvChad/ui#93]
After switching theme, the icons from the file tree will change (because they were not loaded before the theme switch).

Before:
![image](https://user-images.githubusercontent.com/30608179/234020447-51cdfeb3-5ef5-4fe2-b871-f09c3c04c3c8.png)

After:
![image](https://user-images.githubusercontent.com/30608179/234020502-3e559e76-7332-4458-a2b2-8dccfdd4dca8.png)

**Comment by siduck** [comment]
@BrunoKrugel  this happens only when you use the theme switcher right?

**Comment by BrunoKrugel** [comment]
Yes, which one is the correct icon?

**Comment by siduck** [comment]
> Yes, which one is the correct icon?

obviously the 1st one https://github.com/NvChad/ui/blob/v2.0/lua/nvchad_ui/icons.lua#L44

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/236607771-14f83e93-a141-4316-8c65-aafad0e00c96.mp4

unable to reproduce  it now

**Comment by BrunoKrugel** [comment]
Unable to reproduce it here now too, maybe some update fixed
