### ISSUE TITLE
Signature covering whole typing space screen

### ISSUE THREAD

**Issue by greed-d** [NvChad/ui#95]
![2023-04-27 13-09-05](https://user-images.githubusercontent.com/58597122/234794044-4224bbd5-02a3-41d0-bca1-f35c112c39b9.gif)

**Comment by siduck** [comment]
will try to fix this weekend! 

In case anyone wants to contribute, check our signature file https://github.com/NvChad/ui/blob/v2.0/lua/nvchad_ui/signature.lua

**Comment by siduck** [comment]
I've tried many signature plugins, they all face this issue. I dont think its fixable!! so use cmp signature plugin instead

```lua
{
    "hrsh7th/nvim-cmp",
    dependencies = {
      "hrsh7th/cmp-nvim-lsp-signature-help",
    },
    opts = {
      sources = {
        { name = "nvim_lsp" },
        { name = "luasnip" },
        { name = "buffer" },
        { name = "nvim_lua" },
        { name = "path" },
        { name = "nvim_lsp_signature_help" },
      },
    },
  }
```
and disable our signature inchadrc

```lua
M.ui = {
   lsp = {
     signature = {
       disabled = false,
    } 
  }
}
```

**Comment by siduck** [comment]
@hdsong2 this issue should be fixed now, max_height option exists!
