### ISSUE TITLE
Disable statusline in NvDash 

### ISSUE THREAD

**Issue by yoplat** [NvChad/ui#96]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem was.
The status line is active on startup on the NvDash splash screen

**Describe the solution you'd like**
Disable the statusline if buffer is NvDash

**Comment by siduck** [comment]
```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "nvdash",
  callback = function()
    vim.opt.laststatus = 0
  end,
})

vim.api.nvim_create_autocmd("BufWinLeave", {
  callback = function()
    if vim.bo.ft == "nvdash" then
      vim.opt.laststatus = 3
    end
  end,
})
```

put it in custom/init.lua
