### ISSUE TITLE
disable the bufferline and make tabs work like bufferline

### ISSUE THREAD

**Issue by Nithin745** [NvChad/ui#98]
I have followed this issue #52 to disable bufferline, but when i open the a buffer in new tab it only shows tab numbers.
i want to display filename and save status indicator before the the tab number, i want some help on how to achieve this.
thanks

**Comment by siduck** [comment]
@Nithin745 that'd require lots of effort if you're newbie to nvim

**Comment by Nithin745** [comment]
> @Nithin745 that'd require lots of effort if you're newbie to nvim

Yeah, i understand, but im not a completely new to nvim, i know some beginner to intermediate things , getting the list of 
buffer, buffer names.. etc
I know it is hard to do this, is there any module in nvchad_ui, which i can use to do this or i'll try to write a function to get 
the file name and i want to know where i need to put it in the UI config?

Please give me some idea or point me in the right direction, i'll also do some research on my own. 
Thanks

**Comment by siduck** [comment]
@Nithin745 https://github.com/NvChad/ui/blob/v2.0/lua/nvchad_ui/tabufline/modules.lua#L209
 
 So you have to override modules and just include this 
 
 your custom module + tablist 
 
 your custom module = buffer name + modified status

**Comment by Nithin745** [comment]
Okay thanks, i'll do my best to find something, if i succeeded, i'll post it here

**Comment by Nithin745** [comment]
> your custom module + tablist

So just to be clear i need to override `tablist()` module

> your custom module = buffer name + modified status

and i need to create one custom module that return buf name and modified status

Lastly in the override config, i need to give something like this, right?
```lua
  tabufline = {
    overriden_modules = function()
      local tabufline_modules = require "nvchad_ui.tabufline.modules"

      return {
        bufferlist = function()
          return ""
        end,

        buttons = function()
          return "%#TblineFill#%=" .. tabufline_modules.buttons()
        end,

        -- Here overriding tablist module
        tablist = custom_func
      }
    end,
  },
```

**Comment by siduck** [comment]
@Nithin745 keep this on hold for now, i'll help at evening

**Comment by Nithin745** [comment]
> @Nithin745 keep this on hold for now, i'll help at evening

Okay thank you so much.

**Comment by siduck** [comment]
hi @Nithin745 , sorry i totally forgot about this

```lua
tabufline = {
    lazyload = false,
    overriden_modules = function()
      local fn = vim.fn

      return {
        bufferlist = function()
          local icon = " 󰈚 "
          local filename = (fn.expand "%" == "" and "Empty ") or fn.expand "%:t" -- remove :t if u want full path

          if filename ~= "Empty " then
            local devicons = require "nvim-web-devicons"

            local ft_icon = devicons.get_icon(filename)
            icon = (ft_icon ~= nil and " " .. ft_icon) or ""

            -- add modified icon
            filename = filename .. (vim.bo[0].modified and "  " or "  ")
            filename = " " .. filename -- add left padding
          end

          return "%#St_file_info#" .. icon .. filename .. "%#TbLineBufOff#" .. "%=" -- "&= adds empty space between"
        end,
      }
    end,
  }
  ```
  
  ![image](https://user-images.githubusercontent.com/59060246/236606496-2656688a-6f26-4b9e-a9fa-8f377d4fe61d.png)

**Comment by Nithin745** [comment]
Thanks for giving me this, i modified this  little bit to use `tablist` instead of `buferlist`

```lua
  tabufline = {
    -- lazyload = false,
    overriden_modules = function()
      local fn = vim.fn
      local tabufline_modules = require "nvchad_ui.tabufline.modules"

      return {
        bufferlist = function()
          return ""
        end,
        buttons = function()
          return "%#TblineFill#%=" .. tabufline_modules.buttons()
        end,
        tablist = function()
          local result, number_of_tabs = "", fn.tabpagenr "$"
          local icon = " 󰈚 "

          if number_of_tabs > 1 then
            for i = 1, number_of_tabs, 1 do
              local filename = fn.bufname(fn.tabpagebuflist(i)[1])
              if filename == "" then
                filename = "Empty "
              else
                local devicons = require "nvim-web-devicons"
                filename = fn.fnamemodify(filename, ":t")
                local ft_icon = devicons.get_icon(filename)
                icon = (ft_icon ~= nil and " " .. ft_icon) or ""
              end
              local modified = fn.getbufvar(fn.tabpagebuflist(i)[1], "&mod")
              if modified == 1 then
                filename = filename .. "  "
              else
                filename = filename .. " "
              end
              local tab_hl = ((i == fn.tabpagenr()) and "%#TbLineTabOn# ") or "%#TbLineTabOff# "
              result = result .. ("%" .. i .. "@TbGotoTab@" .. tab_hl .. i .. icon .. " " .. filename)
              result = (i == fn.tabpagenr() and result .. "%#TbLineTabCloseBtn#" .. "%@TbTabClose@󰅙 %X") or result
            end

            local new_tabtn = "%#TblineTabNewBtn#" .. "%@TbNewTab@  %X"
            local tabstoggleBtn = "%@TbToggleTabs@ %#TBTabTitle# TABS %X"

            return vim.g.TbTabsToggled == 1 and tabstoggleBtn:gsub("()", { [36] = " " })
                or new_tabtn .. tabstoggleBtn .. result
          end
        end,
      }
    end,
  },

```
![2023-05-07_screenshot_138](https://user-images.githubusercontent.com/85417614/236644277-a91498ec-1f40-4171-9fda-c0690628ece8.png)

@siduck  Please let me know if this Okay or needs some optimizations

**Comment by siduck** [comment]
@Nithin745 looks fine to me!

**Comment by Nithin745** [comment]
@siduck  thank for the help, couldn't have done it without you
